### ISSUE TITLE
Build DNS records for Mesos.

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/mesos-dns#100]
Mesos: can you dig it?

Supporting DNS queries for the name `mesos` (or perhaps `mesos-master` and `mesos-slave` would be helpful for dynamic configuration of external software that needs to talk to the Mesos REST APIs.

**Comment by cmaloney** [comment]
See: https://github.com/mesosphere/mesos-dns/issues/82

**Comment by ConnorDoyle** [comment]
@cmaloney Thanks, I missed that one.  Looks like this one can be closed for now.

**Comment by cmaloney** [comment]
Would it still be handy for your use case to have {slave-id}.slave.mesos available though?  That one isn't provided yet.

**Comment by ConnorDoyle** [comment]
No need for it yet.  Anyhow, provided that the masters are discoverable then users can query state.json to fetch a list of slave hosts.
