### ISSUE TITLE
Add HTTP redirector

### ISSUE THREAD

**Issue by quofelix** [mesosphere/mesos-dns#111]
This way, any port that happens to be HTTP is reachable on a well-defined address via a web-browser.

You just need to add a wildcard DNS record (*.redir.corp.com) that points to the mesos-dns machine, run the mesos-dns http port on 80, and you can directly reach all tasks like so:

http://_prometheus._tcp.marathon.mesos.redir.corp.com

Probably not belonging into mesos-dns from a purist point of view, but it is so simple and useful. Not fluent in Go though, otherwise I'd do it myself.

I hacked this in Python: 
```
import urlparse
import SimpleHTTPServer
import SocketServer
import DNS

PORT = 80
HOSTNAME = 'redir.corp.com'

DNS.ParseResolvConf()
srv_req = DNS.Request(qtype = 'srv')

class Handler(SimpleHTTPServer.SimpleHTTPRequestHandler):
  def do_POST(self):
    return self.do_GET()

  def do_HEAD(self):
    return self.do_GET()

  def do_DELETE(self):
    return self.do_GET()

  def do_GET(self):
    if ':' in self.headers['Host']:
      host, port = self.headers['Host'].split(':')
    else:
      host = self.headers['Host']
    target = host.replace(HOSTNAME, '')
    print "Request to ", target, self.path

    srv_result = srv_req.req(target)
    for result in srv_result.answers:
      if result['typename'] == 'SRV':
        print "Found SRV for", target, result['data']
        prio, x, port, host = result['data']
        self.send_response(303)
        dest = "http://%s:%d%s" % (host, port, self.path)
        print "Redirecting to", dest
        self.send_header('Location', dest)
        self.end_headers()
        self.wfile.write('Redirecting to ' + dest)
        return

    self.send_error(404,'File Not %s' % target)
    return

SocketServer.BaseServer.allow_reuse_address = True
httpd = SocketServer.TCPServer(("", PORT), Handler)

print "serving at port", PORT
httpd.serve_forever()
```

**Comment by kozyraki** [comment]
@quofelix Not a bad idea Felix. We are actually adding an http interface for SRV records in v0.2. Let me ask to make sure there is no unexpected implication of adding this service and I will let you know.

**Comment by nickpoorman** [comment]
+1 I'm all for this

**Comment by tsenart** [comment]
Mesos-DNS is a DNS server with DNS and HTTP APIs. You're suggesting it also becomes a reverse proxy. I'm very hesitant to add more responsibilities to this project when it's trivial to configure any solid reverse proxy with the data provided by Mesos-DNS.

**Comment by jdef** [comment]
@tsenart this is HTTP redirection, not proxy, so it's a little more lightweight and shouldn't put too much load on the DNS server (or on us developers :) )

**Comment by tsenart** [comment]
@jdef: It's the responsibility of the client to choose which SRV answer to follow, not the DNS server's. How would the server choose an appropriate load-balancing strategy? Clients would start relying on this functionality and break under misaligned assumptions such as unhealthy endpoints returned.

**Comment by quofelix** [comment]
This is purely a convenience thing. Nowadays many services have http status pages and with this you can just access your services via a static URL directly.

We have for example a http://prometheus.redir/ internally that goes via a generic SRV redirector we wrote in Python. This way you can also connect simply services via their REST APIs. Just configure this static URL, no matter on which machine and port Mesos decides to schedule it.

What works well from our experience:

* Redirect with 307 codes.
* Set these headers in the response:

    Access-Control-Allow-Headers: Accept, Authorization, Content-Type, Origin
    Access-Control-Allow-Methods: GET
    Access-Control-Allow-Origin: *
    Access-Control-Expose-Headers: Date

**Comment by jdef** [comment]
@tsenart for responses that have multiple answers, mesos-dns should be randomizing the order of those answers. in that case, a redirector impl would just grab the first answer and redirect to that.

**Comment by tsenart** [comment]
@jdef: My point being, that I don't think the server ought to make such assumptions about how clients use answers.

**Comment by quofelix** [comment]
At the company formerly known as the big G, the URL looked like http://<task_no>.<job-name> ...

**Comment by tsenart** [comment]
@quofelix: Hello! I hadn't realised this was you :)

Answering your comment: I totally understand your use case, and it's quite convenient indeed. However, mesos-dns will be deployed in heterogenous environments which IMO limits our ability to make assumptions about how SRV answers shall be load-balanced and managed in a redirector of the kind you propose. I think the way to go is what you ended up doing. Writing this very simple redirector yourself, with your company specific policies and constraints encoded.

**Comment by tsenart** [comment]
By the way, we had something like that at SoundCloud too, built by your ex-colleagues :-) But it was an independent service from the DNS server, which makes sense. In our case, it was in everyones search domain and we could simply type `go/...`

**Comment by jdef** [comment]
in this case, our internal http redirector is the client. and I think one of the goals of providing randomized order for answers was to prevent client's from depending on the order. in this case i think the dependency on randomized order is fine (since it's documented mesos-dns behavior already) and we can document the dependency on randomized order in the redirect code.

we could also define a flag that disables this feature for people that don't want any services exposed this way, ever.

we also have a `tools/` directory. what about writing a standalone app that fits in there? `tools/dns-redir/main.go` for example...

**Comment by tsenart** [comment]
@jdef: I understand that in this case the HTTP redirector is the client, but again, the assumptions made are too opinionated for mesos-dns itself. We'd be better off implementing it as completely separate thing, in a separate repo. There should be zero code dependencies between these two.

**Comment by spacejam** [comment]
Random/RR LB strategies only work for trivial request / highly uniform service time distributions.  As a toy, this is fine as a separate tool, but I think that there is little reason to couple this in any way to mesos-dns.

**Comment by tsenart** [comment]
@quofelix: https://github.com/mesosphere/redir
