### ISSUE TITLE
Generator is re-using names for A records

### ISSUE THREAD

**Issue by JeffBurdette** [mesosphere/mesos-dns#126]
It appears that mesos-dns is re-using the same hostname for some A records.  Below is the log (in -v=2 mode) you will see that mesos-dns is assigning dbbuilderagent-s1.marathon.mesos to both mesos-01.my.net (192.168.55.1) and mesos-05.my.net (192.168.55.5).    It should have created a dbbuilder-agent-s3.marathon.mesos for 192.168.55.5 instead of reusing dbbuilder-agent-s1.marathon.mesos.  This is obviously wrong and will lead to issues as shown in the DNS query below -- where mesos-05's ports appear to be on mesos-01.

    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:166: Zookeeper says the leader is:  mesos-01.my.net:5050
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:127: reloading from master mesos-01.my.net
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:131: Warning: master changed to mesos-01.my.net
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [A]     dbbuilderagent.marathon.mesos.: mesos-03.my.net
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [A]     dbbuilderagent-s2.marathon.mesos.: mesos-03.my.net
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [SRV]   _dbbuilderagent._tcp.marathon.mesos.: dbbuilderagent-s2.marathon.mesos.:31793
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [SRV]   _dbbuilderagent._udp.marathon.mesos.: dbbuilderagent-s2.marathon.mesos.:31793
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [SRV]   _dbbuilderagent._tcp.marathon.mesos.: dbbuilderagent-s2.marathon.mesos.:31794
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [SRV]   _dbbuilderagent._udp.marathon.mesos.: dbbuilderagent-s2.marathon.mesos.:31794
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [A]     dbbuilderagent.marathon.mesos.: mesos-01.my.net
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [A]     dbbuilderagent-s1.marathon.mesos.: mesos-01.my.net
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [SRV]   _dbbuilderagent._tcp.marathon.mesos.: dbbuilderagent-s1.marathon.mesos.:31858
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [SRV]   _dbbuilderagent._udp.marathon.mesos.: dbbuilderagent-s1.marathon.mesos.:31858
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [SRV]   _dbbuilderagent._tcp.marathon.mesos.: dbbuilderagent-s1.marathon.mesos.:31859
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [SRV]   _dbbuilderagent._udp.marathon.mesos.: dbbuilderagent-s1.marathon.mesos.:31859
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [A]     dbbuilderagent.marathon.mesos.: mesos-05.my.net
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [A]     dbbuilderagent-s1.marathon.mesos.: mesos-05.my.net
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [SRV]   _dbbuilderagent._tcp.marathon.mesos.: dbbuilderagent-s1.marathon.mesos.:31467
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [SRV]   _dbbuilderagent._udp.marathon.mesos.: dbbuilderagent-s1.marathon.mesos.:31467
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [SRV]   _dbbuilderagent._tcp.marathon.mesos.: dbbuilderagent-s1.marathon.mesos.:31468
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [SRV]   _dbbuilderagent._udp.marathon.mesos.: dbbuilderagent-s1.marathon.mesos.:31468
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [A]     dbbuilderagent.marathon.mesos.: mesos-04.my.net
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [A]     dbbuilderagent-s24.marathon.mesos.: mesos-04.my.net
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [SRV]   _dbbuilderagent._tcp.marathon.mesos.: dbbuilderagent-s24.marathon.mesos.:31612
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [SRV]   _dbbuilderagent._udp.marathon.mesos.: dbbuilderagent-s24.marathon.mesos.:31612
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [SRV]   _dbbuilderagent._tcp.marathon.mesos.: dbbuilderagent-s24.marathon.mesos.:31613
    VERY VERBOSE: 2015/04/13 08:35:51 generator.go:431: [SRV]   _dbbuilderagent._udp.marathon.mesos.: dbbuilderagent-s24.marathon.mesos.:31613

The resulting DNS query is:

    ;; QUESTION SECTION:
    ;_dbbuilderagent._tcp.marathon.mesos. IN        SRV
    
    ;; ANSWER SECTION:
    _dbbuilderagent._tcp.marathon.mesos. 60 IN SRV  0 0 31858 dbbuilderagent-s1.marathon.mesos.
    _dbbuilderagent._tcp.marathon.mesos. 60 IN SRV  0 0 31859 dbbuilderagent-s1.marathon.mesos.
    _dbbuilderagent._tcp.marathon.mesos. 60 IN SRV  0 0 31467 dbbuilderagent-s1.marathon.mesos.
    _dbbuilderagent._tcp.marathon.mesos. 60 IN SRV  0 0 31468 dbbuilderagent-s1.marathon.mesos.
    _dbbuilderagent._tcp.marathon.mesos. 60 IN SRV  0 0 31793 dbbuilderagent-s2.marathon.mesos.
    _dbbuilderagent._tcp.marathon.mesos. 60 IN SRV  0 0 31794 dbbuilderagent-s2.marathon.mesos.
    _dbbuilderagent._tcp.marathon.mesos. 60 IN SRV  0 0 31612 dbbuilderagent-s24.marathon.mesos.
    _dbbuilderagent._tcp.marathon.mesos. 60 IN SRV  0 0 31613 dbbuilderagent-s24.marathon.mesos.

    ;; ADDITIONAL SECTION:
    dbbuilderagent-s2.marathon.mesos. 60 IN A       192.168.55.3
    dbbuilderagent-s2.marathon.mesos. 60 IN A       192.168.55.3
    dbbuilderagent-s1.marathon.mesos. 60 IN A       192.168.55.1
    dbbuilderagent-s1.marathon.mesos. 60 IN A       192.168.55.1
    dbbuilderagent-s1.marathon.mesos. 60 IN A       192.168.55.1
    dbbuilderagent-s1.marathon.mesos. 60 IN A       192.168.55.1
    dbbuilderagent-s24.marathon.mesos. 60 IN A      192.168.55.4
    dbbuilderagent-s24.marathon.mesos. 60 IN A      192.168.55.4

Below you can see what marathon says about the hosts and ports:

![marathon-dbbuilderagent](https://cloud.githubusercontent.com/assets/11924832/7116149/45509806-e1bd-11e4-882f-02920baa7160.png)

Running mesos-dns v0.1.1 that was pulled on April 2, 2015.

    [root@mesos-01 mesos-dns]# ./mesos-dns -version
    0.1.1

Pretty stock configuration:

    {
      "zk": "zk://prod-zk-1.my.net:2181,prod-zk-2.my.net:2181,prod-zk-3.my.net:2181/mesos",
      "refreshSeconds": 60,
      "ttl": 60,
      "domain": "mesos",
      "port": 53,
      "resolvers": ["192.168.0.4", "192.168.0.3"],
      "timeout": 5,
      "listener": "192.168.55.1",
      "email": "root.mesos-dns.mesos"
    }

Is this a known issue?  If so, is there a fix available?  If not, I'll be happy to provide any additional information to help resolve it.

**Comment by kozyraki** [comment]
@JeffBurdette thanks for spotting this. 
The root of the problems is the following: Marathon has started 4 tasks with the same name (dbbuilderagent). The current Mesos-DNS code generates the "-sN" nodes for each one independently. 
I can change the code to look for aliases in a day or two. I'll put the fix in the http branch which includes a major refactoring/cleanup of the code + an HTTP interface that will make using SRV records much easier.

**Comment by JeffBurdette** [comment]
I noticed it was generating -sN nodes for each one, but it was odd that it reused the same N value for 2 different hosts.  Will use of aliases require changes in marathon configuration or will this be handled by mesos-dns?

**Comment by kozyraki** [comment]
I should be able to provide you with unique values without any changes to
Marathon.

**Comment by JeffBurdette** [comment]
Thanks.

I pulled the http branch and noticed it will not compile.  Maybe in a state of flux?

[root@mesos-01 mesos-dns-http]# make build
--> Building mesos-dns
# _/opt/mesos-dns-http
./main.go:32: undefined: resolver.New
./main.go:35: config.DnsOn undefined (type records.Config has no field or method DnsOn)
./main.go:40: config.HttpOn undefined (type records.Config has no field or method HttpOn)
godep: go exit status 2
make: *** [build] Error 1

**Comment by kozyraki** [comment]
Try "make all"

**Comment by JeffBurdette** [comment]
Nope, no luck there either.  I see all those fields in records/config.go though...

[root@mesos-01 mesos-dns-http]# make clean
--> Cleaning mesos-dns

[root@mesos-01 mesos-dns-http]# make all
--> Restoring build dependencies
--> Testing mesos-dns
# _/opt/mesos-dns-http
./main.go:32: undefined: resolver.New
./main.go:35: config.DnsOn undefined (type records.Config has no field or method DnsOn)
./main.go:40: config.HttpOn undefined (type records.Config has no field or method HttpOn)
# _/opt/mesos-dns-http/resolver
resolver/resolver.go:121: too many arguments in call to t.ParseState
resolver/resolver.go:128: res.config.SOASerial undefined (type records.Config has no field or method 
SOASerial)
resolver/resolver.go:230: res.config.SOAMname undefined (type records.Config has no field or method 
SOAMname)
resolver/resolver.go:231: res.config.SOARname undefined (type records.Config has no field or method 
SOARname)
resolver/resolver.go:232: res.config.SOASerial undefined (type records.Config has no field or method 
SOASerial)
resolver/resolver.go:233: res.config.SOARefresh undefined (type records.Config has no field or 
method SOARefresh)
resolver/resolver.go:234: res.config.SOARetry undefined (type records.Config has no field or method 
SOARetry)
resolver/resolver.go:235: res.config.SOAExpire undefined (type records.Config has no field or method 
SOAExpire)
resolver/resolver.go:262: res.config.ExternalOn undefined (type records.Config has no field or 
method ExternalOn)
resolver/resolver.go:433: res.config.HttpPort undefined (type records.Config has no field or method 
HttpPort)
resolver/resolver.go:433: too many errors
godep: go exit status 2
make: *** [test] Error 1

**Comment by kozyraki** [comment]
Strange, not sure what is going on. 
Can you try first "cd $GOPATH/src/github.com/mesosphere/mesos-dns" and then "make all"?

**Comment by JeffBurdette** [comment]
Yes, that makes cleanly (I knew it would since I have been using it):

[root@mesos-01 mesos-dns-http]# cd $GOPATH/src/github.com/mesosphere/mesos-dns/
[root@mesos-01 mesos-dns]# make all
--> Testing mesos-dns
?       github.com/mesosphere/mesos-dns [no test files]
?       github.com/mesosphere/mesos-dns/logging [no test files]
ok      github.com/mesosphere/mesos-dns/records 0.013s
ok      github.com/mesosphere/mesos-dns/resolver        0.241s
?       github.com/mesosphere/mesos-dns/tools   [no test files]
--> Building mesos-dns

**Comment by kozyraki** [comment]
@JeffBurdette the original issue should be solved in the http branch. 
Give it a try. 
We'll merge it into the master soon.

**Comment by kozyraki** [comment]
The branch is merged on the master. Take a look. 
I will close this for now.
