### ISSUE TITLE
Add arbitrary dns records

### ISSUE THREAD

**Issue by stuart-warren** [mesosphere/mesos-dns#132]
I'd like to add arbitrary records to the zone controlled by mesos-dns.
Perhaps point to a static zone-like file in the config and read on start.
```
ns1    IN  A      192.168.0.1  ;name server definition     
*.lb    IN  A      192.168.0.2  ;load balancer wildcard definition
ftp    IN  CNAME  www.example.com.  ;ftp server definition
```
If noone has any major objections, I'll try hacking it in myself.

**Comment by itamar-yowza** [comment]
+1

**Comment by kozyraki** [comment]
The most difficult part about adding arbitrary records to Mesos-DNS is where are these records persisted. Meson-Dns is stateless and if it crashes your records will be lost. 
We have to decide what is a reasonable assumption for storage in a mesos cluster: ZK, the replicated log, something else? And how do we access it.

**Comment by tsenart** [comment]
@kozyraki: In static deployments of mesos-dns, using the filesystem for persistence is a valid use case. I'd expect this to be useful in some scenarios.

**Comment by sepiroth887** [comment]
+1 I have a requirement for this as well. What I'm thinking is to persist those records as part of the config/or an additional config. 

I.e. start mesos-dns with --staticDNS=./path/to/json 

Then read and validate the json and pass the values as a map down to the record generator. 

Format could be as simple as this: 

[{
   "fqdn" : "some.example.mesos",
   "type" : "A",
   "value": "100.0.0.1"
}]

I may get a PR ready for this as I really really need it soon to avoid using another DNS server (bind i guess) to manage the environment (which I'd really really don't want to do)

**Comment by tsenart** [comment]
@sepiroth887: Please refer to https://github.com/mesosphere/mesos-dns/blob/master/CONTRIBUTING.md if you intend to contribute.

**Comment by sepiroth887** [comment]
Of course. Looks reasonable. Would this thread suffice as the discussion or would you like me to open another with describing what exactly my approach would be? Either is fine by me

**Comment by tsenart** [comment]
Please open a new proposal issue and cross reference this one.

**Comment by sargun** [comment]
I would nudge to using BIND for this, and putting BIND behind Mesos-DNS for this purpose.

**Comment by stuart-warren** [comment]
Closing in favour of #274
