### ISSUE TITLE
support systemd socket activation

### ISSUE THREAD

**Issue by jdef** [mesosphere/mesos-dns#148]
It looks like the underlying DNS package already supports this:

https://github.com/miekg/dns/blob/5a357a6fc5e85268b929350aa6423e2d56dcc4ff/server.go#L201

there's some golang/systemd bindings from coreos:

https://github.com/coreos/go-systemd/tree/master/activation

**Comment by kozyraki** [comment]
@jdef what is the use case for this? The DNS service seems like something that should be up all the time, so not clear what it buys us. But maybe you have some fault-tolerance/restart in mind. @cmaloney do you have a use case for this?

**Comment by jdef** [comment]
having socket activation would allow clients to queue in the backlog if
mesos-dns crashes and restarts for some reason. otherwise, clients may just
hang for a bit until they timeout.

**Comment by cmaloney** [comment]
This needs to fallback gracefully on non-systemd systems. While for now we're only launching on Systemd systems, that isn't what we're going to be doing into the future.

I also worry about things backing up in the systemd queues. In the DCOS use case of mesos-dns we actually put an load balancer (Amazon ELB for instance), in front of all the mesos-dns instances, which should be able to route around failures / redirect requests to a functioning server.

**Comment by kozyraki** [comment]
Ok, this is about picking another option for recovery from failures. It may be useful and I do not object supporting this. It does not seem high priority though and queuing at the (failed) server side seems scary. That said, having multiple mesos-dns servers listed in resolv.conf is scary too, hence the load balancer in DCOS I assume.

**Comment by cmaloney** [comment]
The load balancer is primarily so that we have a stable IP address to get to mesos-dns so when we have a master failure, we can keep resolving things reasonably (If the mesos-dns fails, then how do we find out what the other masters are which might have functioning mesos-dns?). In practice we also found that fallback dns nameservers tend not to work correctly in quite a bit of software, so just having one which server which does healthchecks / routes around failures is preferable.

**Comment by jdef** [comment]
Agree that this is probably not high priority.

**Comment by tsenart** [comment]
Correct me if I'm wrong but most clients will retry DNS queries *anyways*. In non-persistent connection models, transient failures in availability are usually handled by client retries. With the given context, I don't think this proposal is worth the effort.
