### ISSUE TITLE
Make truncation to 24 characters optional

### ISSUE THREAD

**Issue by kozyraki** [mesosphere/mesos-dns#149]
But document it is not standard

**Comment by gomes** [comment]
@kozyraki you can see on http://www.rfc-base.org/txt/rfc-1123.txt that this limit can be higher:

RFC 952
1. A "name" (Net, Host, Gateway, or Domain name) is a text string up to 24
characters drawn from the alphabet (A-Z), digits (0-9), minus sign (-), and
period (.).  Note that periods are only allowed when they serve to delimit
components of "domain style names". (See RFC-921, "Domain Name System
Implementation Schedule", for background).  No blank or space characters are
permitted as part of a name. No distinction is made between upper and lower
case.  The first character must be an alpha character.  The last character
must not be a minus sign or period. 

RFC 1123
The syntax of a legal Internet host name was specified in RFC-952 [DNS:4].
One aspect of host name syntax is hereby changed: the restriction on the
first character is relaxed to allow either a letter or a digit.  Host
software MUST support this more liberal syntax. Host software MUST handle
host names of up to 63 characters and SHOULD handle host names of up to 255
characters.

**Comment by kozyraki** [comment]
@gomes good point. we'll get to it!
Thanks

**Comment by willroden** [comment]
+1 this.  Note also the part where a hostname can now start with a digit.  That would be very useful for us.

**Comment by jensendw** [comment]
+1

**Comment by altoplano** [comment]
Or be even more current and look at RFC 2181.

**Comment by jdef** [comment]
Is there a particular aspect of RFC2181 that you're interested in? Skimming
the doc .. it looks like the label and hostname length limits are the same
as in RFC1123.
