### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by kozyraki** [mesosphere/mesos-dns#15]
Provide packages for common Linux distributions

**Comment by timothysc** [comment]
ping me when it's further down the road.

**Comment by activars** [comment]
My question is kind of related. do you accept PR if I refactor this package to use Godeps to manage Golang dependencies?

**Comment by kozyraki** [comment]
@activars we definitely open to PRs on any topic, including packaging. @eyberg is more knowledgeable about godeps and can provide more focused feedback.

**Comment by activars** [comment]
Thanks, I will work on the godep first as it should help with the building/test consistency.

**Comment by kozyraki** [comment]
Please look at https://github.com/mesosphere/mesos-dns-pkg 
@timothysc is this what you were looking for?
