### ISSUE TITLE
unknown http.Client field 'Timeout' in struct literal

### ISSUE THREAD

**Issue by Semif3r** [mesosphere/mesos-dns#150]
On Ubuntu 14.04.2 LTS (full update), when i try to build with  
> go build -o /usr/local/mesos-dns/mesos-dns

I have this error
> github.com/mesos/mesos-go/detector
> ../../mesos/mesos-go/detector/standalone.go:73: unknown http.Client field 'Timeout' in struct literal

if i comment this line then i can build.

**Comment by kozyraki** [comment]
Could you please use godeps to make sure you are not missing a dependency?

cd $GOPATH/src/github.com/mesosphere/mesos-dns
make all

Let me know how it goes.

**Comment by jdef** [comment]
what version of go are you using?

On Wed, May 6, 2015 at 5:14 PM, Christos Kozyrakis <notifications@github.com
> wrote:

> Could you please use godeps to make sure you are not missing a dependency?
>
> cd $GOPATH/src/github.com/mesosphere/mesos-dns
> make all
>
> Let me know how it goes.
>
>

**Comment by Semif3r** [comment]
Hi to all,

@jdef 
Version
> go version go1.2.1 linux/amd64

Go is installed from Ubuntu repos.

@kozyraki 
In fact, i have this error two times. When i do 
> go get github.com/mesosphere/mesos-dns

And when i do 
> go build -o /usr/local/mesos-dns/mesos-dns

I have tried 
> godep save 

With path
> $HOME/src/github.com/mesosphere/mesos-dns/Godeps/_workspace

No message, no error but build failed again at line 73.Godeps.json exists with some stuff. 

I have tried "make all"
> make all
> --> Restoring build dependencies
> --> Testing mesos-dns
> ?       github.com/mesosphere/mesos-dns [no test files]
> ?       github.com/mesosphere/mesos-dns/logging [no test files]
> github.com/mesos/mesos-go/detector
> Godeps/_workspace/src/github.com/mesos/mesos-go/detector/standalone.go:73: unknown > http.Client field 'Timeout' in struct literal
> ok      github.com/mesosphere/mesos-dns/records 0.007s
> ok      github.com/mesosphere/mesos-dns/records/labels  0.004s
> FAIL    github.com/mesosphere/mesos-dns/resolver [build failed]
> ?       github.com/mesosphere/mesos-dns/tools   [no test files]
> ok      github.com/mesosphere/mesos-dns/util    0.070s
> godep: go exit status 2
> make: *** [test] Erreur 1

Same error...

I have tested on 3 virtual machines with same conf. I did this test there is 2 days ago on CentOS 7.1 (full update too) with no error.

When i comment line 73, i can build and mesos-dns seems working correctly for the moment. But i imagine that isn't very stable... I have not checked how code it works, no time for this.

I'm working on a lab, well no urgency. 

Thanks for your responses.

**Comment by jdef** [comment]
You'll want to upgrade to at least golang 1.3

**Comment by Semif3r** [comment]
Ubuntu doesn't distribute this version in repositories for 14.04.2 LTS Server  :(

I'm trying to run a mesosphere environment on an OS with long term support to have "production vision" and honestly, after test Centos7 and Debian 8, Ubuntu is the more stable lab that i have tried. Surprising to me.

With more updated systems, i'm facing with more problems. I cannot have everything... Well, maybe an another repo for golang ?

**Comment by jdef** [comment]
You can follow the steps listed here (from the "Debian" section) to get Go
1.4.2. It's pretty short and sweet.

https://github.com/mesosphere/kubernetes-mesos/blob/master/DEVELOP.md#debian

**Comment by Semif3r** [comment]
I will try that at work and i send you a feedback. Thanks.

**Comment by jdef** [comment]
@Semif3r any update?

**Comment by jdef** [comment]
closing this out, please re-open if needed
