### ISSUE TITLE
Potential bug in dns952.go

### ISSUE THREAD

**Issue by jensendw** [mesosphere/mesos-dns#154]
I looked through the code but couldn't figure out a logical reason why this was happening.  Maybe I'm just misunderstand RFC952 but it should allow all numbers as long as the first character is an alpha character.

Here is what I'm seeing:

If I have an app called /angrypigs/dev/r29f it gets converted to r2f-dev-angrypigs.marathon.mesos

/angrypigs/dev/rel-2.9 = rel2-angrypigs-mooh.marathon.mesos

**Comment by jdef** [comment]
Thanks for reporting this. Fix on the way.
