### ISSUE TITLE
balancing over a same port 

### ISSUE THREAD

**Issue by eddytrex** [mesosphere/mesos-dns#156]
I have an application running on port X and three levels therefore I have three ex ports. x1 x2 x3.
I ran Mesos-dns and I have a name for the application, app.marathon.mesos.I can access the applications using app.marathon.mesos: x1, x2, x3.

Is there any way to add a port to the name and not use the ports assigned?

**Comment by kozyraki** [comment]
@eddytrex If you have 3 identically named tasks app.marathon.mesos, every time you lookup an A record for app.marathon.mesos, you will the (up to) 3 IP address back in a random order. So, unless x1, x2, and x3 is identical port numbers, using app.marathon.mesos: x1 will not work consistently as you may get app.marathon.mesos to translate to the IP address for the task that uses x2. 

If you pass port numbers to Mesos-DNS, you will get SRV records. If you look up "dig SRV _app._tcp.marathon.mesos" you will get back 3 pairs of IP:x and you can use any of these to access your app. So, you need code to parse the SRV reply. Alternatively, you can use the HTTP interface to get the same info (may be easier to parse). 

Hope this helps.

**Comment by eddytrex** [comment]
Thanks for the answer, so  if I have an other application how need the first (app.marathon.mesos.) I need to Lookup srv records and obtain the ports.
