### ISSUE TITLE
Serve master and slave hostnames as a-record

### ISSUE THREAD

**Issue by jstabenow** [mesosphere/mesos-dns#159]
Is it planed to add the hostnames of the mesos-master and mesos-slaves as a a-record? it would be a very nice addition! so we can reach the HOST-Env (like HOST=slave1) without seperate dns-resolver...

examples: 
"hostname".mesos 3600 IN A "10.11.12.13"
"hostname".slave.mesos 3600 IN A "10.11.12.13"
"hostname".master.mesos 3600 IN A "10.11.12.13"

**Comment by kozyraki** [comment]
Hi @jstabenow , this is an interesting idea. 
I can see one issue though, that of consistency of numbering. Mesos-DNS pulls the state.json endpoint from the master. If that one describes 5 slaves (e.g., A, B, C, D, E) it can generate A records for slave-{0,1,2,3,4}. However, let's suppose that later on, slave B catches fire. When Mesos-DNS pulls the state again, it will read {A, C, D, E}. If we proceed naively, C, D, and E will change numbering. Similar issues will occur if other slaves are added or removed later, or if Mesos-DNS fails and restarts. 

How important is name consistency for your use case? If not, the implementation is trivial. If yes, we need to find a way to persist past numbering state, probably in zookeeper.

**Comment by jstabenow** [comment]
Hey @kozyraki,
thanks for your answer. 

Name consistency is very imporant. 
I mean hostname = hostname and not dynamic names like "slave1.mesos","slave2.mesos",...

```json
{
    "slaves": [
        {
            "hostname": "myhostname3.dev",
            "pid": "slave(1)@10.11.12.13: 5051"
        },
        {
            "hostname": "myhostname2.dev",
            "pid": "slave(1)@10.11.12.12: 5051"
        },
        {
            "hostname": "myhostname1.dev",
            "pid": "slave(1)@10.11.12.11: 5051"
        }
    ]
}
```
myhostname1.dev -> myhostname1.dev.slave.mesos 3600 IN A 10.11.12.11
myhostname2.dev -> myhostname2.dev.slave.mesos 3600 IN A 10.11.12.12
myhostname3.dev -> myhostname3.dev.slave.mesos 3600 IN A 10.11.12.13

To answer your question I need to understand more about what you are doing.  
I will be back again.
Greetings

**Comment by kozyraki** [comment]
@jstabenow If you are responsible for the numbering (and its consistency) than simple. We can take the hostname and translate this to a hostname.domain) entry on Mesos-DNS (where tail is typically mesos)

However, there are still a few minor issues to resolve:
- Mesos-DNS may still have a small difficult with formating the hostname. For instance, what is the hostname on my site is myhostname1.dev.abc.com? Should we use the whole name (myhostname1.dev.abc.com.mesos) or try to trim it? If we try to trim it, how do we know if the ".dev" is part of the hostname or the tail? 
- Not all Mesos installations use a valid hostname on the "hostname" parameter. We have seen quite a few cases where they list an IP address. What do we do in this case? The simplest thing is to skip the creation of the new name altogether. 

Let me know what you think.

**Comment by BenWhitehead** [comment]
:watch:ing

**Comment by jstabenow** [comment]
@kozyraki here is my problem:

![dns-problem](https://cloud.githubusercontent.com/assets/7462030/7671731/ee99acee-fcda-11e4-8e9e-9c4f8c9c5776.png)

The result without extra DNS-Resolvers:
```sh
root@task3:/# ping host1.dev
ping: unknown host host1.dev
````

But with a Mesos-DNS solution, we could do:
host=${HOST}.slave.mesos

To your questions:
I would not modify the hostnames. Mean that a hostname=10.11.12.13, the dns will be
10.11.12.13.slave.mesos

So you can reach the HOST-Enviroment everytime over HOST.slave.mesos. 

What do you think about it?

**Comment by jstabenow** [comment]
Here is an other way to realize the same "workflow", but it's very hard because you have to deal with many many tasks:

You get from /master/state.json:

```json
{
    "tasks": [
        {
            "framework_id": "20150122-094551-1063518218-5050-1327-0000",
            "id": "demo-app.1b276298-fd34-11e4-835c-a268d739d527",
            "slave_id": "20150513-124419-1063518218-5050-1722-S0"
        }
    ],
    "slaves": [
        {
            "id": "20150513-124419-1063518218-5050-1722-S0",
            "pid": "slave(1)@10.11.12.13:5051"
        }
    ]
}
```

So you can create a task-dns-mapping:
* demo-app.1b276298-fd34-11e4-835c-a268d739d527.marathon.mesos, or
* demo-app.1b276298-fd34-11e4-835c-a268d739d527.task.mesos

But it's not so easy because chronos (and other frameworks) use id's like:
* ct:1431937560000:0:my_funny_cron-task:

This needs a formating:
* ct:1431937560000:0:my_funny_cron-task -> ct.1431937560000.0.my_funny_cron-task.

And additionally, the Marathon/Chronos- or the Mesos-Team must add the TaskId to the enviroment-set:
* MESOS_TASKID=demo-app.1b276298-fd34-11e4-835c-a268d739d527

Perhaps a long way to go...

Currently I think the workflow with the HOST-Env is the easiest way to realize it without other dev-teams and a lot of workarounds.

**Comment by jstabenow** [comment]
Hey @kozyraki 
Have you thought about solutions to make "hostnames" or the "mesos-task-id" reachable? Is it possible or is it a problem for other applications or requirements?

**Comment by tsenart** [comment]
Ping @kozyraki.
