### ISSUE TITLE
HTTP API - /v1/hosts return all hosts available

### ISSUE THREAD

**Issue by gomes** [mesosphere/mesos-dns#162]
What about return all available hosts when call /hosts? If it's ok, I can do that and send a PR.

**Comment by kozyraki** [comment]
@gomes At small scale, this is very useful. But at large-scale, it seems like a big security risk (tell me everything you know about all tasks). 

What do others think?

**Comment by tsenart** [comment]
Besides being a security flaw, the HTTP API to the DNS server ought to closely mimic DNS API semantics. Although that's not the case at the moment, I think it's a direction we should move into.
