### ISSUE TITLE
Always have mesos-dns return the full list of masters when querying for masters.mesos

### ISSUE THREAD

**Issue by lloesche** [mesosphere/mesos-dns#166]
Right now Mesos-DNS doesn't know about the masters unless they are explicitly configured in the Mesos-DNS json config. When Zookeeper is being used it only knows about the leader.

For #164 I'd need masters.mesos to always return the full list of Mesos Masters. But also independent of #164 it would be the behaviour I would expect from the System.

**Comment by s-urbaniak** [comment]
Proposal:

Leader changes (by the zookeeper detector or any other pluggable detector) are currently being propagated as callback functions, see https://github.com/mesosphere/mesos-dns/blob/master/resolver/resolver.go#L119.

When a new leader/master is being elected this change is being propagated but the originally configured list of masters is left untouched (even if being invalid/outdated).

The https://godoc.org/github.com/mesos/mesos-go/detector#AllMasters interface exposes the necessary callback to update all masters (not only the leader). It will be invoked if the underlying detector plugin supports such an operation.

If the underlying detector plugin does not support the AllMasters interface the current behaviour will be preserved.

I propose to get rid of callback functions/locks and use channel propagation instead.

**Comment by jdef** [comment]
May be of interest: there's a (way too big) PR in mesos-go that I've been
hacking in. Should probably be split up into smaller PR's for easier review
once it's ready. There's a ton of ZK client refactoring in there:
https://github.com/mesos/mesos-go/pull/159

On Thu, Sep 3, 2015 at 11:13 AM, Sergiusz Urbaniak <notifications@github.com

**Comment by s-urbaniak** [comment]
@jdef Thanks for the pointer!

I am relying solely on the https://godoc.org/github.com/mesos/mesos-go/detector#Master and https://godoc.org/github.com/mesos/mesos-go/detector#AllMasters interfaces for this refactoring.

Quickly scanning through the PR didn't reveal any changes in the interface but I'll have a deeper look tomorrow.

**Comment by jdef** [comment]
Right, that interface shouldn't change. Just the underlying ZK connectivity.
