### ISSUE TITLE
Docker can't parse mesos-dns answers

### ISSUE THREAD

**Issue by jdoklovic** [mesosphere/mesos-dns#170]
When trying to do a docker pull on a machine with mesos-dns running, it fails complaining about not being able to parse the dns message:
```bash
FATA[0004] Get https://registry-1.docker.io/v1/repositories/mesosphere/chronos/tags: dial tcp: lookup registry-1.docker.io on 192.168.33.12:53: cannot unmarshal DNS message
```
seems it might be related to: https://github.com/hashicorp/consul/issues/854

**Comment by kozyraki** [comment]
Thanks for reporting this. We'll start the digging.

**Comment by tsenart** [comment]
It's hard to write a test that reproduces this issue since the stdlib `net.LookupHost` loads the DNS resolvers to use from `/etc/resolv.conf`. I'll continue investigation next week.

**Comment by jdoklovic** [comment]
FYI, the issue only occurs if the mesos-dns ip is the only nameserver listed in resolv.conf.
If I list the mesos-dns first and then list 8.8.8.8 as a second nameserver, it seems to work properly
