### ISSUE TITLE
Improve documentation of install steps

### ISSUE THREAD

**Issue by jdoklovic** [mesosphere/mesos-dns#171]
I have a dv vm build that needs to get and build mesos-dns.
This was working fine up until this morning.
Now when it does:
```bash
go get github.com/mesosphere/mesos-dns
```
I get:
```bash
virtualbox-ovf: failed: [127.0.0.1] => {"changed": true, "cmd": "go get github.com/mesosphere/mesos-dns", "delta": "0:03:02.253808", "end": "2015-06-12 17:55:25.287440", "rc": 2, "start": "2015-06-12 17:52:23.033632", "warnings": []}
    virtualbox-ovf: stderr: # github.com/mesos/mesos-go/mesosproto
    virtualbox-ovf: /home/vagrant/go/src/github.com/mesos/mesos-go/mesosproto/log.pb.go:663: undefined: proto.Skip
    virtualbox-ovf: /home/vagrant/go/src/github.com/mesos/mesos-go/mesosproto/log.pb.go:872: undefined: proto.Skip
    virtualbox-ovf: /home/vagrant/go/src/github.com/mesos/mesos-go/mesosproto/log.pb.go:913: undefined: proto.Skip
    virtualbox-ovf: /home/vagrant/go/src/github.com/mesos/mesos-go/mesosproto/log.pb.go:999: undefined: proto.Skip
    virtualbox-ovf: /home/vagrant/go/src/github.com/mesos/mesos-go/mesosproto/log.pb.go:1058: undefined: proto.Skip
    virtualbox-ovf: /home/vagrant/go/src/github.com/mesos/mesos-go/mesosproto/log.pb.go:1134: undefined: proto.Skip
    virtualbox-ovf: /home/vagrant/go/src/github.com/mesos/mesos-go/mesosproto/log.pb.go:1274: undefined: proto.Skip
    virtualbox-ovf: /home/vagrant/go/src/github.com/mesos/mesos-go/mesosproto/log.pb.go:1350: undefined: proto.Skip
    virtualbox-ovf: /home/vagrant/go/src/github.com/mesos/mesos-go/mesosproto/log.pb.go:1471: undefined: proto.Skip
    virtualbox-ovf: /home/vagrant/go/src/github.com/mesos/mesos-go/mesosproto/log.pb.go:1663: undefined: proto.Skip
    virtualbox-ovf: /home/vagrant/go/src/github.com/mesos/mesos-go/mesosproto/log.pb.go:1663: too many errors
```

How can i fix this??

**Comment by jdef** [comment]
Perhaps you have another project sharing the same GOPATH that uses a different version of the protobuf lib?

**Comment by jdoklovic** [comment]
I think it's a change in mesos-go that mesos-dns isn't consuming....
https://github.com/mesos/mesos-go/commit/dfbab1058414bb7f357a8b9bd2fef516824a0a85

look at the log.pb.go diff... the proto.Skip was changed to proto2.Skip

**Comment by jdoklovic** [comment]
Also, this is a packer/ansible/vagrant build that starts with a blank ubuntu image, so there aren't any other go projects until the mesos-dns role runs.

For clarity, here's my ansible snippet:
```javascript
env:
  GOPATH: /home/vagrant/go
  PATH: /usr/local/go/bin:{{ ansible_env.PATH }}

- name: get go
  shell: curl -L https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz | tar xvz
  args:
    chdir: /usr/local
  sudo: yes
  
- name: make go dir
  shell: mkdir -pv /home/vagrant/go
  sudo: yes
    
- name: install godep
  shell: go get github.com/tools/godep
  environment: env

- name: go symlink
  shell: ln -sv /home/vagrant/go/bin/godep /usr/local/bin/godep
  environment: env
    
- name: get mesos-dns
  shell: go get github.com/mesosphere/mesos-dns
  environment: env
```

**Comment by jdef** [comment]
Thanks for that. Will double-check the deps

**Comment by jdoklovic** [comment]
So I admit, I'm not a go guy, but if I clean out my go dir and then just do the go get github.com/mesosphere/mesos-dns it appears it pulls the latest gogo/protobuf from github even though mesos-go and mesos-dns both list different revisions in their Godeps files.

If I look at either of the revisions that mesos-go or mesos-dns are requesting, I can see that skip_gogo.go exists:  https://github.com/gogo/protobuf/blob/bc946d07d1016848dfd2507f90f0859c9471681e/proto/skip_gogo.go

However, that file does not seem to exist on master: https://github.com/gogo/protobuf/blob/master/proto/skip_gogo.go

Oddly, I can't find a commit that deletes that file

**Comment by jdoklovic** [comment]
Finally, I just went into $GOPATH/src/github.com/gogo/protobuf and did:
```bash
git checkout bc946d07d1016848dfd2507f90f0859c9471681e
go get github.com/mesosphere/mesos-dns
```
and got no errors

**Comment by jdef** [comment]
So `go get` is a great tool for pulling things down quick and dirty. It's not so great when vendored library APIs change.

here's what works:
```shell
$ go get -d github.com/mesosphere/mesos-dns
$ cd src/github.com/mesosphere/mesos-dns/
$ make
```

**Comment by jdoklovic** [comment]
awesome, that works.
I'll let you close this issue if you want, but please note you should update the docs page:
http://mesosphere.github.io/mesos-dns/docs/

**Comment by jdef** [comment]
I've re-tagged this as a docs issue. Thanks for bringing this to our
attention!

**Comment by alon-argus** [comment]
I guess the reason for the failure is this
https://github.com/gogo/protobuf/commit/a719b4f394a5b000b2896a6337a0c2e5a8848f2d
