### ISSUE TITLE
resolv.conf is being override by service gen_resolvconf.timer

### ISSUE THREAD

**Issue by zoharaharoni** [mesosphere/mesos-dns#179]
Hi,
I have a newly installed DCOS cluster on AWS.
I followed the documentation to configure mesos-dns but found out that resolv.conf is always being override by service gen_resolvconf.timer.
I had to stop it so that I'll be able to add mesos-dns nameserver to resolv.conf. I'm not sure if that is the proper solution..
Did I miss something in the configuration?

**Comment by jdef** [comment]
mesos-dns is already installed as part of DCOS. Is there a particular
reason that you're trying to install a 2nd copy?

**Comment by zoharaharoni** [comment]
Oh, I didn't know that :-) I didn't see it in the documentation...
Where is it running?

**Comment by jdef** [comment]
I believe that mesos-dns currently runs on the master nodes in DCOS. That's
probably subject change in the future (I don't think our DCOS
specifications guarantee the location of mesos-dns within the cluster).

Is there something particular that you're trying to accomplish that the
current deployment strategy is blocking you on?

**Comment by zoharaharoni** [comment]
Actually - the current deployment strategy works great for me.
I just wasn't aware that mesos-dns is already running on the master because
the documentation say to install it on the slaves, So I didn't looked there
:-)

Anyway - I restarted the service so that resolv.conf will get the updated
and stopped the mesos-dns app I ran from marathon.

Thanks for the help.

**Comment by jdef** [comment]
OK, glad to hear that it's going to work out.

**Comment by cmaloney** [comment]
The guarantee we give at this point is that all slave tasks will have MesosDNS be their default resolver. Exactly how we do that will likely change in the future (At the moment we use a load balancer between the masters which we send DNS to, then the gen_resolveconf service you see to only add mesos-dns as a resolver after it has managed to connect to zookeeper and determine what the leading mesos master is).

**Comment by zoharaharoni** [comment]
Thanks for the clarification.
After James mentioned that mesos-dns runs on the master by default it was
clear how it works and what is the purpose of the resolvconf service.

Thanks.

-- Zohar
