### ISSUE TITLE
No validation that task name is RFC 952 formatted

### ISSUE THREAD

**Issue by dsinyakov** [mesosphere/mesos-dns#181]
It is possible to submit task with name containing special characters like "-". It will appear in marathon and will execute just fine. 
Mesos-DNS query: 
```
 /v1/services/<task name>._tcp.marathon.mesos
``` 
will return empty response.

The expected behavior would be to return an error stating the task name is not compliant with RFC 952 formatting.

**Comment by sttts** [comment]
mesos-dns will escape non-compliant task names. If I understand your expected behavior correctly, this issue should be about marathon, shouldn't it?

**Comment by dsinyakov** [comment]
@sttts Correct. In a slack chat we agreed that this should be added to DCOS version of marathon. Mesos team promised to file a bug to internal Jira regarding this.

**Comment by sttts** [comment]
Also note https://github.com/mesosphere/mesos-dns/pull/177. The compliant names are now rfc1123.
