### ISSUE TITLE
DNS request for container running on same host as mesos-dns returns 127.0.0.1

### ISSUE THREAD

**Issue by hanwang** [mesosphere/mesos-dns#182]
Currently, I'm running a docker-registry and mesos-dns on the same cluster. Marathon ended up assigning docker registry to the same physical machine as mesos-dns. Now when any external machine tries to resolve dockerreg.marathon.mesos, the record is returned as 127.0.0.1. Is this the intended behaviour for containers which share the host of mesos-dns?

**Comment by lloesche** [comment]
@hanwang what are the `--ip` and `--hostname` settings for mesos-slave (I'd also define them explicit for mesos-master)? Mesos DNS takes the IP it finds in mesos-master's `:5050/state.json` and creates the records from that. If the slave is running on the same machine as the master and uses the loopback IP to connect to it that would result in Mesos DNS seeing the loopback IP.

**Comment by tsenart** [comment]
@hanwang: Ping.

**Comment by hanwang** [comment]
I will pull the log from the server and post it here, but the ip was set to eth0 in /etc/mesos-slave/ip explicitly so I would be surprised if it defaulted to local loopback for communication.

**Comment by tsenart** [comment]
Please re-open if its still an issue.
