### ISSUE TITLE
Make upstream resolvers optional

### ISSUE THREAD

**Issue by cmaloney** [mesosphere/mesos-dns#187]
There are some environments we're shipping to which don't have upstream DNS.

**Comment by sargun** [comment]
@cmaloney Is this any different than setting "ExternalOn" to false? Although, internally, it'll maintain a DNS server list, it shouldn't get used.

**Comment by cmaloney** [comment]
In my configuration currently I either have to set `"resolvers": ["list", "of", "resolvers"]"` or `"externalOn": false"`, which generally works. Why doesn't a list of empty resolvers just imply `externalOn` is false though? Why do I need these two different settings?

**Comment by sargun** [comment]
The current behaviour is that if you omit resolvers from the configuration, it falls back to `8.8.8.8`. An empty list of resolvers currently pulls resolvers from the system resolver list. These are two defined behaviours. Would you like to propose an option so we users can intuitively configure their instances to use the system resolver list, or just the built-in defaults? 

Either way, if we're changing the way the configuration works, we're going to have to go through a few cycles to deprecate it.

**Comment by cmaloney** [comment]
The current behavior works, so I wouldn't focus on it for now. Picking up system resolvers I think could be dangerous (In our case, some point to instances of Mesos-DNS, some point to whatever a customer's upstream DNS servers are). Falling back to Google DNS isn't a really obvious behavior (I'd almost rather have it be a mandatory parameter you have to set at startup), but that is all personal design nits.
