### ISSUE TITLE
Question on using mesos-dns when not binding host port

### ISSUE THREAD

**Issue by pdzilla** [mesosphere/mesos-dns#189]
Thanks for the readthrough of this.
I'm tinkering with mesos-dns and just have a question regarding technique and looking for some advice.

For this example, I'm using a multi-instance app launched by POSTing to Marathon.  Here's the relevant part of a json descriptor:
``` json
{
	"container": {
    "type": "DOCKER",
    "docker": {
      "image": "pdzilla/activemq:5.8.0",
      "network": "BRIDGE",
      "privileged": false,
      "portMappings": [
        {
          "containerPort": 8161,
          "hostPort": 0,
          "servicePort": 8161,
          "protocol": "tcp"
        },
        {
          "containerPort": 61616,
          "hostPort": 0,
          "servicePort": 61616,
          "protocol": "tcp"
        }
      ]
    }
  },
  "id": "amq",
...
```

Nevermind that it's activemq :smile: any app with a similar configuration would beg the same question from me.

if I then issue an `nslookup amq.marathon.mesos` against the nameserver running mesos-dns, I see the records -- it returns the IP of the host running each instance.

Like it shows above, I'm not binding the host port when these instances launch; I don't want to do host port binding unless it's otherwise unavoidable. If there's another app in the Mesos cluster that looks for these services by their psuedo-fqdn `app-name.marathon.mesos` and tries to hit the container port, naturally it'll fail.  I admit to being new with mesos-dns, but am I missing something that's blatantly obvious?  Without doing host port binding, can I use mesos-dns for discovery?

Because I'm running haproxy, I'm working around what I don't currently understand by just having the other app reference this service via haproxy for now; but I'd rather use mesos-dns if I'm able.

I'm somewhat convinced that mesos-dns is working properly (I can be un-convinced quite easily).  Nonetheless, I'm including here the config:

``` json
{
  "zk": "zk://a.b.c.d:2181/mesos",
  "masters": ["a.b.c.d:5050", "a.b.c.e:5050", "a.b.c.f:5050"],
  "refreshSeconds": 60,
  "ttl": 60,
  "domain": "mesos",
  "port": 53,
  "resolvers": ["b.b.c.d", "b.b.c.e"],
  "timeout": 5,
  "httpon": true,
  "dsnon": true,
  "httpport": 8123,
  "externalon": true,
  "listener": "0.0.0.0",
  "SOAMname": "root.ns1.mesos",
  "SOARname": "ns1.mesos",
  "SOARefresh": 60,
  "SOARetry":   600,
  "SOAExpire":  86400,
  "SOAMinttl": 60
}
```

**Comment by sttts** [comment]
Early support for container IPs was merged into Mesos and mesos-dns just yesterday: compare https://reviews.apache.org/r/36585/ and https://github.com/mesosphere/mesos-dns/pull/183. With that you will be able to use `_container.amq.marathon.mesos` to get the IP of the container.

**Comment by pdzilla** [comment]
@sttts looks like exactly what I am after; thanks for the timely response.

**Comment by pdzilla** [comment]
@sttts based on the limited reading I did on these, it looks like I should expect an A record matching `_container.amq.marathon.mesos` after updating mesos-dns to the latest on `master`.  Perhaps I'm missing something, but I just don't see it behaving that way.  Based on the below, have I missed something?  Thanks again for the attention.

Happy to share some info; if I'm missing something I'd be glad to make a change.
Here is some information that hopefully helps:

``` bash
# curl http://slave:8123/v1/version
{"Service":"Mesos-DNS","URL":"https://github.com/mesosphere/mesos-dns","Version":"0.1.2"}

# curl http://slave:8123/v1/config
{"Masters":["1:5050","2:5050","3:5050"],"Zk":"zk://1:2181/mesos","RefreshSeconds":60,"TTL":60,"Port":53,"Domain":"mesos","Resolvers":["a","b"],"Timeout":5,"File":"/usr/local/mesos-dns/mesos-dns-config.json","SOAMname":"root.ns1.mesos.","SOARname":"ns1.mesos.","SOASerial":1437581327,"SOARefresh":60,"SOARetry":600,"SOAExpire":86400,"SOAMinttl":60,"RecurseOn":true,"Listener":"0.0.0.0","HttpPort":8123,"DnsOn":true,"HttpOn":true,"ExternalOn":true,"EnforceRFC952":false}

# curl http://slave:8123/v1/hosts/amq.marathon.mesos
[{"host":"amq.marathon.mesos.","ip":"another-slave"}]

# curl http://slave:8123/v1/hosts/_container.amq.marathon.mesos
[{"host":"","ip":""}]

# dig amq.marathon.mesos

; <<>> DiG 9.9.4-RedHat-9.9.4-18.el7_1.1 <<>> amq.marathon.mesos
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45193
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;amq.marathon.mesos.		IN	A

;; ANSWER SECTION:
amq.marathon.mesos.	60	IN	A	another-slave


# dig _container.amq.marathon.mesos

; <<>> DiG 9.9.4-RedHat-9.9.4-18.el7_1.1 <<>> _container.amq.marathon.mesos
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 43150
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;_container.amq.marathon.mesos.	IN	A

;; AUTHORITY SECTION:
_container.amq.marathon.mesos. 60 IN	SOA	ns1.mesos. root.ns1.mesos. 1437584809 60 600 86400 60

;; Query time: 1 msec
;; SERVER: slave#53(slave)
;; WHEN: Wed Jul 22 17:07:21 UTC 2015
;; MSG SIZE  rcvd: 92
```

**Comment by sttts** [comment]
Do you have Mesos from the master branch? The patch was only merged yesterday. I guess it will be part of Mesos 0.23 when it is released officially.

**Comment by pdzilla** [comment]
That was my first suspicion add well, I looked at the source from the merge and diffed against what I fetched with `go get`; the changed files seem to match.

I'll try to just clone the repo and build from that. Thanks again

________________________________

On July 22, 2015 11:12:31 AM "Dr. Stefan Schimanski" <notifications@github.com> wrote:

Do you have Mesos from the master branch? The patch was only merged yesterday. I guess it will be part of Mesos 0.23 when it is released officially.

-

**Comment by sttts** [comment]
No, I meant Mesos, not mesos-dns. Mesos needs to supply the container IP to mesos-dns. Without a Mesos binary from the master branch, mesos-dns cannot know about them.

**Comment by pdzilla** [comment]
:bulb: Thanks; I am on 0.22.1, will pull the latest Mesos and go from there.
