### ISSUE TITLE
How to read port of a containerized task through mesos-dns

### ISSUE THREAD

**Issue by ee1200231** [mesosphere/mesos-dns#190]
I post my containerized web application through json file to marathon. Now, this app needs to communicate with a mysql container running as a marathon task. So, i pass "mysqlserver.marathon.mesos" as an env variable. This does resolve the IP of the host on which mysqlserver is running. But how do i get the port exposed by that host? Mysqlserver is not fixed to run on 3306 since it is containerized.

**Comment by sttts** [comment]
There are several solutions for this:
* You get and parse the SRV record of your mysqlserver host, compare 

    https://mesosphere.github.io/mesos-dns/docs/naming.html. 

* You use the mesos-dns HTTP interface: https://mesosphere.github.io/mesos-dns/docs/http.html
* You use the Marathon haproxy service bridge: https://mesosphere.github.io/marathon/docs/service-discovery-load-balancing.html. This will allow you to define static service ports in Marathon (e.g. 3306) and you don't have to care about port management anymore.

**Comment by ee1200231** [comment]
I understand the first two approaches. These commands work on my terminal. If i use "myservice.marathon.mesos" in my json, it does retrieve the IP of the host on which "myservice" is running. How do I get the port? For parsing, does something exist? Or would I have to implement that on my own?

Given the use case of Mesos-DNS, I think something must exist.

I dont want to use static port as that would create a dependency on the host. In case, the port is not free on any of my nodes, marathon wont launch it anywhere and leave it in deployment mode.

**Comment by kozyraki** [comment]
Rishabh, 

For now, yes, you would have to parse on your own the SRV reply or the HTTP reply. It is literally 5 fields per entry so it should be easy enough to do it in your favorite language. 
Longer term, we are working on supporting IP per container in Mesos. Which will allow you to use the std port without any dependencies on the host. 

Christos

**Comment by ee1200231** [comment]
All right. Thank you for the help. :)

Btw, the longer term plan sounds amazing!
