### ISSUE TITLE
True round-robin load balancing

### ISSUE THREAD

**Issue by sybrandy** [mesosphere/mesos-dns#194]
Hello,

We have a use case where we have two nodes we want to load balance between.  The problem is that the current shuffle algorithm heavily favors one node over the other.  Would it be possible to provide a simpler round-robin algorithm for load balancing?  Instead of shuffling, perhaps take the first element and make it the last element each time a request was made?

**Comment by sybrandy** [comment]
Closing as this apparently was premature.  It looks like the client code had, by default, keep-alive on so the connection was being reused instead of being load balanced.  I would still be interested in knowing why you went the randomization route for load balancing.

**Comment by jdef** [comment]
Randomized balancing is:
(a) simpler; no state to track
(b) clients aren't tempted to depend on some pseudo-deterministic balance
order; leaves us free to change the underlying impl in the future without
breaking clients
