### ISSUE TITLE
Resolve schedulers as well as tasks.

### ISSUE THREAD

**Issue by pyronicide** [mesosphere/mesos-dns#202]
I would like to resolve where my scheduler is running. `ping marathon.mesos` should return the IP of the scheduler that is connected to mesos.

**Comment by jdef** [comment]
we parse a framework's PID from state.json to create an A record from the IP address listed there. would that suffice?

what's the urgency of this?

**Comment by pyronicide** [comment]
There isn't a massive urgency. It is more something that I expected to work
and it didn't. Getting the PID from state.json and making an A record out
of it would do exactly what I was expecting.
