### ISSUE TITLE
Massive amount of unintelligible log lines

### ISSUE THREAD

**Issue by pyronicide** [mesosphere/mesos-dns#206]
My logs are being flooded by lines like this:

```
1.1.1.1.in-addr.arpa
nil msg
```

Why is this and what can I do about it?

**Comment by kozyraki** [comment]
Seems like a reverse 1.1.1.1. We do not support PTR records at the moment (and it’s not clear that there is good motivation).

**Comment by sttts** [comment]
Do you have defined external resolvers? If see this happening if there are no external resolvers, but externalOn is true.

**Comment by pyronicide** [comment]
There is an external resolver, but I don't think it is reachable.

**Comment by sttts** [comment]
If you disable externalOn, the messages should go away.

**Comment by pyronicide** [comment]
@kozyraki This is more that there are some odd log lines that don't make any sense than a specific feature. I've seen totally valid domain lookups there as well as they flew by.

It sounds like @sttts has a solution, but it doesn't fix the core problem. Can we make the message have a little more meaning? I couldn't even figure out what was going on by looking at the code.

**Comment by kozyraki** [comment]
> @kozyraki <https://github.com/kozyraki> This is more that there are some odd log lines that don't make any sense than a specific feature. I've seen totally valid domain lookups there as well as they flew by.
> 
> 

Yes, I am pretty sure that there is a line that logs all failed DNS lookups. It should be selected only by very very verbose (-v=2).
Unfortunately, there seems to be something in your apps that generates reserve lookups for 1.1.1.1 (which actually fails anyway) in a massive manner. 
> It sounds like @sttts <https://github.com/sttts> has a solution, but it doesn't fix the core problem. Can we make the message have a little more meaning? I couldn't even figure out what was going on by looking at the code.
> 
> 

I think we should preserve these messages, but push the to a deeper logging level (-v=3 or beyond).

**Comment by pyronicide** [comment]
@kozyraki I agree, the messages should be preserved (I don't even mind leaving them at the current log level). What I would like is something closer to `failed DNS lookup externally: X` instead of `nil msg`.
