### ISSUE TITLE
Tune errcheck CI settings to ignore `defer Close()` on RO objects

### ISSUE THREAD

**Issue by tsenart** [mesosphere/mesos-dns#223]
> Yes, and we should totally use defer whenever we can use it. It's my fault I didn't explain this change well enough. So, here's the deal: One of the linters in our CI is `errcheck` which detects ignored errors in Go programs. Unfortunately, it creates tension with the common `defer r.Close()` Go idiom. Now, errors returned by `Close` methods can be safely ignored *as long as* what was closed was read-only. Whenever there are writes involved, errors returned by close should absolutely not be ignored.

> What is lacking, then, is the appropriate tooling to handle such intricacies intelligently. In this PR, I did the easiest thing that would silence the CI failure, but I knew that it wasn't the right thing to do. I will follow up

**Comment by sargun** [comment]
I think being explicit about this, and using the new `util.IgnoreError`, e.g. `defer util.IgnoreError(r.Close())` versus blindly ignoring these, to the linter accidentally dropping errors.

**Comment by tsenart** [comment]
I dread any package called `util`. It ends up sucking up all matter from the known universe. I like the idea of making it explicit, but let's create a package called `errors` and have `defer errors.Ignore(r.Close)`

**Comment by sargun** [comment]
@tsenart Isn't there already a std golang package named errors? I wouldn't want to have to import that as another name to avoid the conflict. Any other name suggestions?

**Comment by jdef** [comment]
yes there is a stdlib package called errors but that shouldn't preclude us
from using the same name if it makes sense.

**Comment by sargun** [comment]
@jdef errors is imported, and used in generator.go, which also uses this util func. I'd say, if we know there's going to be an import name collision from day 1, let's try to avoid that.

**Comment by jdef** [comment]
I'd be fine with an `errorutil` package

**Comment by sargun** [comment]
@jdef :+1:

**Comment by tsenart** [comment]
`errutil`

**Comment by sargun** [comment]
See: https://github.com/mesosphere/mesos-dns/pull/352
