### ISSUE TITLE
Change in Mesos leader info in ZK may break Mesos-DNS

### ISSUE THREAD

**Issue by kozyraki** [mesosphere/mesos-dns#228]
Mesos 0.24 will follow this convention for the leading master info in ZK: https://github.com/mesos/commons/blob/master/docs/leader_discovery.rst
https://issues.apache.org/jira/browse/MESOS-2340
This will break existing Mesos-DNS code which assumes the old protobuf. 

We need to update the code to handle correctly both 0.24 and older versions :(

**Comment by tsenart** [comment]
@kozyraki: As long as they maintain deprecated fields in the Protobufs for backwards compatibility (even if the data isn't filled), addressing this should be pretty easy. It'll be a great opportunity to properly encapsulate the master detection code behind a well defined API that hides these implementation and compatibility constraints.

**Comment by cmaloney** [comment]
This is currently preventing using Mesos 0.24 in DCOS. Needs to be fixed ASAP

**Comment by jdef** [comment]
I've started hacking on a patch in mesos-go

**Comment by jdef** [comment]
xref https://github.com/mesos/mesos-go/pull/174

**Comment by tsenart** [comment]
@cmaloney: Would you please provide us with a more detailed timeline than *ASAP*?

**Comment by cmaloney** [comment]
It is going to delay multiple projects and likely make them miss their schedules if it is more than a couple business days out.

**Comment by tsenart** [comment]
@cmaloney: Thanks.

**Comment by tsenart** [comment]
Fixed by https://github.com/mesos/mesos-go/pull/174

**Comment by jdef** [comment]
mesos-go/zk detection has been updated to support the JSON MasterInfo blob, need to incorporate updated Godeps into this project to pull the latest changes from mesos-go

**Comment by F21** [comment]
Ran into the problem while trying to use mesos-dns with mesos 0.24 today. Hope this gets merged soon!
