### ISSUE TITLE
Allow fallback DNS to be configured in Mesos-DNS

### ISSUE THREAD

**Issue by jgarcia-mesosphere** [mesosphere/mesos-dns#235]
Currently, it does not appear that you can add more than one fallback DNS entry. Additionally, we are not even able to manually add DNS entries to the Mesosphere servers as there is a Python job that continually syncs resolv.conf with the values provided in the Cloudformation template.

We'd like the option of configuring multiple failover DNS addresses in the CloudFormation template.

**Comment by cmaloney** [comment]
This is a configuration thing with DCOS, not mesos-dns, closing and moving the discussion.
