### ISSUE TITLE
Mesos-dns container shows: no master

### ISSUE THREAD

**Issue by n3rV3** [mesosphere/mesos-dns#238]
I am running a mesos cluster on AWS and when I run a Mesos-DNS container. Its logs show:
<code>ERROR: 2015/09/01 08:09:31 generator.go:148: Get http://102.0.0.10:5050/master/state.json: dial tcp 102.0.0.10:5050: i/o timeout
ERROR: 2015/09/01 08:09:31 generator.go:74: no master
ERROR: 2015/09/01 08:11:01 generator.go:148: Get http://102.0.0.10:5050/master/state.json: dial tcp 102.0.0.10:5050: i/o timeout
ERROR: 2015/09/01 08:11:01 generator.go:74: no master
ERROR: 2015/09/01 08:12:31 generator.go:148: Get http://102.0.0.10:5050/master/state.json: dial tcp 102.0.0.10:5050: i/o timeout
ERROR: 2015/09/01 08:12:31 generator.go:74: no master
</code>

The IPs here are reversed from the actual ones, i.e., 102.0.0.10 should be 10.0.0.102.
And the correct URI shows status:
<code>
{"activated_slaves":3,"build_date":"2015-05-05 06:16:35","build_time":1430806595,"build_user":"root","cluster":"test-cfn-aether","completed_frameworks":[],"deactivated_slaves":0,"elected_time":1441080651.94144,"failed_tasks":0,"finished_tasks":0,"flags":{"allocation_interval":"1secs","authenticate":"false","authenticate_slaves":"false","authenticators":"crammd5","cluster":"test-cfn-aether","framework_sorter":"drf","help":"false","hostname":"","initialize_driver_logging":"true","log_auto_initialize":"true","log_dir":"\/var\/log\/mesos","logbufsecs":"0","logging_level":"INFO","port":"5050","quiet":"false","quorum":"2","recovery_slave_removal_limit":"100%","registry":"replicated_log","registry_fetch_timeout":"1mins","registry_store_timeout":"5secs","registry_strict":"false","root_submissions":"true","slave_reregister_timeout":"10mins","user_sorter":"drf","version":"false","webui_dir":"\/usr\/share\/mesos\/webui","work_dir":"\/var\/lib\/mesos","zk":"zk:\/\/10.0.0.100:2181,10.0.0.101:2181,10.0.0.102:2181\/mesos","zk_session_timeout":"10secs"},"frameworks":[{"active":true,"checkpoint":true,"completed_tasks":[],"failover_timeout":604800,"hostname":"ip-10-0-0-100.us-west-2.compute.internal","id":"20150901-040706-1694498826-5050-2039-0000","name":"marathon","offered_resources":{"cpus":0,"disk":0,"mem":0},"offers":[],"registered_time":1441080655.37587,"reregistered_time":1441080655.37588,"resources":{"cpus":0,"disk":0,"mem":0},"role":"*","tasks":[],"unregistered_time":0,"used_resources":{"cpus":0,"disk":0,"mem":0},"user":"root","webui_url":"http:\/\/ip-10-0-0-100:8080"},{"active":true,"checkpoint":true,"completed_tasks":[],"failover_timeout":604800,"hostname":"ip-10-0-0-100","id":"20150901-040706-1694498826-5050-2039-0001","name":"chronos-2.4.0-RC1","offered_resources":{"cpus":0,"disk":0,"mem":0},"offers":[],"registered_time":1441080653.87233,"reregistered_time":1441081060.15099,"resources":{"cpus":0,"disk":0,"mem":0},"role":"*","tasks":[],"unregistered_time":0,"used_resources":{"cpus":0,"disk":0,"mem":0},"user":"root","webui_url":"http:\/\/ec2-52-88-34-48.us-west-2.compute.amazonaws.com:4400"}],"git_sha":"d6309f92a7f9af3ab61a878403e3d9c284ea87e0","git_tag":"0.22.1","hostname":"","id":"20150901-040828-1711276042-5050-2204","killed_tasks":0,"leader":"master@10.0.0.102:5050","log_dir":"\/var\/log\/mesos","lost_tasks":0,"orphan_tasks":[],"pid":"master@10.0.0.102:5050","slaves":[{"active":true,"attributes":{},"hostname":"ec2-52-11-31-29.us-west-2.compute.amazonaws.com","id":"20150901-040828-1711276042-5050-2204-S0","pid":"slave(1)@10.0.0.190:5051","registered_time":1441080659.14983,"resources":{"cpus":1,"disk":4090,"mem":496,"ports":"[31000-32000]"}},{"active":true,"attributes":{},"hostname":"ec2-52-27-53-140.us-west-2.compute.amazonaws.com","id":"20150901-040706-1694498826-5050-2039-S0","pid":"slave(1)@10.0.0.189:5051","registered_time":1441080659.14824,"reregistered_time":1441080659.14825,"resources":{"cpus":1,"disk":4090,"mem":496,"ports":"[31000-32000]"}},{"active":true,"attributes":{},"hostname":"ec2-52-27-42-163.us-west-2.compute.amazonaws.com","id":"20150901-040706-1694498826-5050-2039-S1","pid":"slave(1)@10.0.0.188:5051","registered_time":1441080656.25057,"reregistered_time":1441080656.25059,"resources":{"cpus":1,"disk":4090,"mem":496,"ports":"[31000-32000]"}}],"staged_tasks":0,"start_time":1441080508.7509,"started_tasks":0,"unregistered_frameworks":[],"version":"0.22.1"}
</code>
 Zookeeper and Mesos-Master show the status of servers as usual.

**Comment by n3rV3** [comment]
Hostname difference in /etc/hosts and Mesos caused this. Closing the issue.

**Comment by tsenart** [comment]
@n3rV3: Would you please give more details to what cause your issue?

**Comment by n3rV3** [comment]
@tsenart: I had instance hostname's set as their public dns names in AWS. But, I wasn't setting /etc/mesos-*/hostname to this and Mesos was picking up the internal DNS name. This was causing the errors in Mesos-DNS. I fixed the hostnames everywhere to public dns names and everything started working.
