### ISSUE TITLE
Use IPs to connect to mesos masters

### ISSUE THREAD

**Issue by discordianfish** [mesosphere/mesos-dns#244]
A mesos master host's hostname doesn't necessarily resolve to the IP mesos is listening on. Since we have the IP mesos registers itself in ZK with, we should use that instead.

**Comment by discordianfish** [comment]
It appears this issue isn't as straight forward as I hoped, see same discussion for kubernetes: https://github.com/kubernetes/kubernetes/pull/13730

**Comment by karlkfi** [comment]
Mesos announces its "hostname", which is often configured with `--hostname` to be a FQDN or an IP. So we have to prefer it over the `--ip` which is used for binding/listening and may not be externally exposed.

**Comment by discordianfish** [comment]
@karlkfi Got it, I didn't expect it and consider that bad design. But that needs to be discussed somewhere else.
