### ISSUE TITLE
A record for mesos agent

### ISSUE THREAD

**Issue by sepiroth887** [mesosphere/mesos-dns#249]
Would it be possible to add A records for all registered mesos agents? The hostname should be known right?

**Comment by jdef** [comment]
slave.mesos is an A record that should return IPs for slaves. is this what
you're looking for?

**Comment by sepiroth887** [comment]
Oh neat its close enough i guess once i enable the http endpoint it should be possible to list them right? 

What i was thinking is to have each agent assigned an A record based on its hostname (as sent to the master) like: hostA.mesos or 192-132-1-1.mesos if hostname is an ip. 

The reason id like to have this is to drive monitoring via dns discovery.

**Comment by sepiroth887** [comment]
Though i just realized that without zone transfers this wont work anyways. I go wih http endpoint for now. Thanks !!
