### ISSUE TITLE
Research answer ordering semantics defined in DNS RFCs

### ISSUE THREAD

**Issue by tsenart** [mesosphere/mesos-dns#254]

**Comment by sargun** [comment]
DNS does not guarantee ordering. It is up to us to decide, see, [RFC1794, section 4](https://tools.ietf.org/html/rfc1794). It's also the way that most of the internet works, see [Round Robin DNS](https://en.wikipedia.org/wiki/Round-robin_DNS) from Wikipedia.

**Comment by tsenart** [comment]
What about SRV records?

**Comment by sargun** [comment]
Reading between the lines in [RFC2782](https://www.ietf.org/rfc/rfc2782.txt), it seems like the client is responsible for reordering results. 

> In the absence of a protocol whose specification calls for the
> use of other weighting information, **a client** arranges the SRV
> RRs of the same Priority in the order in which target hosts,
> specified by the SRV RRs, will be contacted. [emphasis added].

So, DNS in general doesn't guarantee ordering. SRV records themselves have "order" defined not by ordering in the packet, but rather sorted by priority, and weight order.

**Comment by tsenart** [comment]
Makes sense, it's the client responsibility then.
