### ISSUE TITLE
Update documentation to reflect our new release mechanism

### ISSUE THREAD

**Issue by tsenart** [mesosphere/mesos-dns#264]
Users of this project are to download and install mesos-dns via Github releases instead of building from source.

**Comment by jdef** [comment]
s/are to download/are encouraged to download/

**Comment by tsenart** [comment]
@jdef: The point being we'll have a *single*, official, supported distribution and installation method. That'll be Github release artifacts, not source builds.

**Comment by jdef** [comment]
understood
