### ISSUE TITLE
Error (Current not implemented on linux/amd64)

### ISSUE THREAD

**Issue by rafaelcapucho** [mesosphere/mesos-dns#275]
Hello,

I downloaded the correct version [1] but when I run I got strange errors.

[1] - https://github.com/mesosphere/mesos-dns/releases/download/v0.2.0/mesos-dns-v0.2.0-linux-amd64.tgz

For config.json:
```
{
  "zk": "zk://173.255.192.122:2181/mesos",
  "masters": ["173.255.192.122:5050"],
  "refreshSeconds": 30,
  "ttl": 60,
  "domain": "mesos",
  "port": 53,
  "resolvers": ["8.8.8.8"],
  "timeout": 10
}
```
I got (with mesos-dns moved to /usr/local/bin and running with user root):
```
sudo mesos-dns --config=/root/mesos-dns/config.json
ERROR: 2015/09/23 01:16:55 config.go:185: Failed to determine current user, translating ~/ to ./, error was user: Current not implemented on linux/amd64
```
Linux li202-122 4.1.5-x86_64-linode61 #7 SMP Mon Aug 24 13:46:31 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 14.04.1 LTS

Thank you

**Comment by jdef** [comment]
thanks for reporting this. i wonder if this has to do with the platform
that the binaries were cross-compiled on. i have no such problem with
binaries compiled on my linux system.

**Comment by tsenart** [comment]
Ref: https://github.com/golang/go/issues/6376
