### ISSUE TITLE
external resolver timeout

### ISSUE THREAD

**Issue by crucidal** [mesosphere/mesos-dns#281]
I'm only getting timeouts when I try to use external resolvers. (tested firewall etc. manually it all works).

> ERROR: 2015/09/23 15:09:45 exchanger.go:64: error exchanging with "xxx.xxx.xxx:53": dial udp: i/o >timeout
>ERROR: 2015/09/23 15:09:45 resolver.go:280: example.com.
>ERROR: 2015/09/23 15:09:45 resolver.go:281: failed external DNS lookup of "example.com": dial udp: > i/o timeout

a quick search in the repo shows no declaration of Duration (and as far as I can tell it's not a constant).
Could this be the cause? Hopefully you can resolve it a.s.a.p

We're almost ready to use this in two of our clusters :-)

**Comment by tsenart** [comment]
Please see the `timeout` configuration field documentation: https://mesosphere.github.io/mesos-dns/docs/configuration-parameters.html

Not using `time.Duration` for these is non-idiomatic technical debt.

**Comment by crucidal** [comment]
thanks for the prompt response tsenart. The messages are 'spammed' into the logs 4 to 5 times per second. That's why I was in doubt whether `time.Duration` was defined or not.
In my setup `timeout` is set to 5 seconds.

**Comment by crucidal** [comment]
Apologies. The cause of the issue turns out not to be a bug but to be a problem between the seat of my chair and my keyboard :-)

I altered the resolv.conf files on the machines that were running mesos-dns in such a way that the only nameservers listed were slaves running mesos-dns. though <a href=http://mesosphere.github.io/mesos-dns/docs/configuration-parameters.html>documentation</a> states that 
>We recommend that you list the nameservers specified in the /etc/resolv.conf on the server Mesos-DNS is running. Alternatively, you can list 8.8.8.8, which is the Google public DNS address. The resolvers field is required. 

It seems like the machines who're running mesos-dns cannot profit from the service themselves...
Where can I ask questions/learn more about this? (issues don't seem like the right place)

**Comment by tsenart** [comment]
@crucidal: No problem :) Check https://github.com/mesosphere/mesos-dns#contact for our mailing list.
