### ISSUE TITLE
Proposal: Enumeration

### ISSUE THREAD

**Issue by tsenart** [mesosphere/mesos-dns#294]
In order to enable humans or machines to discover available services (not service endpoints), we should support enumeration in DNS (via PTR records) and HTTP.

**Comment by tony-kerz** [comment]
+1

**Comment by errordeveloper** [comment]
It'd be great to have a public API for this, however I wonder if there's a low-level way to obtain all records?

**Comment by jdef** [comment]
Enumeration is supported via HTTP: https://github.com/mesosphere/mesos-dns/blob/master/docs/docs/http.md#get-v1enumerate
