### ISSUE TITLE
mesos-dns server is not responding properly to zone NS request (ERROR: mesos-dns.... resolver.go:393: NS request

### ISSUE THREAD

**Issue by cruizpollino** [mesosphere/mesos-dns#295]
Good morning everyone

We've installed and configured mesos-dns on server named compute1.mad.roche.com, to act as DNS server for some services running on top of marathon/mesos ecosystem

**cat config.json**
{
  "zk": "zk://centostest61.mad.roche.com:2181,centostest71.mad.roche.com:2181,centostest85.mad.roche.com:2181/mesos",
  "refreshSeconds": 60,
  "ttl": 60,
  "domain": "prhpc.roche.com",
  "port": 53,
  "timeout": 5,
  "email": "root.prhpc.roche.com",
  "httpon": true,
  "dnson": true,
  "httpport": 8123,
  "externalon": false,
  "listener": "10.120.39.154",
  "SOAMname": "root.ns1.prhpc.roche.com",
  "SOARname": "ns1.prhpc.roche.com",
  "SOARefresh": 60,
  "SOARetry":   600,
  "SOAExpire":  86400,
  "SOAMinttl": 60
}

mesos-dns is answering properly to requests related with services running on mesos

But when we run 
* dig @compute1.mad.roche.com prhpc.roche.com NS

We got 
**# dig @compute1.mad.roche.com prhpc.roche.com NS**

; <<>> DiG 9.9.4-RedHat-9.9.4-18.el7 <<>> @compute1.mad.roche.com prhpc.roche.com NS
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41391
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;prhpc.roche.com.               IN      NS

;; AUTHORITY SECTION:
prhpc.roche.com.        60      IN      NS      root.ns1.prhpc.roche.com.

;; Query time: 0 msec
;; SERVER: 10.120.39.154#53(10.120.39.154)
;; WHEN: Thu Oct 01 23:15:30 PDT 2015
;; MSG SIZE  rcvd: 56

**And in mesos-dns log we got**
*ERROR: 2015/10/02 08:15:20 resolver.go:393: NS request

I've tried setting the parameter SOARName to compute1.mad.roche.com, but behavior remains identical

I've read the thread https://github.com/mesosphere/mesos-dns/issues/73, and it looks like this behavior shall be addressed already.

Could any of you guys please help me set the NS resolution properly or confirm me if this behavior is expected one?

Kind Regards

**Comment by tsenart** [comment]
Hello there!

Thanks for reporting. Once #296 is merged I'll cut a release which you'll be able to download. You'll have to switch around the values of `SOARname` and `SOAMname` in your config.

PS: Would you mind to follow the guidelines for filing and issue next time? https://github.com/mesosphere/mesos-dns/blob/master/CONTRIBUTING.md#issues

**Comment by cruizpollino** [comment]
sure i will follow the guidelines. sorry it was my first time in this portal

thanks for quick answer

regards


El 2/10/2015, a las 19:05, Tomás Senart <notifications@github.com> escribió:

Hello there!

Thanks for reporting. Once #296
<https://github.com/mesosphere/mesos-dns/pull/296> is merged I'll cut a
release which you'll be able to download. You'll have to switch around the
values of SOARname and SOAMname in your config.

PS: Would you mind to follow the guidelines for filing and issue next time?
https://github.com/mesosphere/mesos-dns/blob/master/CONTRIBUTING.md#issues

—
Reply to this email directly or view it on GitHub
<https://github.com/mesosphere/mesos-dns/issues/295#issuecomment-145087205>.
