### ISSUE TITLE
Research and possibly remove recursion logic from external resolver (forwarder)

### ISSUE THREAD

**Issue by tsenart** [mesosphere/mesos-dns#301]
Talking to @discordianfish brought some light to the weird practice that we're undertaking here. Usually a DNS server won't be both a forwarder and a unorthodox recurser. I'll have to do some code archeology to understand the rationale behind this.

**Comment by tsenart** [comment]
Ref: https://github.com/mesosphere/mesos-dns/issues/302

**Comment by tsenart** [comment]
Read this: https://tools.ietf.org/html/rfc5625

**Comment by tsenart** [comment]
It turns out that this logic came from the first commit in the repo, so no real explanation.

**Comment by discordianfish** [comment]
To sum up what I said: mesos-dns should be an authoritative nameserver for .mesos and it should simply forward queries for all other zones to a recursive resolving nameserver (aka something like 8.8.8.8 or everything that end up in resolv.conf). It shouldn't do any other logic beside forwarding, similar to the bind option 'forwarders'. This is also what tools like consul are doing.
