### ISSUE TITLE
Update docs tuning section to account for new default GOMAXPROCS in Go 1.5

### ISSUE THREAD

**Issue by mindscratch** [mesosphere/mesos-dns#311]
With Go 1.5 (and later) the GOMAXPROCS gets set to the max available automatically when the program is run. If mesos-dns is built with Go 1.5 (or later) then [setting GOMAXPROCS](http://mesosphere.github.io/mesos-dns/docs/performance-tuning.html) won't be necessary.

**Comment by tsenart** [comment]
@mindscratch: Once the long tail of users using older versions of mesos dns fades, we can update the documentation. Meanwhile, setting GOMAXPROCS doesn't hurt.

**Comment by sargun** [comment]
Updated.
