### ISSUE TITLE
App name resolution isn't working for Marathon apps

### ISSUE THREAD

**Issue by tobilg** [mesosphere/mesos-dns#313]
**What version of the project are you using?**
- Mesos DNS: `v0.4.0-pre`
- Mesos: `0.24.1`
- Marathon `0.11.0`

**What operating system and processor architecture are you using?**

```
admin@coreos-hw-node-1 ~ $ uname -a
Linux coreos-hw-node-1 4.1.7-coreos #2 SMP Wed Sep 16 22:54:37 UTC 2015 x86_64 Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz GenuineIntel GNU/Linux
```

**What did you do?**
I startet Mesos DNS with the following configuration:

```

  "Masters": null,
  "Zk": "zk://192.168.200.165:2181/mesos",
  "ZkDetectionTimeout": 30,
  "RefreshSeconds": 60,
  "TTL": 60,
  "Port": 53,
  "Domain": "mesos",
  "Resolvers": [
   "192.168.200.1",
   "193.101.111.10"
  ],
  "Timeout": 5,
  "SOAMname": "ns1.mesos.",
  "SOARname": "root.ns1.mesos.",
  "SOASerial": 1444222716,
  "SOARefresh": 60,
  "SOARetry": 600,
  "SOAExpire": 86400,
  "SOAMinttl": 60,
  "RecurseOn": true,
  "Listener": "192.168.200.165",
  "HttpPort": 8123,
  "DnsOn": true,
  "HttpOn": true,
  "ExternalOn": true,
  "EnforceRFC952": false,
  "IPSources": [
   "netinfo",
   "mesos",
   "host"
  ]
 }
```
via `sudo /tmp/mesos-dns -config=/tmp/config.json -v=2`

Then, I started a simple nginx web app via Marathon, which is working when I access it via the IP/port assigned by Marathon:

```
admin@coreos-hw-node-1 ~ $ curl http://192.168.200.165:31914/status
Hello from the Mini Webserver!
```

I see the logging output:

```
VERY VERBOSE: 2015/10/08 08:47:47 generator.go:508: [A] web.marathon.mesos.: 192.168.200.165
VERY VERBOSE: 2015/10/08 08:47:47 generator.go:508: [A] web-18257-s0.marathon.mesos.: 192.168.200.165
VERY VERBOSE: 2015/10/08 08:47:47 generator.go:508: [A] web.marathon.slave.mesos.: 192.168.200.165
VERY VERBOSE: 2015/10/08 08:47:47 generator.go:508: [A] web-18257-s0.marathon.slave.mesos.: 192.168.200.165
VERY VERBOSE: 2015/10/08 08:47:47 generator.go:508: [SRV]       _web._tcp.marathon.mesos.: web-18257-s0.marathon.slave.mesos.:31914
VERY VERBOSE: 2015/10/08 08:47:47 generator.go:508: [SRV]       _web._udp.marathon.mesos.: web-18257-s0.marathon.slave.mesos.:31914
VERY VERBOSE: 2015/10/08 08:47:47 generator.go:508: [SRV]       _web._tcp.marathon.slave.mesos.: web-18257-s0.marathon.slave.mesos.:31914
VERY VERBOSE: 2015/10/08 08:47:47 generator.go:508: [SRV]       _web._udp.marathon.slave.mesos.: web-18257-s0.marathon.slave.mesos.:31914
```

**What did you expect to see?**
I expected to see the status message of my sample webserver, `Hello from the Mini Webserver!` as shown above.

**What did you see instead?**
Instead, I get

```
admin@coreos-hw-node-1 /tmp $ wget http://web.marathon.mesos/status
--2015-10-08 08:50:52--  http://web.marathon.mesos/status
Resolving web.marathon.mesos... 192.168.200.165
Connecting to web.marathon.mesos|192.168.200.165|:80... failed: Connection refused.
```

So to me it seems that the "port forwarding" mechanisms is not working correctly.

```
admin@coreos-hw-node-1 /tmp $ dig _web._tcp.marathon.mesos SRV

; <<>> DiG 9.10.2-P2 <<>> _web._tcp.marathon.mesos SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21223
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;_web._tcp.marathon.mesos.      IN      SRV

;; ANSWER SECTION:
_web._tcp.marathon.mesos. 60    IN      SRV     0 0 31914 web-18257-s0.marathon.slave.mesos.

;; ADDITIONAL SECTION:
web-18257-s0.marathon.slave.mesos. 60 IN A      192.168.200.165

;; Query time: 0 msec
;; SERVER: 192.168.200.165#53(192.168.200.165)
;; WHEN: Thu Oct 08 08:53:20 UTC 2015
;; MSG SIZE  rcvd: 139
```

looks good to me though. 

```
 dig web.marathon.mesos

; <<>> DiG 9.10.2-P2 <<>> web.marathon.mesos
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61062
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;web.marathon.mesos.            IN      A

;; ANSWER SECTION:
web.marathon.mesos.     60      IN      A       192.168.200.165

;; Query time: 0 msec
;; SERVER: 192.168.200.165#53(192.168.200.165)
;; WHEN: Thu Oct 08 08:53:59 UTC 2015
;; MSG SIZE  rcvd: 52
```

as well. But I the Mesos DNS logs, I find

```
VERY VERBOSE: 2015/10/08 08:57:29 resolver.go:390: total A rrs: 11
VERY VERBOSE: 2015/10/08 08:57:29 resolver.go:391: failed looking for ;web.marathon.mesos.      IN       AAAA
```

Not sure why... Thanks for any help.

**Comment by tsenart** [comment]
Hi there!

My first hunch is that your `/etc/resolv.conf` may be misconfigured. Would you mind sharing it with us?

**Comment by tobilg** [comment]
Thanks for the fast response. Looks good to me though:

```
admin@coreos-hw-node-1 /tmp $ cat /etc/resolv.conf
# This file is managed by systemd-resolved(8). Do not edit.
#
# Third party programs must not access this file directly, but
# only through the symlink at /etc/resolv.conf. To manage
# resolv.conf(5) in a different way, replace the symlink by a
# static file or a different symlink.

nameserver 192.168.200.165
nameserver 192.168.200.1
nameserver 193.101.111.10
```

**Comment by tsenart** [comment]
Oh, wait a minute. What port forwarding mechanisms are you referring to? We have no such mechanisms in place. You need to specify the ports explicitly.

**Comment by tsenart** [comment]
Oh and by the way, thanks for following our contribution guidelines :-)

**Comment by tobilg** [comment]
No problem :-) Sorry if I was unclear. My expectation was/is that if I start an application called `web` via Marathon I can resolve `http://web.marathon.mesos/status` to the "correct" URL `http://192.168.200.165:31914/status` via Mesos DNS. Instead, it just points to port `80` as can be seen from the logs...

**Comment by tsenart** [comment]
> No problem :-) Sorry if I was unclear. My expectation was/is that if I start an application called web via Marathon I can resolve http://web.marathon.mesos/status to the "correct" URL http://192.168.200.165:31914/status via Mesos DNS. Instead, it just points to port 80 as can be seen from the logs...

Wouldn't that be great? Unfortunately, all normal DNS resolvers like the one provided by glibc query for A (IPv4) and AAAA (IPv6) records, not SRV records (which contain ports). Hence, what you expect is not satisfied :-(

> And, in the last log output from my initial issue, it seems that there's a problem with resolving the request (failed looking for ;web.marathon.mesos.). I'm not an expert on DNS, but the dig results above look more or less fine...

```
VERY VERBOSE: 2015/10/08 08:57:29 resolver.go:391: failed looking for ;web.marathon.mesos.      IN       AAAA
```

This is happening because we don't generate AAAA records, only A records.

**Comment by tobilg** [comment]
Hmmm, then I verify misunderstand the docs at http://mesosphere.github.io/mesos-dns/ saying 

> ...Applications launched by Marathon or Aurora are assigned names like search.marathon.mesos or log-aggregator.aurora.mesos. **Mesos-DNS translates these names to the IP address and port on the machine currently running each application.** To connect to an application in the Mesos datacenter, all you need to know is its name. Every time a connection is initiated, the DNS translation will point to the right machine in the datacenter.

How is this meant then? And how would service discovery be possible for Marathon? 

Before this was solve via HA Proxy AFAIK, but I assumed Mesos DNS would be the more general solution. Now I'm puzzled...

**Comment by tsenart** [comment]
Mesos-DNS *does* translate those names to the IP address and port of the machine running each instance of each application. It does so via SRV records as you exemplified before.

However, when you run `wget http://web.marathon.mesos/status`, `wget` performs an `A` type query, not an `SRV` query, so the only information it knows about is the IP address of `web.marathon.mesos` and not the port, which assumes to be`80`.

In order to reach the right ports of the tasks running on Mesos, users of Mesos-DNS must know how to query and use the SRV records returned by Mesos-DNS.

**Comment by tobilg** [comment]
Ok then, for obvious dummies like me (sorry for misunderstanding the concept), how exactly do I profit from Mesos DNS then? 

For example, if I'd have a Node.js web application (web.marathon.mesos) which connects to a MongoDB server(s) (e.g. mongodb.marathon.mesos) which are both launched via Marathon, I'd have to implement the discovery of the MongoDB server(s) in my Node.js application?

If so, where would be the benefit of using Mesos DNS from directly using the Marathon HTTP API? E.g. using `/v2/apps/{appId}` (see https://mesosphere.github.io/marathon/docs/rest-api.html).

On the Mesosphere website (https://open.mesosphere.com/getting-started/service-discovery/) there's still the HAProxy described as solution for service discovery...

**Comment by tsenart** [comment]
> Ok then, for obvious dummies like me (sorry for misunderstanding the concept), how exactly do I profit from Mesos DNS then?

> For example, if I'd have a Node.js web application (web.marathon.mesos) which connects to a MongoDB server(s) (e.g. mongodb.marathon.mesos) which are both launched via Marathon, I'd have to implement the discovery of the MongoDB server(s) in my Node.js application?

You'd use a DNS client in your application which supports SRV records. A quick Google search reveals something like: https://www.npmjs.com/package/service-agent

> If so, where would be the benefit of using Mesos DNS from directly using the Marathon HTTP API? E.g. using /v2/apps/{appId} (see https://mesosphere.github.io/marathon/docs/rest-api.html).

Then you'd limited to discover services that are running on Marathon. There many other Mesos frameworks which you couldn't reach that way. I'm also not sure about the performance impact that would have on Marathon.

> On the Mesosphere website (https://open.mesosphere.com/getting-started/service-discovery/) there's still the HAProxy described as solution for service discovery...

Thanks for bringing that up. You can certainly do it, but it isn't our blessed suggestion anymore. Using load balancers brings its own set of challenges to the table.

**Comment by tobilg** [comment]
Thanks for answering my questions so patiently... I think I learned a lot today :-) I will discuss this with our developers.

BTW, I created a minimal Docker image for Mesos DNS, see

* https://github.com/tobilg/docker-mesos-dns
* https://hub.docker.com/r/tobilg/mesos-dns/

**Comment by tsenart** [comment]
You're welcome!
