### ISSUE TITLE
mesos-dns is having trouble connecting to zookeeper

### ISSUE THREAD

**Issue by suppandi** [mesosphere/mesos-dns#318]
I am running my zookeeper/mesos-master/marathon on ubuntu with oracle java8. when i run the mesos-dns container, it continuously logs 
ERROR: 2015/10/08 17:10:12 generator.go:74: no master
ERROR: 2015/10/08 17:11:12 generator.go:74: no master
ERROR: 2015/10/08 17:12:12 generator.go:74: no master
ERROR: 2015/10/08 17:13:12 generator.go:74: no master
ERROR: 2015/10/08 17:14:12 main.go:65: ZK watcher failed: timed out waiting for initial ZK detection, exiting
ERROR: 2015/10/08 17:14:12 generator.go:74: no master
ERROR: 2015/10/08 17:15:12 generator.go:74: no master
ERROR: 2015/10/08 17:16:12 generator.go:74: no master

i see the zk is reachable from the container. seems like a bug

**Comment by tsenart** [comment]
@suppandi: I need more information to help you. Would you please follow our contribution guidelines? Thanks! https://github.com/mesosphere/mesos-dns/blob/master/CONTRIBUTING.md#issues

**Comment by suppandi** [comment]
**What version of the project are you using?**
latest versions in the ubuntu repository - zookeeper=3.4.5--1, mesos=0.24.1-0.2.35.ubuntu1404, mesos-dns docker image=latest
**What operating system and processor architecture are you using?**
amd64 ubuntu 14.04, oracle java 8
**What did you do?**
started the mesos-dns container as
    docker run --name=mesos-dns --net=host -d -v "/etc/mesos-dns/config.json:/config.json" mesosphere/mesos-dns /mesos-dns -config=/config.json
**What did you expect to see?**
expected to see mesos-dns resolving leader.mesos
What did you see instead?
mesos-dns was not resolving anything. So i did a docker logs mesos-dns and i see errors
    ERROR: 2015/10/08 17:10:12 generator.go:74: no master
    ERROR: 2015/10/08 17:11:12 generator.go:74: no master
    ERROR: 2015/10/08 17:12:12 generator.go:74: no master
    ERROR: 2015/10/08 17:13:12 generator.go:74: no master
    ERROR: 2015/10/08 17:14:12 main.go:65: ZK watcher failed: timed out waiting for initial ZK detection, exiting
    ERROR: 2015/10/08 17:14:12 generator.go:74: no master
    ERROR: 2015/10/08 17:15:12 generator.go:74: no master
    ERROR: 2015/10/08 17:16:12 generator.go:74: no master

**Comment by tsenart** [comment]
@suppandi: What mesos-dns docker image are you running? We don't officially have one. We have pre-compiled executables instead: https://github.com/mesosphere/mesos-dns/releases

**Comment by suppandi** [comment]
https://hub.docker.com/r/mesosphere/mesos-dns/

**Comment by tsenart** [comment]
@suppandi: I'm sorry, that Docker image isn't maintained at this point. Would you please use pre-compiled executable from a release instead?

PS: I'm about to release v0.4.0, if you want to wait.

**Comment by suppandi** [comment]
that worked...thanks
