### ISSUE TITLE
Implement /debug/ endpoints

### ISSUE THREAD

**Issue by tsenart** [mesosphere/mesos-dns#319]
In order to aid live debugging, Mesos-DNS should expose useful debug endpoints over HTTP.

`/debug/stats`
`/debug/loglevel`
`/debug/reload`

**Comment by tsenart** [comment]
@spacejam: I'd be really happy to have your feedback on this one.

**Comment by sargun** [comment]
@spacejam Should we expose an endpoint to trigger reloading? If so, I'd say we need to put authentication on it. As a stop-gap, I think SIGUSR1 should trigger reloading the state, rather than beginning to get into the security business.

**Comment by spacejam** [comment]
This thread completely slipped through my filter x_x I like the idea of using a signal to punt on auth.  I'm not as worried about loglevel because it has fewer consequences when abused.  Stat endpoints are super, super important for any system that exists in a DC, and we should favor over-reporting for just-in-case debugging.

**Comment by jdef** [comment]
I think stats/metrics should be broken out into a separate issue/PR and we should spend some time gathering requirements on what metrics make sense to report through a /metrics (or /stats) endpoint.

**Comment by sargun** [comment]
I'd say as far as changing the loglevel - that can be dangerous. If someone accidentally raises the log level too high, and breaks things? If we're to do it, I think it would make sense to only allow changes from localhost.

As far as the API, looking at the config.go, if we wanted to have minimum effect we could expose each of the log levels a la:
```
PUT /debug/loglevel
```
payload:
`0`, `1`, or `2`

That aligns along the glog levels, and then we can set the flags as necessary.

**Comment by sargun** [comment]
I've split this out into a couple issues:
* Signals for reload: #348 
* Metrics: #349 
* Log level: #350 

I'm going to go ahead and close this one out otherwise.
