### ISSUE TITLE
SRV Records section in docs looks broken

### ISSUE THREAD

**Issue by bobrik** [mesosphere/mesos-dns#325]
Last paragraph here: http://mesosphere.github.io/mesos-dns/docs/naming.html#srv-records

![image](https://cloud.githubusercontent.com/assets/89186/10430407/eff77f4a-70f6-11e5-81bd-80661489b40c.png)

**Comment by sargun** [comment]
This will get fixed as part of the 0.5.0 release which should happen this week.

**Comment by sargun** [comment]
Fixed.
