### ISSUE TITLE
possible malformed response with large responses

### ISSUE THREAD

**Issue by spacejam** [mesosphere/mesos-dns#326]
```
[root@ip-10-0-1-234 ~]# tcpdump -vvv -s 0 -l -n port 53
20:17:51.513349 IP (tos 0x0, ttl 64, id 56497, offset 0, flags [DF], proto UDP (17), length 74)
    10.0.1.234.37336 > 10.0.4.245.domain: [bad udp cksum 0x1b26 -> 0x84d3!] 34960+ SRV? _etcd-server._tcp.etcd.mesos. (46)
20:17:51.514077 IP (tos 0x0, ttl 64, id 25692, offset 0, flags [DF], proto UDP (17), length 740)
    10.0.4.245.domain > 10.0.1.234.37336: [udp sum ok] 34960*| q: SRV? _etcd-server._tcp.etcd.mesos. 9/0/9 _etcd-server._tcp.etcd.mesos. [1m] SRV etcd-server-19237-s0.etcd.mesos.:1025 0 0, _etcd-server._tcp.etcd.mesos. [1m] SRV etcd-server-43841-s3.etcd.mesos.:1026 0 0, _etcd-server._tcp.etcd.mesos. [1m] SRV etcd-server-43841-s3.etcd.mesos.:1025 0 0, _etcd-server._tcp.etcd.mesos. [1m] SRV etcd-server-55660-s1.etcd.mesos.:1025 0 0, _etcd-server._tcp.etcd.mesos. [1m] SRV etcd-server-19237-s0.etcd.mesos.:1027 0 0, _etcd-server._tcp.etcd.mesos. [1m] SRV etcd-server-55660-s1.etcd.mesos.:1027 0 0, _etcd-server._tcp.etcd.mesos. [1m] SRV etcd-server-19237-s0.etcd.mesos.:1026 0 0, _etcd-server._tcp.etcd.mesos. [1m] SRV etcd-server-55660-s1.etcd.mesos.:1026 0 0, _etcd-server._tcp.etcd.mesos. [1m] SRV etcd-server-43841-s3.etcd.mesos.:1027 0 0 ar: etcd-server-19237-s0.etcd.mesos. [1m] A 10.0.1.236, etcd-server-19237-s0.etcd.mesos. [1m] A 10.0.1.236, etcd-server-19237-s0.etcd.mesos. [1m] A 10.0.1.236, etcd-server-55660-s1.etcd.mesos. [1m] A 10.0.1.235, etcd-server-55660-s1.etcd.mesos. [1m] A 10.0.1.235, etcd-server-55660-s1.etcd.mesos. [1m] A 10.0.1.235, etcd-server-43841-s3.etcd.mesos. [1m] A 10.0.1.234, etcd-server-43841-s3.etcd.mesos. [1m] A 10.0.1.234, etcd-server-43841-s3.etcd.mesos. [1m] A 10.0.1.234 (712)
```
In particular, note the `length 740`.  This manifests as SRV record lookup failures in go.  Dig works, however, so it's not clear if we are mishandling large responses or if go's srv lookup code is buggy.  Go is able to resolve small responses, when I only query for _leader._tcp.mesos.  I'm working around this in etcd-mesos by providing discoveryinfo that will limit the size of the response.

**Comment by s-urbaniak** [comment]
I can reproduce the `bad cksum` also for A record lookups. I'll try to investigate it further...

1. What version of the project are you using?
https://github.com/mesosphere/mesos-dns/commit/fd4c5fc35175119faad2ef74cd18bbce9c77c56b

2. What operating system and processor architecture are you using?
Mac OSX, amd64

3. What did you do?
See below

4. What did you expect to see?
We expect to see no errors when using `tcpdump`

5. What did you see instead?
`tcpdump` reports cksum errors

Zookeeper: `$ zkServer`
Mesos master: `/usr/local/sbin/mesos-master --registry=in_memory --zk='zk://127.0.0.1:2181/mesos' --ip=127.0.0.1`
mesos-dns `config.json`:
```
{
  "zk": "zk://localhost:2181/mesos",
  "refreshSeconds": 2,
  "ttl": 60,
  "domain": "mesos",
  "port": 5253,
  "resolvers": ["8.8.8.8"],
  "timeout": 5, 
  "httpon": true,
  "dsnon": true,
  "httpport": 8123,
  "externalon": true,
  "listener": "127.0.0.1",
  "SOAMname": "root.ns1.mesos",
  "SOARname": "ns1.mesos",
  "SOARefresh": 60,
  "SOARetry":   600,
  "SOAExpire":  86400,
  "SOAMinttl": 60
}
```
query:
```
$ dig @127.0.0.1 -p 5253 leader.mesos +short A
```
tcpdump output:
```
$ sudo tcpdump -i lo0 -vvv -s 0 -l -n port 5253
09:32:49.455353 IP (tos 0x0, ttl 64, id 64428, offset 0, flags [none], proto UDP (17), length 58, bad cksum 0 (->8104)!)
    127.0.0.1.63310 > 127.0.0.1.5253: [bad udp cksum 0xfe39 -> 0x6695!] UDP, length 30
09:32:49.455478 IP (tos 0x0, ttl 64, id 26892, offset 0, flags [none], proto UDP (17), length 74, bad cksum 0 (->1395)!)
    127.0.0.1.5253 > 127.0.0.1.63310: [bad udp cksum 0xfe49 -> 0xa2a3!] UDP, length 46
```

Same issue for `SRV` lookups:
query:
```
$ dig @127.0.0.1 -p 5253 _leader._tcp.mesos +short SRV
```
tcpdump output:
```
09:33:10.334693 IP (tos 0x0, ttl 64, id 37104, offset 0, flags [none], proto UDP (17), length 64, bad cksum 0 (->ebba)!)
    127.0.0.1.58441 > 127.0.0.1.5253: [bad udp cksum 0xfe3f -> 0xd195!] UDP, length 36
09:33:10.334837 IP (tos 0x0, ttl 64, id 45800, offset 0, flags [none], proto UDP (17), length 119, bad cksum 0 (->c98b)!)
    127.0.0.1.5253 > 127.0.0.1.58441: [bad udp cksum 0xfe76 -> 0x42ec!] UDP, length 91
```

**Comment by s-urbaniak** [comment]
xref: https://sokratisg.net/2012/04/01/udp-tcp-checksum-errors-from-tcpdump-nic-hardware-offloading/, https://bugzilla.redhat.com/show_bug.cgi?id=129778

@spacejam It may be that the cksum errors are caused by nic hardware offloading as described above?!

**Comment by s-urbaniak** [comment]
Just tried from a separate VM:
```
$ dig @192.168.59.3 -p 5253 _leader._tcp.mesos +short SRV
0 0 5050 leader.mesos.
```
tcpdump:
```
$ sudo tcpdump -i enp0s8 -vvv -s 0 -l -n port 5253
tcpdump: listening on enp0s8, link-type EN10MB (Ethernet), capture size 262144 bytes
19:06:40.585041 IP (tos 0x0, ttl 64, id 55534, offset 0, flags [none], proto UDP (17), length 75)
    192.168.59.1.33605 > 192.168.59.3.5253: [bad udp cksum 0xf79d -> 0xcb47!] UDP, length 47
19:06:40.585299 IP (tos 0x0, ttl 64, id 3847, offset 0, flags [none], proto UDP (17), length 119)
    192.168.59.3.5253 > 192.168.59.1.33605: [udp sum ok] UDP, length 91
```
as expected the outgoing packet reports a cksum error (offloaded nic cksum handling), the response has no cksum error any more.

@spacejam Do you mind issuing the query from a separate machine and do a tcpdump trace from there?

**Comment by s-urbaniak** [comment]
Go adheres to https://tools.ietf.org/html/rfc1035 and limits the maximum DNS response size to 512 bytes, see https://github.com/golang/go/blob/release-branch.go1.5/src/net/dnsclient_unix.go#L43.

**Comment by s-urbaniak** [comment]
xref https://github.com/hashicorp/consul/issues/854

**Comment by s-urbaniak** [comment]
xref https://github.com/mesosphere/mesos-dns/issues/237

**Comment by s-urbaniak** [comment]
Compression is already introduced in https://github.com/mesosphere/mesos-dns/commit/b204a79ae01245b909586962068be57912ca4fc9, so that card is played already.

**Comment by discordianfish** [comment]
In general, an answer can be larger than 512 bytes, in that case EDNS is used (not supported by go / netgo) or it falls back to TCP for resolution (which golang should do). From the server side we just need to make sure that we set the truncated bit if the answer doesn't fit into 512 bytes.

**Comment by discordianfish** [comment]
Just verified: We set the truncated flag, but it seems like we also need to make sure that what we send back is complete. I've created a branch to fix the issue, but I haven't tested it yet: https://github.com/mesosphere/mesos-dns/compare/fish/fix-truncate?expand=1
This is roughly based on https://github.com/skynetservices/skydns/blob/4c00898b5ed8769af24f8dde381386f3969c2275/server/server.go#L175
