### ISSUE TITLE
resolution of AWS internal names hangs on version 0.3.0

### ISSUE THREAD

**Issue by spacejam** [mesosphere/mesos-dns#328]
With version 0.3.0 of mesos-dns, this behavior was observed on aws, which caused connection timeouts on etcd-mesos where short timeouts were employed:
```
core@ip-10-0-0-89 ~ $ time curl http://10.0.0.89:1026
404 page not found

real    0m0.004s
user    0m0.003s
sys     0m0.000s
core@ip-10-0-0-89 ~ $ time curl http://ip-10-0-0-89.us-west-2.compute.internal:1026
404 page not found

real    0m3.006s
user    0m0.004s
sys     0m0.000s
```
with `/etc/resolv.conf`:
```
options timeout:1
options attempts:3
nameserver <mesos-dns ip>
nameserver <external aws resolver>
```
conf (unchanged since working version 0.1.2):
```
{
  "zk": "zk://127.0.0.1:2181/mesos",
  "refreshSeconds": 30,
  "ttl": 60,
  "domain": "mesos",
  "port": 53,
  "resolvers": ["<external aws resolver>"],
  "timeout": 5,
  "listener": "0.0.0.0",
  "email": "root.mesos-dns.mesos"
}
```
I'm in the process of trying to reproduce with 0.4.0, and will post back with results shortly.

**Comment by spacejam** [comment]
0.4.0 seems to fix this, but its not clear to me specifically which change fixed it from the changes file.

**Comment by jdef** [comment]
Prior to v0.4 mesos-dns implemented a complicated recursion algorithm. It
was rewritten for v0.4 to be a simple forwarder instead, which is the
recommended approach according to the RFC's that describe the proper
behavior of DNS proxies. The simple forwarder does much less work (makes
fewer external system calls --> translates to shorter overall timeout
window) than the prior recursive resolver.

**Comment by tsenart** [comment]
This issue was first reported in https://github.com/mesosphere/mesos-dns/issues/297. If you're interested in the details of how this slow down manifested, have a look there.
