### ISSUE TITLE
Question: Dockerfile for running Mesos DNS via Marathon

### ISSUE THREAD

**Issue by tobilg** [mesosphere/mesos-dns#329]
I created a minimal Docker image for running Mesos DNS via Marathon: https://github.com/tobilg/docker-mesos-dns 

If this is something you're interested in, I would happily create a pull request for this.

**Comment by tsenart** [comment]
We feel the value of a official Docker image would be great once we transition to [flag based configuration](https://github.com/mesosphere/mesos-dns/issues/257) which is one of the next things I'll be working on. Until then we won't be doing this. Thanks for the suggestion!

**Comment by tsenart** [comment]
Ref: https://github.com/mesosphere/mesos-dns/issues/331
