### ISSUE TITLE
Mesos DNS Returning Internal Docker IP Address and not Host IP Address

### ISSUE THREAD

**Issue by parker20121** [mesosphere/mesos-dns#332]
I've deployed chronos on marathon (0.11.0). Using coreos 835 with mesos 0.25.0 and mesos-dns 0.4.0 as a docker container wtih docl. The same also happens for mesos 0.3.0.
```
{
  "type": "DOCKER",
  "volumes": [],
  "docker": {
    "image": "mesosphere/chronos:chronos-2.4.0-0.1.20151007110204.ubuntu1404-mesos-0.24.1-0.2.35.ubuntu1404",
    "network": "BRIDGE",
    "portMappings": [
      {
        "containerPort": 8080,
        "hostPort": 0,
        "servicePort": 10000,
        "protocol": "tcp"
      }
    ],
    "privileged": false,
    "parameters": [
      {
        "key": "name",
        "value": "chronos"
      }
    ],
    "forcePullImage": false
  }
}
```
When I perform 
```
nslookup chronos 10.105.255.249
```
 it returns the internal docker ip address that chronos is running on and not the host ip address.

```
user@hub:~/dsra-dcos/docker/mesos-dns$ nslookup chronos 10.105.255.249
Server:		10.105.255.249
Address:	10.105.255.249#53

Name:	chronos.marathon.mesos
Address: 172.17.0.4
```
I would expect to see a 10.105.x.x address.

**Comment by tsenart** [comment]
It seems like you need to change your `IPSources` as described in https://mesosphere.github.io/mesos-dns/docs/configuration-parameters.html

**Comment by parker20121** [comment]
thanks. that did it.

**Comment by naxhh** [comment]
Same here.

Netinfo as default starting from 0.25 makes no sense because no application outside that slave is able to reach the services.

Maybe is a good idea to default to host, netinfo? or I'm missing some usecase here?

**Comment by sargun** [comment]
(1) We assume you used host networking with docker
(2) We've filed a ticket to fix this issue in Mesos: https://issues.apache.org/jira/browse/MESOS-4113

**Comment by naxhh** [comment]
Thanks for the info :)

**Comment by scalp42** [comment]
@sargun more discussion on that ticket btw
