### ISSUE TITLE
Build failed for the first time Mesos-dns v0.4.0

### ISSUE THREAD

**Issue by bernadinm** [mesosphere/mesos-dns#333]
Hello,

I just attempted to install mesos-dns and got this error when attempted to build this.

I am running Ubuntu 14.04 with kernel 3.13.0-32-generic

root@abc:/usr/local/mesos-dns-0.4.0# godep go build ./...
# github.com/emicklei/go-restful
Godeps/_workspace/src/github.com/emicklei/go-restful/compressor_pools.go:12:28: error: reference to undefined identifier ‘sync.Pool’
 var GzipWriterPool = &sync.Pool{
                            ^
Godeps/_workspace/src/github.com/emicklei/go-restful/compressor_pools.go:12:32: error: expected ‘;’ or newline after top level declaration
 var GzipWriterPool = &sync.Pool{
                                ^
Godeps/_workspace/src/github.com/emicklei/go-restful/compressor_pools.go:15:2: error: expected declaration
  },
  ^
Godeps/_workspace/src/github.com/emicklei/go-restful/compressor_pools.go:29:28: error: reference to undefined identifier ‘sync.Pool’
 var GzipReaderPool = &sync.Pool{
                            ^
Godeps/_workspace/src/github.com/emicklei/go-restful/compressor_pools.go:29:32: error: expected ‘;’ or newline after top level declaration
 var GzipReaderPool = &sync.Pool{
                                ^
Godeps/_workspace/src/github.com/emicklei/go-restful/compressor_pools.go:32:2: error: expected declaration
  },
  ^
Godeps/_workspace/src/github.com/emicklei/go-restful/compressor_pools.go:51:28: error: reference to undefined identifier ‘sync.Pool’
 var ZlibWriterPool = &sync.Pool{
                            ^
Godeps/_workspace/src/github.com/emicklei/go-restful/compressor_pools.go:51:32: error: expected ‘;’ or newline after top level declaration
 var ZlibWriterPool = &sync.Pool{
                                ^
Godeps/_workspace/src/github.com/emicklei/go-restful/compressor_pools.go:54:2: error: expected declaration
  },
  ^
Godeps/_workspace/src/github.com/emicklei/go-restful/request.go:117:13: error: reference to undefined field or method ‘Reset’
   gzipReader.Reset(reader)
             ^
# github.com/miekg/dns
Godeps/_workspace/src/github.com/miekg/dns/dnssec.go:258:25: error: reference to undefined identifier ‘crypto.Signer’
 func (rr *RRSIG) Sign(k crypto.Signer, rrset []RR) error {
                         ^
Godeps/_workspace/src/github.com/miekg/dns/dnssec.go:322:13: error: reference to undefined identifier ‘crypto.Signer’
 func sign(k crypto.Signer, hashed []byte, hash crypto.Hash, alg uint8) ([]byte, error) {
             ^
Godeps/_workspace/src/github.com/miekg/dns/sig0.go:16:23: error: reference to undefined identifier ‘crypto.Signer’
 func (rr *SIG) Sign(k crypto.Signer, m *Msg) ([]byte, error) {
                       ^

# github.com/mesos/mesos-go/detector
Godeps/_workspace/src/github.com/mesos/mesos-go/detector/standalone.go:73:4: error: unknown field ‘Timeout’ in ‘http.Client’
    Timeout:   s.httpClientTimeout,
    ^
godep: go exit status 2

**Comment by tsenart** [comment]
Any particular reason why you're not using our [releases](https://github.com/mesosphere/mesos-dns/releases) instead?

In any case, it seems like your version of Go is too old where `sync.Pool` hadn't been introduced yet.

**Comment by bernadinm** [comment]
No particular reason. I saw the source code .tar.gz and wanted to just try the build process. Anyhow, I used the mesos-dns-v0.4.0-linux-amd64 binary instead and I am up and running. Thanks!
