### ISSUE TITLE
Services launched from Marathon in bridged networking mode cannot be discovered

### ISSUE THREAD

**Issue by bernadinm** [mesosphere/mesos-dns#334]
When we launch an application in marathon with  "network": "BRIDGE", it takes passes the internal docker IP address to Mesos-DNS but that IP is not resolvable from any other application. When the application gets launched with "network": "HOST", it works perfectly fine. 

Is there a way where an application can get the IP address from the HOST even when it is launched in BRIDGE mode?

**Comment by jdef** [comment]
remove docker from IPSources in your mesos-dns configuration

**Comment by bernadinm** [comment]
"IPSources": ["netinfo", "mesos", "host"]

I just checked and I don't have docker listed as an IP source.

**Comment by jdef** [comment]
please provide details for this issue according to: https://github.com/mesosphere/mesos-dns/blob/master/CONTRIBUTING.md

FWIW someone else reported a similar problem on the mesos-users list. they solved it by forcing "host" to come first in the list. This *shouldn't* be needed but there's perhaps a bug lingering somewhere that we're not seeing.

**Comment by tobilg** [comment]
@bernadinm Have you tried adding the `portMappings` property to the Docker container configuration?

```
    "container": {
        "type": "DOCKER",
        "docker": {
            "network": "BRIDGE",
            "image": "your/image",
            "portMappings": [
                {
                    "containerPort": 3000
                }
            ]
        }
    },
...
```

This works perfectly fine for me.

**Comment by nemothekid** [comment]
Experiencing this same issue after upgrading from mesosphere/mesos-dns@999adb64 to v0.4.0 

Config:
```json
{
  "masters": [
    "10.129.196.49:5050",
    "10.129.196.11:5050",
    "10.129.196.55:5050"
  ],
  "refreshSeconds": 50,
  "ttl": 60,
  "domain": "mesos",
  "port": 53,
  "resolvers": [
    "10.129.196.28"
  ],
  "timeout": 60,
  "listener": "0.0.0.0",
  "email": "root.mesos-dns.mesos",
  "externalon": false
}
```

`host` command returns internal ips.
```
AirNemo-2:mesos-dns nimi$ host kafka.marathon.mesos
kafka.marathon.mesos has address 172.17.0.1
Host kafka.marathon.mesos not found: 3(NXDOMAIN)
AirNemo-2:mesos-dns nimi$ host web-prod.marathon.mesos
web-prod.marathon.mesos has address 172.17.0.3
web-prod.marathon.mesos has address 172.17.0.2
Host web-prod.marathon.mesos not found: 3(NXDOMAIN)
```

**Comment by nemothekid** [comment]
Actually it looks like mesos 0.25.0 might be auto populating this Netinfo field with the docker container's ip address - from mesos-master state:

```json
{
          "executor_id": "",
          "framework_id": "20151002-220555-935624970-5050-17468-0000",
          "id": "kafka.f53cf4a0-8828-11e5-9c9d-00163e105035",
          "name": "kafka",
          "resources": {
            "cpus": 1.8,
            "disk": 0,
            "mem": 3072,
            "ports": "[7203-7203, 9092-9092]"
          },
          "slave_id": "5f3e0468-fcb4-4ef6-ba7a-ae189da5f050-S1",
          "state": "TASK_RUNNING",
          "statuses": [
            {
              "container_status": {
                "network_infos": [
                  {
                    "ip_address": "172.17.0.1"
                  }
                ]
              },
              "labels": [
                {
                  "key": "Docker.NetworkSettings.IPAddress",
                  "value": "172.17.0.1"
                }
              ],
              "state": "TASK_RUNNING",
              "timestamp": 1447214520.77224
            }
          ]
        }

```

Given that the networkinfo is ahead of host, by default, its using this info. The mesos-dns docs might want to reflect this? I was on a really old version of mesos-dns so I might have glossed over the break in backwards compatibility, but because it seems either mesos 0.25.0 or marathon 0.11.1 is doing this automatically, it might be worth mentioning in the docs.

**Comment by jdef** [comment]
Apparently it's mesos. I was unaware of this change in 0.25:
- https://github.com/apache/mesos/blob/0.25.0/src/docker/executor.cpp#L177

**Comment by jdef** [comment]
@karya0 prior to v0.25, in mesos-dns we could easily ignore the docker ip's by avoiding parsing the IP in the value of the `Docker.NetworkSettings.IPAddress` label. in 0.25 that IP address is being stuffed into NetworkInfo.ip_address. this is biting users. in mesos-dns it would be useful to be able to detect which addresses are docker-assigned since they're not cluster-routable by default. right now the only (hacky) way to do this is to compare the ip address in networkinfo with the value of the `Docker.NetworkSettings.IPAddress` label. not ideal. and if the label is disappearing soon then there's no way for mesos-dns to make this distinction.

looking for a clear path forward on a long term solution. adding optional Label's to each IPAddress perhaps?

**Comment by tobilg** [comment]
Coming back to the original question, I think it's a wrong understanding of how Mesos DNS could/would work.

If using `BRIDGE` networking, Marathon would assign an external port of the slave's port range if the container is configured with `portMappings` as written in my comment above.

So, using `host kibana.marathon.mesos` (as example) would be insufficient, even if it would actually return the correct IP address. 

```
$ host kibana.marathon.mesos
kibana.marathon.mesos has address 172.17.16.156
```

IMHO, the only way to use this is to query for the SRV records of the service, like

```
$ dig _kibana._tcp.marathon.mesos SRV

; <<>> DiG 9.10.2-P2 <<>> _kibana._tcp.marathon.mesos SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23087
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;_kibana._tcp.marathon.mesos.   IN      SRV

;; ANSWER SECTION:
_kibana._tcp.marathon.mesos. 60 IN      SRV     0 0 31537 kibana-8711-s0.marathon.slave.mesos.

;; ADDITIONAL SECTION:
kibana-8711-s0.marathon.slave.mesos. 60 IN A    192.168.200.162

;; Query time: 0 msec
;; SERVER: 192.168.200.162#53(192.168.200.162)
;; WHEN: Wed Nov 11 13:51:23 UTC 2015
;; MSG SIZE  rcvd: 146
```

In the `ANSWER SECTION`, one would find the port (here `31537 `), and in the `ADDITIONAL SECTION` the IP address (here `192.168.200.162`). By mapping the "hostname" ` kibana-8711-s0.marathon.slave.mesos.` between both sections, one can derive the actual `host:port` endpoint where the service lives (here `192.168.200.162:31537`).

I've written a [mesosdns-cli](https://www.npmjs.com/package/mesosdns-cli) which can resolve service names to actual endpoints, but it requires a Node.js runtime to be installed on the acting container/system.

**Comment by nemothekid** [comment]
>I think it's a wrong understanding of how Mesos DNS could/would work.

While I'm not sure 100% about OP's use case, the way we use mesos-dns is we have set ports for certain services (so `kafka` is always on port 7203, using marathon's `requirePorts` option), we just never know what host its on, hence the need for mesos-dns.

**Comment by puneetguptanitj** [comment]
I also was facing the same issue after removing netinfo from IPSources it started giving me the right IPs

"IPSources": ["mesos", "host"]

**Comment by scalp42** [comment]
@jdef any chance you could add some insight to https://issues.apache.org/jira/browse/MESOS-4113

**Comment by jdef** [comment]
xref #385

**Comment by Spritekin** [comment]
From the docs:
service.marathon.mesos -> returns the internal container IP
service.marathon.slave.mesos -> Returns the IP of the host of the container

**Comment by Vish0007** [comment]
@Spritekin 
can you please point to the document you referring to?

@jdef 
does meos dns return a cluster routable ip address? rather docker's NATted address.
I believe, mesos dns should already be using network info ip address which in-turn is decided based on network mode (bridge/host/etc.)? This is important from service discovery point.
Also, having two dns names for a 'service' 
( service.marathon.mesos/service.marathon.slave.mesos) does not help a service (ex: redis master) to determine where its peer is ruuning (ex: redis slave).

**Comment by Spritekin** [comment]
@Vish0007 
Mesos-dns Service Naming: https://mesosphere.github.io/mesos-dns/docs/naming.html

Read on the SRV Records section.

**Comment by bernadinm** [comment]
@jdef The fix in this case was actually correctly mentioned. 

By changing the order of the "host" first in the IPSources fixed the problem for me.
 "IPSources": ["netinfo", "mesos", "host"] to "IPSources": [ "host", "netinfo", "mesos"].

Closing this ticket. Thanks!

**Comment by Vish0007** [comment]
@bernadinm
I been following this issue and interested in getting this right.
After you moved "host" up the order, the containers lauched in BRIDGE mode mesos dns returns the host IP of the container and not the docker's internal IP.
?

**Comment by bernadinm** [comment]
Thats correct. @Vish0007
