### ISSUE TITLE
AAAA lookups returning NXDOMAIN for mesos-dns TLD causing leader.mesos to never get resolved

### ISSUE THREAD

**Issue by cmaloney** [mesosphere/mesos-dns#338]
This causes leader.mesos to never be resolved sometimes (python code using urllib on a machine with ipv6 disabled, but with an ipv6 capable resolver). The system resolver asks for the IPv6 address first / does an AAAA request for leader.mesos. That returns NXDOMAIN. The system resolver got a positive "does not exist" response, so it never tries for an A record / IPv4.

Log snippet:
```Nov 09 03:48:08 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:08 generator.go:70: Zookeeper says the leader is:  10.240.0.5:5050
Nov 09 03:48:08 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:08 generator.go:162: reloading from master 10.240.0.5
Nov 09 03:48:08 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:08 generator.go:508: [A]        marathon.mesos.: 10.240.0.6
Nov 09 03:48:08 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:08 generator.go:508: [SRV]        _framework._tcp.marathon.mesos.: marathon.mesos.:45395
Nov 09 03:48:08 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:08 generator.go:508: [A]        slave.mesos.: 10.240.0.8
Nov 09 03:48:08 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:08 generator.go:508: [SRV]        _slave._tcp.mesos.: slave.mesos.:5051
Nov 09 03:48:08 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:08 generator.go:508: [A]        slave.mesos.: 10.240.0.4
Nov 09 03:48:08 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:08 generator.go:508: [A]        root.ns1.mesos.: 10.240.0.7
Nov 09 03:48:08 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:08 generator.go:508: [A]        root.ns1.mesos.: 172.17.0.1
Nov 09 03:48:08 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:08 generator.go:508: [A]        leader.mesos.: 10.240.0.5
Nov 09 03:48:08 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:08 generator.go:508: [A]        master.mesos.: 10.240.0.5
Nov 09 03:48:08 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:08 generator.go:508: [SRV]        _leader._tcp.mesos.: leader.mesos.:5050
Nov 09 03:48:08 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:08 generator.go:508: [SRV]        _leader._udp.mesos.: leader.mesos.:5050
Nov 09 03:48:08 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:08 generator.go:508: [A]        master0.mesos.: 10.240.0.5
Nov 09 03:48:08 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:08 generator.go:508: [A]        master.mesos.: 10.240.0.7
Nov 09 03:48:08 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:08 generator.go:508: [A]        master1.mesos.: 10.240.0.7
Nov 09 03:48:08 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:08 generator.go:508: [A]        master.mesos.: 10.240.0.6
Nov 09 03:48:08 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:08 generator.go:508: [A]        master2.mesos.: 10.240.0.6
Nov 09 03:48:08 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:08 logging.go:75: {MesosRequests:2818 MesosSuccess:1744 MesosNXDomain:1074 MesosFailed:0 NonMesosRequests:21672 NonMesosSuccess:21672 NonMesosNXDomain:21384 NonMesosFailed:0 NonMesosForwarded:21672}
Nov 09 03:48:09 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:09 resolver.go:384: total A rrs:        8
Nov 09 03:48:09 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:09 resolver.go:385: failed looking for ;leader.mesos.        IN         AAAA
Nov 09 03:48:09 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:09 resolver.go:384: total A rrs:        8
Nov 09 03:48:09 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:09 resolver.go:385: failed looking for ;leader.mesos.        IN         AAAA
Nov 09 03:48:11 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:11 resolver.go:384: total A rrs:        8
Nov 09 03:48:11 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:11 resolver.go:385: failed looking for ;leader.mesos.        IN         AAAA
Nov 09 03:48:13 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:13 resolver.go:384: total A rrs:        8
Nov 09 03:48:13 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:13 resolver.go:385: failed looking for ;leader.mesos.        IN         AAAA
Nov 09 03:48:15 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:15 resolver.go:384: total A rrs:        8
Nov 09 03:48:15 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:15 resolver.go:385: failed looking for ;leader.mesos.        IN         AAAA
Nov 09 03:48:15 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:15 resolver.go:384: total A rrs:        8
Nov 09 03:48:15 v3-installer-1d2p mesos-dns[2031]: VERY VERBOSE: 2015/11/09 03:48:15 resolver.go:385: failed looking for ;leader.mesos.        IN         AAAA
```

**Comment by sargun** [comment]
So, is the ask / remedy to return NODATA here? Or do you want Mesos-DNS to return IPv4 converted addresses?

**Comment by cmaloney** [comment]
I'd prefer NODATA here, although practically we should test with the client library that doesn't work with the NXDOMAIN and make sure that works.

**Comment by malnick** [comment]
I can confirm I'm seeing this same behavior on site at Apple this week. Regardless of kernel or OS settings for the resolver, the history service keeps stubbornly looking up quad A records. It appears to act independently of the OS resolver / kernel settings so we need to ensure we only do ipv4 lookups for the resolver client in the history service.

**Comment by sargun** [comment]
Do you have the state.json to recreate this?

**Comment by cmaloney** [comment]
I think this one all comes down to zk:// for generating leader.mesos.

The config we use:
```
{
  "zk": "zk://127.0.0.1:2181/mesos",
  "refreshSeconds": 30,
  "ttl": 60,
  "domain": "mesos",
  "port": 53,
  "externalOn": false,
  "timeout": 5,
  "listener": "0.0.0.0",
  "email": "root.mesos-dns.mesos"
}
```

**Comment by sargun** [comment]
Yeah, I'm just unsure of how this can slip through - we handle this case in the resolver:
```
if qType == dns.TypeAAAA && len(rs.SRVs[name])+len(rs.As[name]) > 0 {
		m.Rcode = dns.RcodeSuccess
	}
```
The second part should show true, because there is an entry for "A" as: leader.mesos.: 10.240.0.5

**Comment by amulyas** [comment]
one of my three mesos master always trow this error in mesos-dns logs is this expected 

Nov 15 00:13:12 ip-172-18-8-187.ec2.internal dcos-history[598]: [INFO:2015-11-15 00:13:12,943] Get state from leading master http://172.18.8.189:5050/
Nov 15 00:13:13 ip-172-18-8-187.ec2.internal systemd[1]: dcos-signal.service: Service hold-off time over, scheduling restart.
Nov 15 00:13:13 ip-172-18-8-187.ec2.internal systemd[1]: Starting DCOS Tracking...
Nov 15 00:13:13 ip-172-18-8-187.ec2.internal ping[1441]: PING leader.mesos (172.18.8.189) 56(84) bytes of data.
Nov 15 00:13:13 ip-172-18-8-187.ec2.internal ping[1441]: 64 bytes from ip-172-18-8-189.ec2.internal (172.18.8.189): icmp_seq=1 ttl=64 time=0.345 ms
Nov 15 00:13:13 ip-172-18-8-187.ec2.internal ping[1441]: --- leader.mesos ping statistics ---
Nov 15 00:13:13 ip-172-18-8-187.ec2.internal ping[1441]: 1 packets transmitted, 1 received, 0% packet loss, time 0ms
Nov 15 00:13:13 ip-172-18-8-187.ec2.internal ping[1441]: rtt min/avg/max/mdev = 0.345/0.345/0.345/0.000 ms
Nov 15 00:13:13 ip-172-18-8-187.ec2.internal systemd[1]: Started DCOS Tracking.
Nov 15 00:13:13 ip-172-18-8-187.ec2.internal mesos-dns[826]: VERY VERBOSE: 2015/11/15 00:13:13 resolver.go:384: total A rrs:        20
Nov 15 00:13:13 ip-172-18-8-187.ec2.internal mesos-dns[826]: VERY VERBOSE: 2015/11/15 00:13:13 resolver.go:385: failed looking for ;leader.mesos.        IN         AAAA
Nov 15 00:13:13 ip-172-18-8-187.ec2.internal mesos-dns[826]: VERY VERBOSE: 2015/11/15 00:13:13 resolver.go:384: total A rrs:        20
Nov 15 00:13:13 ip-172-18-8-187.ec2.internal mesos-dns[826]: VERY VERBOSE: 2015/11/15 00:13:13 resolver.go:385: failed looking for ;leader.mesos.        IN         AAAA
Nov 15 00:13:14 ip-172-18-8-187.ec2.internal mesos-dns[826]: VERY VERBOSE: 2015/11/15 00:13:14 resolver.go:384: total A rrs:        20

**Comment by sargun** [comment]
We found the root cause of this. See #365. There will be a release out shortly to fix.
