### ISSUE TITLE
when using mesos-dns, mesos-master cannot detect mesos-slave.

### ISSUE THREAD

**Issue by letusfly85** [mesosphere/mesos-dns#364]
### 1. What version of the project are you using?

v0.5.0-linux-amd64

### 2. What operating system and processor architecture are you using?

ubuntu 14.04 on AWS ec2

### 3. What did you do?

I launched 3 instances.

1. mesos-master
1. mesos-slave
1. mesos-dns

mesos-master and mesos-slave 's `resolve.conf` use only `mesos-dns` address.

And, I run mesos-dns process.

### 4. What did you expect to see?

After running mesos-dns process, I succeeded to `dig master.mesos`,
Howver, when I checked webui `http://${MESOS_MASTER}:5050` slave tab, I cannot see slave list any one.. and also cannot get node list through `dcos node` command..

I want to see `mesos-slave` on webui and `dcos node` command.

### 5. What did you see instead?

I wanted to see mesos-slave on webui and `dcos node` command.

Why cannot mesos-master detect mesos-slave after setting `resolve.conf` and running mesos-dns process.

**Comment by sargun** [comment]
So, I'm attempting to reproduce this issue. Are you running DCOS, or are you running Mesos-DNS on a cluster that you built? 

Can you provide the Mesos-DNS log? You can get them on DCOS like so: journalctl -n 100 -u dcos-mesos-dns.service

**Comment by letusfly85** [comment]
thank you for replying.

I'm running Mesos-DNS on a cluster that I build.

here is Mesos-DNS log below. verbose level, I gave 1.

```bash
root@ip-*-*-*-*:~# ./mesos-dns-v0.5.0-linux-amd64 --config=config.json -v 1
VERBOSE: 2015/11/21 17:35:52 config.go:102: config loaded from "/root/config.json"
VERBOSE: 2015/11/21 17:35:52 config.go:133: Mesos-DNS configuration:
VERBOSE: 2015/11/21 17:35:52 config.go:134:    - Masters:
VERBOSE: 2015/11/21 17:35:52 config.go:135:    - Zookeeper:  zk://*.*.*.*:2181/mesos
VERBOSE: 2015/11/21 17:35:52 config.go:136:    - ZookeeperDetectionTimeout:  30
VERBOSE: 2015/11/21 17:35:52 config.go:137:    - RefreshSeconds:  60
VERBOSE: 2015/11/21 17:35:52 config.go:138:    - Domain: mesos
VERBOSE: 2015/11/21 17:35:52 config.go:139:    - Listener: +.+.+.+
VERBOSE: 2015/11/21 17:35:52 config.go:140:    - Port:  53
VERBOSE: 2015/11/21 17:35:52 config.go:141:
VERBOSE: 2015/11/21 17:35:52 config.go:143:    - Timeout:  5
VERBOSE: 2015/11/21 17:35:52 config.go:144:    - StateTimeoutSeconds:  300
VERBOSE: 2015/11/21 17:35:52 config.go:145:    - Resolvers: #.#.#.2
VERBOSE: 2015/11/21 17:35:52 config.go:146:    - ExternalOn:  true
VERBOSE: 2015/11/21 17:35:52 config.go:147:    - SOAMname: ns1.mesos.
VERBOSE: 2015/11/21 17:35:52 config.go:148:    - SOARname: root.ns1.mesos.
VERBOSE: 2015/11/21 17:35:52 config.go:149:    - SOASerial:  1448127352
VERBOSE: 2015/11/21 17:35:52 config.go:150:    - SOARefresh:  60
VERBOSE: 2015/11/21 17:35:52 config.go:151:    - SOARetry:  600
VERBOSE: 2015/11/21 17:35:52 config.go:152:    - SOAExpire:  86400
VERBOSE: 2015/11/21 17:35:52 config.go:153:    - SOAExpire:  60
VERBOSE: 2015/11/21 17:35:52 config.go:154:    - RecurseOn:  true
VERBOSE: 2015/11/21 17:35:52 config.go:155:    - HttpPort:  8123
VERBOSE: 2015/11/21 17:35:52 config.go:156:    - HttpOn:  true
VERBOSE: 2015/11/21 17:35:52 config.go:157:    - ConfigFile:  /root/config.json
VERBOSE: 2015/11/21 17:35:52 config.go:158:    - EnforceRFC952:  false
VERBOSE: 2015/11/21 17:35:52 config.go:159:    - IPSources:  [netinfo mesos host]
VERBOSE: 2015/11/21 17:35:52 main.go:88: Starting master detector for ZK  zk://*.*.*.*:2181/mesos
2015/11/21 17:35:52 Connected to *.*.*.*:2181
2015/11/21 17:35:52 Authenticated: id=94904144457696186, timeout=40000
```

**Comment by letusfly85** [comment]
And I use ubuntu 14.04, I don't use systemctl

**Comment by letusfly85** [comment]
after some try and error, I succeeded starting mesos-slave, however I cannot start `etcd` using `dcos package install etcd`...

here is a script I started mesos-slave.

on slave node, I did it below.

```bash
esos-slave -zk=zk://master.mesos:2181/mesos --master=zk://master.mesos:2181/mesos  --hostname=${slave_ip} &
```

if I missed a parameter `-zk=zk://master.mesos:2181/mesos`, I couldn't start slave.

**Comment by letusfly85** [comment]
And after starting slave, I got many stdout like below..
through mesos master web ui, many times etcd task failed again and again...

```bash
I1121 18:08:07.488327 16646 gc.cpp:56] Scheduling '/tmp/mesos/meta/slaves/bdd45e00-7616-4aa2-a7fb-8e89940aecdd-S3/frameworks/164d97d3-9234-459e-bcc1-b70193c62df8-0000/executors/etcd.d119d966-907a-11e5-bb0b-0242d2b67779/runs/238af8ed-181c-48a1-aea5-484de45f76b5' for gc 6.99999434875259days in the future
I1121 18:08:07.488363 16646 gc.cpp:56] Scheduling '/tmp/mesos/meta/slaves/bdd45e00-7616-4aa2-a7fb-8e89940aecdd-S3/frameworks/164d97d3-9234-459e-bcc1-b70193c62df8-0000/executors/etcd.d119d966-907a-11e5-bb0b-0242d2b67779' for gc 6.99999434859852days in the future
I1121 18:08:07.488347 16651 status_update_manager.cpp:284] Closing status update streams for framework 164d97d3-9234-459e-bcc1-b70193c62df8-0000
I1121 18:08:07.488396 16646 gc.cpp:56] Scheduling '/tmp/
```

**Comment by letusfly85** [comment]
If you want to some info, please let me know.

Thank you.

**Comment by sargun** [comment]
So, it sounds like Mesos-DNS is working fine, the problems you're having are with the ETCd framework?

**Comment by sargun** [comment]
Can you go to one of those container's sandboxes, and dump their stderr, and stdout?

**Comment by letusfly85** [comment]
Sure of course, however today I got limitation of working, next day I will send you..sorry :sweat_drops:

**Comment by letusfly85** [comment]
I got it.

when I started like below, I succeeded start mesos-slave.

```bash
mesos-slave --master=zk://master.mesos:2181/mesos  --containerizers=docker,mesos
```

I missed `docker` in containerizers paramters.
However, from `service`command, I still cannot start mesos-slave... and there are no log..

**Comment by sargun** [comment]
This doesn't sound like a Mesos-DNS problem, I'm curious as to why you think it's a Mesos-DNS issue?

**Comment by letusfly85** [comment]
Sorry, I misunderstood service discovery of Mesos-master to Mesos-slave.
Through, zookeeper, mesos-master detects mesos-slave. (correctly, launching mesos-slave, slave tell zookeeper, and master handle it, I think).

However, using Mesos-dns, it would change,,,,,I misunderstood.

**Comment by letusfly85** [comment]
And, some of the `dcos package install ${app}` doesn't work, so, I wondered where its cause is due to dns or slave or application definition (such as `marathon.json`).

**Comment by sargun** [comment]
@letusfly85 I think it's best to take these comments to the DCOS community room? Or if the specific ${app} has a github repo, that would work too. 

Is it okay if I close this? @letusfly85

**Comment by letusfly85** [comment]
@sargun 

Yes, I comments to the DCOS community room. (And thank you! for replying in the room!)

Yes, it's okay to close this.

Thank you!
