### ISSUE TITLE
version.go hasn't changed for a long time

### ISSUE THREAD

**Issue by asdfsx** [mesosphere/mesos-dns#376]
Although the version has changed many times, but the version.go is still "dev"
It's not a big problem~~~, but every time I use "mesos-dns -version", it feels a little strange

**Comment by sargun** [comment]
@asdfsx Is there any reason why you're not using the builds from Github / Circle-CI? Those have the version number set.

**Comment by asdfsx** [comment]
Actually I'm trying to build an mesos-dns docker image based on alpine linux. So I do it in an quick and easy way, compile it on my laptop. I'll try to use Circle-CI later.
