### ISSUE TITLE
Allow configuration of CIDRs for which mesos-dns will allow recursion

### ISSUE THREAD

**Issue by lloesche** [mesosphere/mesos-dns#383]
At the moment mesos-dns will allow recursion for anyone able to talk to it. It would be nice if there was a config option like bind's
```
allow-recursion {192.168.2.0/24;};
```
that limits which hosts are allowed to use mesos-dns as a resolver. Otherwise a mesos-dns that's available on the internet is automatically an open resolver.

**Comment by sargun** [comment]
I would say that security is the job of IPTables or putting a resolver in front of Mesos-DNS. In addition, does Mesos expose any confidential information, except by means of brute force?

**Comment by lloesche** [comment]
The problem is a different one. In DNS you distinguish between zones the nameserver is authoritative for and those that he is just a dumb resolver for. For instance in power-dns those concerns are separated into two different unix processes. One for serving the authoritative zones (in the case of mesos-dns that would be .mesos) and one for resolving other domains on behalf of the requesting client.

Now in mesos-dns there's currently no such separation. If you have access it's always authoritative for it's one zone but also resolving for it's clients. Without any restrictions.

An IP filter can't help solve this problem because client communication always happens on the same port 53/udp. Now what you generally want is that the nameserver answers dns queries to zones he's authoritative for to anyone (0.0.0.0/0) but resolving other domains like google.com where he forwards the query to other nameservers on behalf of the client should only be done for authorised CIDR blocks like from the local subnet (e.g. 192.168.2.0/24 in the example above).

Without this function your nameserver can be abused for DNS reflection attacks. Or if you always have to firewall off mesos-dns it's unusable as a authoritative nameserver to anyone but trusted clients which limits it's use drastically.

**Comment by sargun** [comment]
Why couldn't you put BIND infront of Mesos-DNS, and have BIND do the filtering?

**Comment by lloesche** [comment]
You could do that if Mesos-DNS supported zone transfers. In that case you might put bind in front of it and configure the mesos zone as a slave zone on bind and turn off recursion. But Mesos-DNS doesn't seem to have AXFR support. At least it didn't work for me when I tried to transfer the mesos zone from localhost.

In any case Mesos-DNS is a recursor by default (Google DNS is preconfigured in the sample config and in code). As such it should have an option that limits the clients that are allowed to recurse (and come with a sane default).
Currently a user that installs Mesos-DNS on their server will by default get an insecure nameserver that can be used to attack 3rd party hosts using DNS reflection.

**Comment by sargun** [comment]
(1) You can disable recursion in Mesos-DNS in the configuration file

(2) You can configure Mesos-DNS as an upstream in bind - as a forwarding zone.

**Comment by lloesche** [comment]
Then maybe we should remove recursion as a function in Mesos-DNS entirely and make the default architecture for those who need recursion a combination of bind and Mesos-DNS.
At least then the user has to explicitly configure it. Right now he just gets it by default even if all he wants is the Mesos service discovery part of Mesos-DNS.

**Comment by jdef** [comment]
AFAIK recursion was removed a while back and replaced with simple
forwarding.

**Comment by sargun** [comment]
@lloesche For DCOS, we can do that? We can put a smarter DNS server on localhost and have that in /etc/resolv.conf. That server can either forward or go to mesos-dns depending on the TLD. Does that seem like a reasonable path forward?

**Comment by jdef** [comment]
doesn't it complicate deployment and ongoing configuration updates to have
a dns service running on every node in the cluster? if we want to make
mesos-dns a secondary service that serves only the .mesos zone, why not run
BIND (or whatever) on the same node as mesos-dns and have it forward .mesos
queries to mesos-dns?

**Comment by sargun** [comment]
That would work too. The only reason I suggested that running it on every node in DCOS is that if you're trying to limit access, you don't know the IP addresses of the agents, and if you're trying to limit access, I don't see a way to generate ACLs on the master for all the agent IPs ahead of time.

The way I see it working for DCOS is like the following:
```
          Agent                                          Master
+-------------------------+                     +----------------------------+
|      +---------+        |                     |                            |
|      |  Glibc  |        |                     |                            |
|      +----+----+        |                     | +-----------------+        |
|           |             |                     | |     Mesos-DNS   |        |
|      +----v----+        |           +----------->                 |        |
|      |  BIND   +--------------------+         | +-----------------+        |
|      +----+----+        |   *.mesos           |                            |
|           |             |                     |                            |
+-------------------------+                     +----------------------------+
            |
            |
+-----------v-------------+
|                         |
|      DNS Server         |
|                         |
+-------------------------+
```

Then Mesos-DNS on the master can have recursion off, and the BIND locally can limit queries to 127/8, and 0000::/8.

**Comment by sargun** [comment]
Have you looked at IPTables as a potential solution as well? 
http://sf-alpha.bjgang.org/wordpress/2013/01/iptables-for-common-dns-amplification-attack-on-recursive-dns-inside-your-network/
