### ISSUE TITLE
dnssec-validation set to auto on bind9 doesn't work with mesos-dns

### ISSUE THREAD

**Issue by aglahe** [mesosphere/mesos-dns#387]
It appears, that when bind has dnssec-validation set to _auto_ forwarding on to mesos-dns fails.  However, setting it to _none_ appears to fix the issue.

BIND 9.9.5-3ubuntu0.7-Ubuntu (Extended Support Version) running on Ubuntu 14.04

**Comment by sargun** [comment]
We do not plan to support dnssec.

**Comment by jdef** [comment]
Can we make this more apparent on the project README? It's come up several
times and it behooves us to properly set expectations.

**Comment by aglahe** [comment]
Is there a way that we can have dnssec turned on for the rest of DNS....but not for anything that forwards on to MesosDNS?  I guess we could take it out of the global settings and put make set it to "no" in the section that forwards to MesosDNS
