### ISSUE TITLE
Cleanup insertRR

### ISSUE THREAD

**Issue by sargun** [mesosphere/mesos-dns#390]
insertRR currently will generate a massive amount of CPU if there are a large number of tasks. Part of this is due to the exists function, which has a naive loop per slave to check for colliding records. We need to do performance testing, and improvement for high-task count clusters.

**Comment by jdef** [comment]
it would be great if we could somehow decide which tasks were not worth
adding to the recordset at all. maybe if discovery-info.visibility ==
"none" ?

**Comment by cmaloney** [comment]
On a Mesos cluster with 8k tasks, runtime.memeqbody starts taking ~22% in a `perf top`, and `github.com/mesosphere/mesos-dns/records.(*RecordGenerator).exists` takes ~9%. The cluster had 10 agents, 800 tasks per agent. @sargun has some ideas / did some digging and found a lot more calls to the runtime.memeqbody than needed. Sent you the state.json

**Comment by jdef** [comment]
thinking that it should be easy to covert the records container from a
slice to a `map[string]struct{}`. we're not really concerned about order
any way. maps are just as easy to iterate over and queries for exact
matches is much faster

**Comment by jdef** [comment]
fixed by #395
