### ISSUE TITLE
mesos-dns cannot startup and it seems some port error

### ISSUE THREAD

**Issue by riverxing** [mesosphere/mesos-dns#409]
`Mar 07 16:33:05 master1 polkitd[758]: Registered Authentication Agent for unix-process:32305:457184784 (system bus name :1.42314 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Mar 07 16:33:05 master1 systemd[1]: Stopping Mesos-DNS...
Mar 07 16:33:05 master1 systemd[1]: mesos-dns.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 07 16:33:05 master1 systemd[1]: Unit mesos-dns.service entered failed state.
Mar 07 16:33:05 master1 systemd[1]: mesos-dns.service failed.
Mar 07 16:33:05 master1 zookeeper[1159]: 2016-03-07 16:33:05,775 [myid:1] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception
Mar 07 16:33:05 master1 zookeeper[1159]: EndOfStreamException: Unable to read additional data from client sessionid 0x15344d170e10015, likely client has closed socket
Mar 07 16:33:05 master1 zookeeper[1159]: at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
Mar 07 16:33:05 master1 zookeeper[1159]: at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
Mar 07 16:33:05 master1 zookeeper[1159]: at java.lang.Thread.run(Thread.java:745)
Mar 07 16:33:05 master1 zookeeper[1159]: 2016-03-07 16:33:05,780 [myid:1] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1007] - Closed socket connection for client /10.1.241.127:39888 which had sessionid 0x15344d170e10015
Mar 07 16:33:05 master1 systemd[1]: Started Mesos-DNS.
Mar 07 16:33:05 master1 systemd[1]: Starting Mesos-DNS...
Mar 07 16:33:05 master1 polkitd[758]: Unregistered Authentication Agent for unix-process:32305:457184784 (system bus name :1.42314, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Mar 07 16:33:05 master1 mesos-dns[32311]: 2016/03/07 16:33:05 Connected to 10.1.241.127:2181
Mar 07 16:33:05 master1 zookeeper[1159]: 2016-03-07 16:33:05,802 [myid:1] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@197] - Accepted socket connection from /10.1.241.127:39890
Mar 07 16:33:05 master1 zookeeper[1159]: 2016-03-07 16:33:05,804 [myid:1] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@822] - Connection request from old client /10.1.241.127:39890; will be dropped if server is in r-o mode
Mar 07 16:33:05 master1 zookeeper[1159]: 2016-03-07 16:33:05,804 [myid:1] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@868] - Client attempting to establish new session at /10.1.241.127:39890
Mar 07 16:33:05 master1 zookeeper[1159]: 2016-03-07 16:33:05,820 [myid:1] - INFO  [CommitProcessor:1:ZooKeeperServer@617] - Established session 0x15344d170e10016 with negotiated timeout 40000 for client /10.1.241.127:39890
Mar 07 16:33:05 master1 mesos-dns[32311]: 2016/03/07 16:33:05 Authenticated: id=95495683437559830, timeout=40000
Mar 07 16:33:05 master1 mesos-master[5403]: I0307 16:33:05.825168  5405 http.cpp:334] HTTP GET for /master/state.json from 10.1.241.127:37165 with User-Agent='Go-http-client/1.1'
Mar 07 16:33:05 master1 mesos-master[5403]: I0307 16:33:05.832132  5408 http.cpp:334] HTTP GET for /master/state.json from 10.1.241.127:37165 with User-Agent='Go-http-client/1.1'
^C`
my config.json seems like this

`{
  "zk": "zk://10.1.241.122:2181,10.1.241.123:2181,10.1.241.124:2181/mesos",
  "masters": ["10.1.241.122:5050", "10.1.241.123:5050", "10.1.241.124:5050"],
  "refreshSeconds": 60,
  "ttl": 60,
  "domain": "ai",
  "port": 53,
  "resolvers": ["10.1.241.123","10.1.1.7","10.1.1.8"],
  "httpon":true,
  "dnson":true,
  "httpport":8123,
  "timeout": 5,
  "IPSources":["netinfo","host"]
}
`
why mesos-dns need port 39890,my zk port area is 2888:3888.Do I need spread the area

**Comment by jdef** [comment]
That's an ephemeral port (39890) used by the client side of a TCP
connection that mesos-dns establishes with zk -- it's completely ordinary.

Please increase the verbosity of the mesos-dns logs and re-test.

**Comment by riverxing** [comment]
I am so sorry,it is my fault
