### ISSUE TITLE
How to get container ip by the http rest api?

### ISSUE THREAD

**Issue by AI-PaaS** [mesosphere/mesos-dns#413]
Hello:
        We use mesos-dns as the mesos cluster dns and its configuration is "netinfo" and "host". and we use flannel as the docker network plugin. So, the containers can access through multi host. We can get  the container ip by digging commands, but can not get the container ip by http api?

Can someone help us? Thx.

**Comment by jdef** [comment]
the DNS and HTTP interface deliver data from the same backend store. can
you provide a log of a terminal session showing the exact problem that
you're observing?

**Comment by AI-PaaS** [comment]
/etc/mesos-dns/config.json
{
  "zk": "zk://10.1.241.122:2181,10.1.241.123:2181,10.1.241.124:2181/mesos",
  "masters": ["10.1.241.122:5050", "10.1.241.123:5050", "10.1.241.124:5050"],
  "refreshSeconds": 60,
  "ttl": 60,
  "domain": "ai",
  "port": 53,
  "resolvers": ["10.1.228.199"],
  "httpon":true,
  "dnson":true,
  "httpport":8123,
  "timeout": 5,
  "IPSources":["netinfo","host"]
}

we deploy tomcat 8.0 with three instances with network bridge.

dig tomcat-8.marathon.ai
   ; <<>> DiG 9.9.4-RedHat-9.9.4-18.el7_1.5 <<>> tomcat-8.marathon.ai
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48720
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;tomcat-8.marathon.ai.          IN      A

;; ANSWER SECTION:
tomcat-8.marathon.ai.   60      IN      A       172.18.3.3
tomcat-8.marathon.ai.   60      IN      A       172.18.3.4
tomcat-8.marathon.ai.   60      IN      A       172.18.78.4

;; Query time: 2 msec
;; SERVER: 10.1.241.124#53(10.1.241.124)
;; WHEN: Tue Mar 22 10:
  
docker inspect xxxxxx
        "Links": null,
                    "Aliases": null,
                    "NetworkID": "a987a6d350489dabcfe2878a5a87275b70d5b3ea922ff2edaa328dbb235bef97",
                    "EndpointID": "8dd953c18e746cfd5a4a1f0dcee16fe4a9a0db4dce0736746b52cdbcf16e917c",
                    "Gateway": "172.18.78.1",
                    "IPAddress": "172.18.78.4",

dig _tomcat-8._tcp.marathon.ai SRV

; <<>> DiG 9.9.4-RedHat-9.9.4-18.el7_1.5 <<>> _tomcat-8._tcp.marathon.ai SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6885
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 3

;; QUESTION SECTION:
;_tomcat-8._tcp.marathon.ai.    IN      SRV

;; ANSWER SECTION:
_tomcat-8._tcp.marathon.ai. 60  IN      SRV     0 0 31564 tomcat-8-m9y9e-s1.marathon.slave.ai.
_tomcat-8._tcp.marathon.ai. 60  IN      SRV     0 0 31564 tomcat-8-oe7kq-s1.marathon.slave.ai.
_tomcat-8._tcp.marathon.ai. 60  IN      SRV     0 0 31775 tomcat-8-akje3-s1.marathon.slave.ai.

;; ADDITIONAL SECTION:
tomcat-8-oe7kq-s1.marathon.slave.ai. 60 IN A    10.1.241.123
tomcat-8-akje3-s1.marathon.slave.ai. 60 IN A    10.1.241.125
tomcat-8-m9y9e-s1.marathon.slave.ai. 60 IN A    10.1.241.125

;; Query time: 1 msec
;; SERVER: 10.1.241.124#53(10.1.241.124)
;; WHEN: Tue Mar 22 10:42:56 CST 2016
;; MSG SIZE  rcvd: 326


curl http://10.1.241.124:8123/v1/services/tomcat-8.marathon.ai
[
  {
   "service": "",
   "host": "",
   "ip": "",
   "port": ""
  }
 ]

curl http://10.1.241.124:8123/v1/services/_tomcat-8._tcp.marathon.ai

[
  {
   "service": "_tomcat-8._tcp.marathon.ai",
   "host": "tomcat-8-oe7kq-s1.marathon.slave.ai.",
   "ip": "10.1.241.123",
   "port": "31564"
  },
  {
   "service": "_tomcat-8._tcp.marathon.ai",
   "host": "tomcat-8-akje3-s1.marathon.slave.ai.",
   "ip": "10.1.241.125",
   "port": "31775"
  },
  {
   "service": "_tomcat-8._tcp.marathon.ai",
   "host": "tomcat-8-m9y9e-s1.marathon.slave.ai.",
   "ip": "10.1.241.125",
   "port": "31564"
  }
 ]

**Comment by AI-PaaS** [comment]
As the above output, we can get container ip from dig command, but can not get it from http api. we use marathon: 0.15.3, mesos-dns:0.5.0

**Comment by jdef** [comment]
Have you tried to query /v1/hosts/{host}? That would be the analogue of the
A dig query that gives you container IPs

**Comment by AI-PaaS** [comment]
Thx. yes, from hosts api i can get the container ip
