### ISSUE TITLE
Allow framework to better customize record names with dots in it

### ISSUE THREAD

**Issue by zhitaoli** [mesosphere/mesos-dns#414]
Hi,

I've been working on introducing DiscoveryInfo from Apache Aurora to Mesos, and a pet sub-project would be get Mesos DNS to work so people have one more alternative of using the software.

The small WIP change to Aurora is at https://reviews.apache.org/r/45177/.

While the connecting the Mesos master to mesos-dns is easy, the records we get is not really usable.

For example, an Aurora job 'vagrant/test/http_example_docker' would get a A record like **http_example_docker.twitterscheduler.mesos**. Although we could export `name` field in any form compatible, I couldn't really find a tutorial or document about how we can generate a good name.

Ideally, we want to a inverse domain name like:

**http-example-docker.test.vagrant.<framework-name>.<mesos-domain-name>**

Also, if we could allow some override of framework name to a different sub-domain, that's even better, but it's pretty optional for now.

Can someone comment on how we could do this? Maybe introducing some ways to allow framework owner or operator to specify how to do that?

Many thanks!

**Comment by sargun** [comment]
If I'm understanding correctly, you're intentionally trying to introduce dots in the domain name?

**Comment by jdef** [comment]
allowing a framework to intentionally introduce sub-domains is something that we're specifically trying to avoid. there's no way to stop tasks from accidentally clobbering and/or masking each other's names in such cases. relying on frameworks to be smart enough to avoid this, or operators for that matter, is probably not an approach that mesos-dns is willing to take.

is there more to your use case? perhaps we could come up with an alternative solution? i'm closing this out for now, please re-open if you wish to continue this discussion
