### ISSUE TITLE
Documentation leading to 404

### ISSUE THREAD

**Issue by denisbetsi** [mesosphere/mesos-dns#420]
http://mesosphere.github.io/mesos-dns/resources.html   references 

> Step-by-step tutorial on deploying Mesos-DNS on a Mesosphere

That leads to 404

**Comment by jdef** [comment]
Looks like we should be linking to http://mesosphere.github.io/mesos-dns/docs/tutorial.html instead of http://mesosphere.github.io/mesos-dns/docs/tutorial-gce.html
