### ISSUE TITLE
Unknown http.Client field 'Timeout' in struct literal

### ISSUE THREAD

**Issue by Protosac** [mesosphere/mesos-dns#424]
Ubuntu 14.10

When I run: `go get -u github.com/exercism/cli/exercism` I get this error. I saw a few older tickets reporting the same thing, but there was no clear solution suggested to resolve this. Anyone know what causes this?

**Comment by jdef** [comment]
you're probably using a version of Go that's older than what the codebase wants.

**Comment by Protosac** [comment]
It was a fresh install of Go, using instructions from the website. No prior installations. I never figured out this error but I have no new information to add. Thanks any way.
