### ISSUE TITLE
Task name crashes Mesos-DNS

### ISSUE THREAD

**Issue by sargun** [mesosphere/mesos-dns#432]
If you start a marathon app named `hello------------------------------------------------------------------------------------------------------------------------------f` it crashes mesos-dns. This is due to the creativity involved in the labels.trimCut function. 

@jdef I propose we simplify this function. I say we make it trims the left characters, and then it trims the right characters, and if it is still too long, it just truncates it.

**Comment by drewkerrigan** [comment]
@sargun can this be closed?
