### ISSUE TITLE
DNS name differences on 0.27 vs 0.28

### ISSUE THREAD

**Issue by frosenberg** [mesosphere/mesos-dns#434]
I'm seeing differences in the generated DNS names between mesos 0.27 and 0.28? 

For example: my service is called `classifier-service.myorg` (`myorg` is the group) in marathon

When I query mesos-dns on a mesos 0.27 deployment I see this:
`classifier-service-myorg.marathon.mesos`

When I do the same on 0.28, I see this:
`classifier-service.myorg.marathon.mesos` (not the . instead of the - between service and group name). 

Is this intentional? I pretty much renders stable DNS names useless for service discovery.

**Comment by sargun** [comment]
@frosenberg That's really unfortunate! Can you please post the state.json on 0.27 and 0.28?

**Comment by sargun** [comment]
Can you also use the enumerate endpoint with both state.json versions and post the output? The enumerate endpoint is `<host>:<HTTP API port>/v1/enumerate`.

**Comment by frosenberg** [comment]
enumerate endpoint of mesos? I cannot seem to find them.

**Comment by frosenberg** [comment]
These files are huge. Anything in particular you look for so I can extract that?

**Comment by sargun** [comment]
@frosenberg That's a mesos-dns endpoint.

@frosenberg The tasks

**Comment by maoxianquan** [comment]
Hi, I have got the same issue here. The difference between two versions is 0.28 would have following structure in the state json:

discovery: {
name: "xxx.xxxx.xxxx",
ports: {
ports: [
{
number: 31960,
protocol: "tcp"
}
]
},
visibility: "FRAMEWORK"
},

the content in the name fields seems used by Mesos-DNS as the task records.

**Comment by maoxianquan** [comment]
Find the reason:

In https://github.com/mesosphere/mesos-dns/blob/master/records/generator.go line 92,  the mesos-dns would use the discovery info as the first priority. So please check why mesos made this information of discovery automatic and how to configure it before start the task.

**Comment by frosenberg** [comment]
Looks to me the real reason is further down:
https://github.com/mesosphere/mesos-dns/blob/master/records/generator.go#L501

**Comment by karthimohan** [comment]
Ran into the same issue. Upgraded Mesos from 0.26.1 to 0.28.2 and ran into this DNSlookup issue. Running Mesos-DNS v0.5.0. Would appreciate if you can let us know any timeline for this fix?

**Comment by sargun** [comment]
Can you just not set DiscoveryInfo on the task?

**Comment by karthimohan** [comment]
@sargun Can you tell me how I can set this option? I dont see this as a configuration option in Mesos documentation. All these tasks are launched from Marathon framework.

**Comment by sargun** [comment]
@karthimohan You should be able to use an older version of Marathon that doesn't set DiscoveryInfo at all, then upgrade your mesos, then change your mesos DNS names, then upgrade Marathon

**Comment by frosenberg** [comment]
@sargun I'm also confused about how to not set DiscoveryInfo.

**Comment by jdef** [comment]
mesos-dns should generate both types of names: those that include `.` and `-` as per https://github.com/mesosphere/mesos-dns/blob/a32855c34ea55d09302226190dd03796d1a63dc1/records/generator.go#L418

at some point we'll drop legacy support for DiscoveryInfo names, meaning that the `.` form will no longer be generated. Please plan accordingly.
