### ISSUE TITLE
Support SSL-enabled Mesos

### ISSUE THREAD

**Issue by micahhausler** [mesosphere/mesos-dns#437]
## What version of the project are you using?

Affects ≤ 0.5.2
## What operating system and processor architecture are you using?

N/A
## What did you do?

Built mesos with SSL support, ran mesos-dns with config that looks like:

```
{
  "zk": "zk://192.168.99.100:2181/mesos",
  "masters": ["192.168.99.100:5050"],
  "stateTimeoutSeconds": 300,
  "refreshSeconds": 60,
  "ttl": 60,
  "domain": "mesos",
  "ns": "ns1",
  "port": 53,
  "resolvers": ["8.8.8.8"],
  "timeout": 5,
  "listener": "0.0.0.0",
  "SOAMname": "ns1.mesos",
  "SOARname": "root.ns1.mesos",
  "SOARefresh": 60,
  "SOARetry":   600,
  "SOAExpire":  86400,
  "SOAMinttl": 60,
  "dnson": true,
  "httpon": true,
  "httpport": 8123,
  "externalon": true,
  "recurseon": true,
  "IPSources": ["mesos", "host"],
  "EnforceRFC952": false,
  "EnumerationOn": true
}
```
## What did you expect to see?

Mesos-dns work with SSL-enabled Mesos
## What did you see instead?

```
VERY VERBOSE: 2016/05/23 18:05:30 main.go:88: Starting master detector for ZK  zk://192.168.99.100:2181/mesos
2016/05/23 18:05:30 Connected to 192.168.99.100:2181
2016/05/23 18:05:30 Authenticated: id=95946452203339776, timeout=40000
VERY VERBOSE: 2016/05/23 18:05:31 masters.go:47: Updated leader:  &MasterInfo{Id:*3fa53ab7-5264-4cd4-8097-3a4550a5e1e2,Ip:*1684252864,Port:*5050,Pid:*master@192.168.99.100:5050,Hostname:*192.168.99.100,Version:*0.28.1,Address:&Address{Hostname:*192.168.99.100,Ip:*192.168.99.100,Port:*5050,XXX_unrecognized:[],},XXX_unrecognized:[],}
VERY VERBOSE: 2016/05/23 18:05:31 main.go:76: new masters detected: [192.168.99.100:5050]
VERY VERBOSE: 2016/05/23 18:05:31 generator.go:153: Zookeeper says the leader is:  192.168.99.100:5050
VERY VERBOSE: 2016/05/23 18:05:31 generator.go:239: reloading from master 192.168.99.100
ERROR: 2016/05/23 18:05:31 generator.go:211: Get http://192.168.99.100:5050/master/state.json: read tcp 192.168.99.100:5050: connection reset by peer
ERROR: 2016/05/23 18:05:31 generator.go:124: no master
ERROR: 2016/05/23 18:05:31 resolver.go:156: Warning: Error generating records: no master; keeping old DNS state
VERY VERBOSE: 2016/05/23 18:05:31 generator.go:162: Warning: Zookeeper is wrong about leader
VERY VERBOSE: 2016/05/23 18:05:31 logging.go:75: {MesosRequests:0 MesosSuccess:0 MesosNXDomain:0 MesosFailed:0 NonMesosRequests:0 NonMesosSuccess:0 NonMesosNXDomain:0 NonMesosFailed:0 NonMesosForwarded:0}
VERY VERBOSE: 2016/05/23 18:05:31 masters.go:56: Updated masters:  [&MasterInfo{Id:*3fa53ab7-5264-4cd4-8097-3a4550a5e1e2,Ip:*1684252864,Port:*5050,Pid:*master@192.168.99.100:5050,Hostname:*192.168.99.100,Version:*0.28.1,Address:&Address{Hostname:*192.168.99.100,Ip:*192.168.99.100,Port:*5050,XXX_unrecognized:[],},XXX_unrecognized:[],}]
```
## Additional info

Currently the scheme is assumed to be `http` : [`generator.go`](https://github.com/mesosphere/mesos-dns/blob/9b4c235f7d58569f032d26cc82dba00646f9dc30/records/generator.go#L217)

It seems either an additional configuration flag should be enabled, or the scheme should be included in the list of master addresses. 

Any thoughts on which approach would be better here?

**Comment by sargun** [comment]
@alberts Does your team have a fix in progress?

**Comment by micahhausler** [comment]
@sargun Any update on this?

**Comment by jdef** [comment]
@micahhausler yes, we do support SSL + authentication with JWT. the authn method isn't pluggable at this point. https://github.com/mesosphere/mesos-dns/blob/master/httpcli/doer.go

PRs welcome :)

**Comment by jdef** [comment]
#448

**Comment by timcharper** [comment]
` Zookeeper is wrong about leader` is exactly the error I got.

**Comment by timcharper** [comment]
@micahhausler I've pushed up a build you can use. https://github.com/vivint-smarthome/mesos-dns/releases/tag/v0.5.3-vivint-2  ; docs here https://github.com/vivint-smarthome/mesos-dns/blob/auth/docs/docs/configuration-parameters.md

The params are going to change, but you could at least get things running if you like.

**Comment by sargun** [comment]
We haven't done a release of this yet, but you can use an artifact from circle-ci for master. 

If you click on the Circle-CI "Passing" button on our README.md, and click on the latest green master, then click on artifacts, you should reach this page: https://circleci.com/gh/mesosphere/mesos-dns/734#artifacts

**Comment by timcharper** [comment]
Super neat, @sargun ! thank you!

**Comment by wrouesnel** [comment]
+1 for getting this into a release as soon as possible, we too would like to run this (we'll use the CI artifact for now).

**Comment by jdef** [comment]
looks like release v0.6.0 ships w/ SSL and authn for mesos
