### ISSUE TITLE
Mesos-DNS: overwrites all containers' /etc/hosts file

### ISSUE THREAD

**Issue by adityats** [mesosphere/mesos-dns#438]
Mesos-DNS overwrites /etc/hosts file on every container on Mesos Agent Nodes regardless of whether the container was spun up by Mesos/Marathon. This leads to other containers which rely on /etc/hosts for external connectivity to become flaky.

Ideally Mesos-DNS should touch only the containers it knows of or was responsible for.

**Comment by sargun** [comment]
I don't believe this is the case. Pretell, what leads you to believe that Mesos-DNS is rewriting /etc/hosts on every node?

**Comment by adityats** [comment]
The file /etc/hosts originally had a couple of lines that looked like:

172.17.0.4          <container-id> # Filled by docker
10.122.6.140      node1.controller.local

Now it looks like as below. We had a DCOS setup without Mesos-DNS and that worked just fine and docker versions are the same across our cluster.

10.122.19.180   mesos-dbee6a67-e528-42a4-a093-69fd5fa658d9-S46-40939e9b-ba52-48c8-bfc8-
66e345080287
10.122.19.180   mesos-dbee6a67-e528-42a4-a093-69fd5fa658d9-S46-40939e9b-ba52-48c8-bfc8-
66e345080287.bridge
10.122.19.181   mesos-dbee6a67-e528-42a4-a093-69fd5fa658d9-S46-7247fe1e-117a-491d-b530-
193920c6e2be
10.122.19.181   mesos-dbee6a67-e528-42a4-a093-69fd5fa658d9-S46-7247fe1e-117a-491d-b530-
193920c6e2be.bridge
10.122.19.182   mesos-dbee6a67-e528-42a4-a093-69fd5fa658d9-S46-a82ec6de-bbce-48e6-afc8-
90a59e4470bb
10.122.19.182   mesos-dbee6a67-e528-42a4-a093-69fd5fa658d9-S46-a82ec6de-bbce-48e6-afc8-
90a59e4470bb.bridge
10.122.19.183   mesos-dbee6a67-e528-42a4-a093-69fd5fa658d9-S46-4709225e-cd5d-4bb2-bfea-
a88011a56761
10.122.19.183   mesos-dbee6a67-e528-42a4-a093-69fd5fa658d9-S46-4709225e-cd5d-4bb2-bfea-
a88011a56761.bridge
10.122.19.184   mesos-dbee6a67-e528-42a4-a093-69fd5fa658d9-S46-59c22902-4e46-4feb-9a22-
60c751d56c9e
10.122.19.184   mesos-dbee6a67-e528-42a4-a093-69fd5fa658d9-S46-59c22902-4e46-4feb-9a22-
60c751d56c9e.bridge
10.122.19.185   mesos-dbee6a67-e528-42a4-a093-69fd5fa658d9-S46-0adee304-0f42-43b6-a509-
eb9e8519550a
10.122.19.185   mesos-dbee6a67-e528-42a4-a093-69fd5fa658d9-S46-0adee304-0f42-43b6-a509-
eb9e8519550a.bridge
10.122.19.186   mesos-dbee6a67-e528-42a4-a093-69fd5fa658d9-S46-31237fd6-1ce4-434c-9cc2-
fc3eb786d0fa
10.122.19.186   mesos-dbee6a67-e528-42a4-a093-69fd5fa658d9-S46-31237fd6-1ce4-434c-9cc2-
fc3eb786d0fa.bridge
10.122.19.187   mesos-dbee6a67-e528-42a4-a093-69fd5fa658d9-S46-cfb2438e-78af-4dc6-9287-
e744ebbe5bc0
10.122.19.187   mesos-dbee6a67-e528-42a4-a093-69fd5fa658d9-S46-cfb2438e-78af-4dc6-9287-
e744ebbe5bc0.bridge
10.122.19.188   mesos-dbee6a67-e528-42a4-a093-69fd5fa658d9-S46-9c57c5b7-4911-4106-9560-
76b2362b4d0e
10.122.19.188   mesos-dbee6a67-e528-42a4-a093-69fd5fa658d9-S46-9c57c5b7-4911-4106-9560-
76b2362b4d0e.bridge
10.122.19.189   mesos-dbee6a67-e528-42a4-a093-69fd5fa658d9-S46-a12c342f-d58a-4937-bb1e-
5c65753ecdfa

**Comment by sargun** [comment]
I'm unsure of how Mesos-DNS could write `/etc/hosts` to the agents, given that it's not even running on them. My colleague tells me that Docker is sometimes known to manipulate `/etc/hosts`. 

I recommend using [ftrace](https://www.kernel.org/doc/Documentation/trace/ftrace.txt) to determine the process writing the file.

**Comment by jgarcia-mesosphere** [comment]
We're pretty sure that `mesos-dns` doesn't do this, but we do know that [Docker can manage /etc/hosts](https://docs.docker.com/engine/userguide/networking/default_network/configure-dns/) and in addition, if you're using `dcos-vagrant` we will inject the cluster machine's names into `/etc/hosts` on your behalf (which would then be consumed by Docker).

Let us know if this helps.

**Comment by sargun** [comment]
```
sudo su -
cd /sys/kernel/debug/tracing
echo function > current_tracer
# Your function may be different, use: 
# grep -i do_sys_open available_filter_functions
# to determine it

echo do_sys_open > set_ftrace_filter
echo 1 > tracing_on
# Once you see the file change
echo 0 > tracing_off

cat trace #-> lists all programs that called do_sys_open
 
```

**Comment by adityats** [comment]
We are running docker version 1.8.3 on CoreOS, not sure if that's an issue but I distinctly remember using 1.6 docker version and not seeing this issue then.

@jgarcia-mesosphere /etc/hosts is not a static file, we cannot use --hostname option during container create. It is actively updated by the container. 

@sargun I will try debugging with ftrace.

**Comment by adityats** [comment]
After upgrading docker to 1.9.1, things seemed to be resolved. Thanks for the tips!
