### ISSUE TITLE
build broken because of new jwt version

### ISSUE THREAD

**Issue by lcjlcj** [mesosphere/mesos-dns#447]
github.com/mesosphere/mesos-dns/httpcli
../github.com/mesosphere/mesos-dns/httpcli/doer.go:72: invalid operation: token.Claims["uid"] (type jwt.Claims does not support indexing)
../github.com/mesosphere/mesos-dns/httpcli/doer.go:73: invalid operation: token.Claims["exp"] (type jwt.Claims does not support indexing)
The command '/bin/sh -c cd /go/src/mesos-dns && go get' returned a non-zero code: 2

This is probably because jwt upgraded and broke API.

**Comment by alberts** [comment]
@lcjlcj we switched to govendor. You should be able to build with

go get github.com/kardianos/govendor
govendor install -v +local

@sargun We should update the docs.

**Comment by sargun** [comment]
Should be fixed.
