### ISSUE TITLE
Support Mesos Principal Basic HTTP Authentication

### ISSUE THREAD

**Issue by timcharper** [mesosphere/mesos-dns#448]
`mesos-dns` does not support HTTP authentication. If `http_authentication` is turned on for mesos-master, and `mesos` `1.0.0` is running, then the request for mesos master state is denied.

**Comment by timcharper** [comment]
I'm working on a patch

**Comment by sargun** [comment]
We support using JWTs: https://github.com/mesosphere/mesos-dns/commit/59f43a3858ff5943a8950936de79d540b490dd04

**Comment by timcharper** [comment]
@sargun okay; how is it used?

**Comment by timcharper** [comment]
It looks like that code is for authorizing against Amazon's IAM, am I mistaken? I didn't see any documentation for it, and saw "IAM", so assumed as much.

**Comment by sargun** [comment]
If you have an Authorizer module that takes JWTs, you can set the JWT ID in the config, and Mesos-DNS will submit them to Mesos. We can extend this to take arbitrary tokens.

**Comment by timcharper** [comment]
I'm not really experienced with JWT's, so I'll smile and nod here. Is this the direction we're taking authentication for all things mesos? Is the principal / secret authentication approach being deprecated?

**Comment by timcharper** [comment]
(I know you've been swamped and want to make sure you noticed that I've done the work and have submitted a pull request for this feature)

**Comment by sargun** [comment]
It's pluggable. In the PR, it'd be nice if it followed roughly the same path, and you had an enum in the config that said use auth mechanism X or Y, but I think that it's a good idea.

**Comment by timcharper** [comment]
Great, I'll take a stab at it. Let's move the discussion to the pull request? https://github.com/mesosphere/mesos-dns/pull/449

**Comment by chjhaijiang** [comment]
@sargun, can you please help to give the instructions about your idea here?
===
If you have an Authorizer module that takes JWTs, you can set the JWT ID in the config, and Mesos-DNS will submit them to Mesos. We can extend this to take arbitrary tokens.
