### ISSUE TITLE
help~ unrecognized import path "golang.org/x/net/context" 

### ISSUE THREAD

**Issue by Aiolia1992** [mesosphere/mesos-dns#451]
I'm installing mesos-dns in my centos7. I'm according the process of mesos official review just like https://open.mesosphere.com/advanced-course/building-and-running-mesos-dns/.
But in this way <go get github.com/mesosphere/mesos-dns> , i met a mistake that <package golang.org/x/net/context: unrecognized import path "golang.org/x/net/context">. I do not konw how to solve it. In other way I use <go get github.com/golang/net > to down the net folder in <$GOPATH/src/github.com/golang/> . Then i copy it to  <$GOPATH/src/golang.org/x/>. Finally, I continue to use <go get github.com/mesosphere/mesos-dns>, but met another mistake that < github.com/mesosphere/mesos-dns/httpcli/iam
../../mesosphere/mesos-dns/httpcli/iam/iam.go:42: invalid operation: token.Claims["uid"] (type jwt.Claims does not support indexing)
../../mesosphere/mesos-dns/httpcli/iam/iam.go:43: invalid operation: token.Claims["exp"] (type jwt.Claims does not support indexing)>
I doubt whether your code has bug cuz last commit. Please help me, thanks!

**Comment by sargun** [comment]
Please use the official releases:
https://github.com/mesosphere/mesos-dns/releases
@joel-hamill Can we point people in this direction?

**Comment by joel-hamill** [comment]
@sargun the advanced mesos course content is no longer actively updated. however, you can make a PR to: https://github.com/mesosphere/open-docs/tree/master/advanced-course

**Comment by Aiolia1992** [comment]
@joel-hamill  hello, I have try your link address, but it hints 404 not found. It has been deteled?

**Comment by joel-hamill** [comment]
@Aiolia1992 sorry for the delay. i have re-opened the repo to the public: https://github.com/mesosphere/open-docs/tree/master/advanced-course. thanks!
