### ISSUE TITLE
Migrate Mesos-DNS repo to DC/OS organisation on GitHub

### ISSUE THREAD

**Issue by ssk2** [mesosphere/mesos-dns#453]
Since Mesos DNS is part of DC/OS, this repo should live there :).

**Comment by alberts** [comment]
Need to make sure we don't break people who might have vendored/imported part of the Mesos-DNS Go code.

**Comment by Difrex** [comment]
What will be the new url for mesos-dns code?

**Comment by ssk2** [comment]
@Difrex: something like https://github.com/dcos/mesos-dns

**Comment by alberts** [comment]
Deferring this.
