### ISSUE TITLE
Fix build instructions in README.md

### ISSUE THREAD

**Issue by timcharper** [mesosphere/mesos-dns#456]
The README.md mentions that godeps should be used to build the project; however, the required deps file `Godeps/Godeps.json` seems to be missing.

**Comment by jdef** [comment]
Looks like a documentation error. Deps should be vendored in `vendor/` now

**Comment by timcharper** [comment]
Okay; I'm still unclear of what commands to use to update these dependencies. I tried running `godeps` and it gives fantastic errors. However, `go install` appears to use these; has godeps been deprecated?

**Comment by timcharper** [comment]
@jdef can you point me in the right direction? I have no idea what to do. I can send a PR for this and also one for #457 if this is solved.

**Comment by sargun** [comment]
@timcharper Look at #463. I like that route a bit.

**Comment by jdef** [comment]
We're using govendor to manage deps, not Godeps; vendored code is all in the `vendor/` directory
