### ISSUE TITLE
Release 0.5.3

### ISSUE THREAD

**Issue by sargun** [mesosphere/mesos-dns#466]
How do y'all feel about prepping a release for 0.5.3?
@jdef @drewkerrigan @alberts 

@alberts -- Can you test the IAM stuff -- I'm not sure where the secret is being set in the config file?

**Comment by timcharper** [comment]
Since releases are infrequent I'd really like a fix applied for #457 - Forwarded truncated DNS responses get extra truncated.

**Comment by drewkerrigan** [comment]
It would be nice to get #467 from @timcharper. #463 would be nice as well, but I think it changes the build process enough to hold off until the next point release at least. 

Other than that, 👍 from me

**Comment by sargun** [comment]
I cut rc2: https://circleci.com/gh/mesosphere/mesos-dns/809#artifacts

@drewkerrigan

**Comment by sargun** [comment]
I would like to cut the Mesos-DNS release in the next 24 hours. If anyone believe we shouldn't, please let me know. 

CC: @jdef @timcharper @drewkerrigan @bradbeam

The following PRs don't seem ready yet:
* https://github.com/mesosphere/mesos-dns/pull/464
* https://github.com/mesosphere/mesos-dns/pull/470
* https://github.com/mesosphere/mesos-dns/pull/463

Although https://github.com/mesosphere/mesos-dns/pull/441 looks close to ready, I think that given we're releasing a stable release in ~days, it seems kinda high risk to put in. We're planning the next GA in about a month, and I think it makes a lot of sense to get this in over the next month.

**Comment by timcharper** [comment]
Hey @sargun ; I agree wrt high risk right now (although We are running an earlier version of the #441 patch in production right now). Getting a solid stable release out first will be good. Once it goes out, I'll rebase the patch on top of it and deploy it to our beta environments for testing, and then ultimately to our production environments, and will report how it goes.

**Comment by jdef** [comment]
I'd check w/ dc/os security team that #470 can wait. Looks like it might have some bits that they need/want for authn

**Comment by bradbeam** [comment]
No concerns about #463 since it seemed to already be communicated that we'd want to wait until the next release. 
This also goes for #464 since this hasn't really reviewed at all.

**Comment by sargun** [comment]
@vespian Mind commening about #470?

**Comment by jdef** [comment]
if we don't need the authn changes then let's punt on #470
