### ISSUE TITLE
`godep: No Godeps found (or in any parent directory)`

### ISSUE THREAD

**Issue by rmros** [mesosphere/mesos-dns#471]
i follow these steps

`$ mkdir ~/go

$ export GOPATH=$HOME/go

$ export PATH=$PATH:$GOPATH/bin

$ go get github.com/tools/godep

$ go get github.com/mesosphere/mesos-dns

$ cd $GOPATH/src/github.com/mesosphere/mesos-dns

$ godep go build . `

but 
after --> godep go build .
get this message : 

`godep: No Godeps found (or in any parent directory)`

**Comment by jdef** [comment]
we're using govendor now to manage properly vendored deps. you should no
longer need godep.

**Comment by rmros** [comment]
mr @jdef thanks 
after
`$ mkdir ~/go

$ export GOPATH=$HOME/go

$ export PATH=$PATH:$GOPATH/bin

$ go get -u github.com/kardianos/govendor

$ go get github.com/mesosphere/mesos-dns

$ cd $GOPATH/src/github.com/mesosphere/mesos-dns`

what is command instead of `godep go build .` ?

**Comment by jdef** [comment]
if you're using a recent release of go then you should be able to `go build
.`

**Comment by rmros** [comment]
yes i use go 1.6
thanks mr jdef
