### ISSUE TITLE
Ns namaserver's A record is not returned

### ISSUE THREAD

**Issue by stevenlee87** [mesosphere/mesos-dns#501]
dig ns1.mesos.test.net

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7 <<>> ns1.mesos.test.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 6850
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ns1.mesos.test.net.        IN      A                    <---- A record is not returned!!!

;; AUTHORITY SECTION:
ns1.mesos.test.net. 5 IN    SOA     ns1.mesos.test.net. root.ns1.mesos.test.net. 1498640947 60 600 86400 5

config.json:
  "refreshSeconds": 5,
  "ttl": 5,
  "domain": "mesos.test.net",
  "port": 53,
  "resolvers": ["1.1.1.1","2.2.2.2"],
  "timeout": 5, 
  "httpon": true,
  "dnson": true,
  "httpport": 8123,
  "externalon": true,
  "listener": "10.172.190.165",
  "SOAMname": "ns1.mesos.test.net",
  "SOARname": "root.ns1.mesos.test.net",
  "SOARefresh": 60,
  "SOARetry":   600,
  "SOAExpire":  86400,
  "SOAMinttl": 60,
  "IPSources": ["host", "mesos", "netinfo"]

**Comment by gpaul** [comment]
Interesting. Could you give a bit more detail about your cluster, what output you'd expect, and why?

**Comment by stevenlee87** [comment]
mesos 1.3
marathon 1.4.5
msos-dns 0.6.0

The result I expect is:
dig ns1.mesos.test.net

; <<>> DiG 9.3.6-P1-RedHat-9.3.6-4.P1.el5 <<>> ns1.mesos.test.net
;; global options:  printcmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15279
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;ns1.mesos.test.net.   IN      A

;; ANSWER SECTION:
ns1.mesos.test.net. 60 IN      A       10.10.10.26  <---- A record is returned!!!

;; Query time: 12 msec
;; SERVER: 218.30.118.6#53(1.1.1.1)
;; WHEN: Mon Jul  3 18:33:14 2017
;; MSG SIZE  rcvd: 61

**Comment by jdef** [comment]
suspect that passing the `rname` is wrong here, and that we should be passing the `mname` instead: https://github.com/mesosphere/mesos-dns/blob/9d21ea6de38bd371e34bde196ceaee94cdac8a2c/records/generator.go#L187

i'm not crazy about the defaults in our config file, but that's a separate issue

**Comment by jdef** [comment]
the other weird thing is that SOA `mname` is supposed to reference a primary master. But running mesos-dns on multiple hosts w/ the default config probably results in 3 different primary masters being set. And that feels wrong.

Docs:
https://www.ripe.net/publications/docs/ripe-203

> 4.1 The MNAME Value
>
>The DNS specification explicitly states that the primary master server be named here. The value must be determined and used. Especially it is a mistake to repeat the zone name here, unless this also leads to a valid address of the primary master.
