### ISSUE TITLE
nslookup in docker container failed!

### ISSUE THREAD

**Issue by junneyang** [mesosphere/mesos-dns#527]
slave node:
ping helloworld.marathon.mesos------Ok

slave docker app:
ping helloworld.marathon.mesos------FAIL
nslookup: can't resolve '(null)': Name does not resolve

**Comment by jdef** [comment]
Can you provide more context re: your environment? See https://github.com/mesosphere/mesos-dns/blob/master/CONTRIBUTING.md#issues

**Comment by junneyang** [comment]
@jdef 

mesos: 1.7.0
marathon:  1.7.50

helloworld app:
`{
  "id": "/helloworld",
  "cmd": "python -m SimpleHTTPServer $PORT",
  "cpus": 1,
  "mem": 128,
  "disk": 0,
  "instances": 2,
  "acceptedResourceRoles": [
    "*"
  ],
  "healthChecks": [
    {
      "gracePeriodSeconds": 300,
      "ignoreHttp1xx": false,
      "intervalSeconds": 60,
      "maxConsecutiveFailures": 3,
      "path": "/",
      "portIndex": 0,
      "protocol": "HTTP",
      "ipProtocol": "IPv4",
      "timeoutSeconds": 20,
      "delaySeconds": 15
    }
  ],
  "portDefinitions": [
    {
      "port": 10000,
      "protocol": "tcp"
    }
  ]
}`

nginx-docker app:
`{
  "id": "/helloworld-nginx",
  "cmd": null,
  "cpus": 1,
  "mem": 128,
  "disk": 0,
  "instances": 1,
  "constraints": [
    [
      "hostname",
      "CLUSTER",
      "10.240.185.53"
    ]
  ],
  "acceptedResourceRoles": [],
  "container": {
    "type": "DOCKER",
    "docker": {
      "forcePullImage": false,
      "image": "nginx:1.15-alpine",
      "parameters": [],
      "privileged": false
    },
    "volumes": [
      {
        "containerPath": "/usr/share/nginx/html",
        "hostPath": "/opt/paas/data/nginx",
        "mode": "RO"
      }
    ],
    "portMappings": [
      {
        "containerPort": 80,
        "hostPort": 0,
        "labels": {},
        "protocol": "tcp",
        "servicePort": 10001
      }
    ]
  },
  "healthChecks": [
    {
      "gracePeriodSeconds": 300,
      "ignoreHttp1xx": false,
      "intervalSeconds": 60,
      "maxConsecutiveFailures": 3,
      "path": "/",
      "portIndex": 0,
      "protocol": "HTTP",
      "ipProtocol": "IPv4",
      "timeoutSeconds": 20,
      "delaySeconds": 15
    }
  ],
  "networks": [
    {
      "mode": "container/bridge"
    }
  ],
  "portDefinitions": []
}`

on slave node:
nslookup helloworld.marathon.mesos------OK
![tim 20180927215647](https://user-images.githubusercontent.com/6802322/46150968-5e73bf80-c2a0-11e8-9bfe-2212691c6b17.png)

in nginx-docker:
nslookup helloworld.marathon.mesos------FAIL
![tim 20180927215908](https://user-images.githubusercontent.com/6802322/46151088-9975f300-c2a0-11e8-9f8f-a4aeebe143ad.png)

mesos-dns:v0.6.0
config.json:
`{
	"zk": "zk://yangjun-centos7-4-0001.novalocal:2181,yangjun-centos7-4-0002.novalocal:2181,yangjun-centos7-4-0003.novalocal:2181/mesos",
	"masters": ["yangjun-centos7-4-0001.novalocal:5050", "yangjun-centos7-4-0002.novalocal:5050", "yangjun-centos7-4-0003.novalocal:5050"],
	"refreshSeconds": 60,
	"ttl": 60,
	"domain": "mesos",
	"port": 53,
	"resolvers": ["8.8.8.8"],
	"timeout": 5,
	"httpon": true,
	"dnson": true,
	"httpport": 8123,
	"externalon": true,
	"listener": "0.0.0.0",
	"SOAMname": "felix.mesos",
	"SOARname": "admin.felix.mesos",
	"SOARefresh": 60,
	"SOARetry": 600,
	"SOAExpire": 86400,
	"SOAMinttl": 60,
	"IPSources": ["netinfo", "mesos", "host"]
}
`


thanks for your help!

**Comment by jdef** [comment]
on which node is mesos-dns running? have you tried enabling verbose logging
for mesos-dns to observe what it's doing?

**Comment by junneyang** [comment]
mesos-dns runs on 10.240.185.53

in container dig says: 
![image](https://user-images.githubusercontent.com/6802322/46154496-dee9ee80-c2a7-11e8-81c3-051d4140c2ab.png)

why 172.17.0.1#53 ?
172.17.0.1 is address of docker0

**Comment by jdef** [comment]
can you include the output of `docker version`?

**Comment by junneyang** [comment]
@jdef 
`docker version 
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
`
![image](https://user-images.githubusercontent.com/6802322/46154867-9da60e80-c2a8-11e8-8c61-722f094786ad.png)

**Comment by junneyang** [comment]
@jdef 
Is this problem related to the iptables?
it seems that the docker0 reply the dig request directly, not the mesos-dns

**Comment by jdef** [comment]
I see you're trying to use docker bridge-mode networking. Are you using the default docker bridge, as auto-configured by docker OOTB? If not, how have you configured the default bridge network for docker?

Docker networking is a bit funny. See https://docs.docker.com/network/bridge/#connect-a-container-to-the-default-bridge-network

As an aside, consider changing your `IPSources` to `["host", "netinfo"]` unless you're sure you really want what you have.

**Comment by junneyang** [comment]
@jdef 
solved!

![image](https://user-images.githubusercontent.com/6802322/46157169-bcf36a80-c2ad-11e8-8490-442a0e67b09a.png)

i changed the listener: 0.0.0.0   to   10.240.185.53
problem solved

thanks very much!

**Comment by jdef** [comment]
Glad you got it working. Closing this out as resolved.
