### ISSUE TITLE
mesos-DNS

### ISSUE THREAD

**Issue by devops083** [mesosphere/mesos-dns#528]
dig nginx.marathon.mesos
when try this it showing container ips not showing slave ips where containers was deployed...

**Comment by jdef** [comment]
You probably want to change the default value of `IPSources` in your config. See https://github.com/mesosphere/mesos-dns/blob/ca483fa2f6b6f8ea5707449abbf065f8946bcb82/docs/docs/configuration-parameters.md#L110

**Comment by devops083** [comment]
hey @jdef thnx for your response, IPSources default value is ["netinfo", "mesos", "host"]
other than netinfo, what are possible values we can prefer...?

**Comment by devops083** [comment]
@jdef 
So I have to change the order of IPSources?

**Comment by jdef** [comment]
oops, I mean "host"

**Comment by devops083** [comment]
@jdef 
Its working thanks a lot  :)
