### ISSUE TITLE
Golang 1.11 LookupSRV can't resolve mesos-dns compressed responses.

### ISSUE THREAD

**Issue by 2easy** [mesosphere/mesos-dns#530]
Hi, with golang 1.11 I can't make it to resolve SRV records from mesos-dns. After some debugging I have discovered that golang does not allow for compressed SRV records (error message "compressed name in SRV resource data").

```package main

import (
	"log"
	"net"
)

func main() {
	_, _, err := net.LookupSRV("", "", "_my_service._udp.marathon.mesos.")
	log.Println(err)
}
```

Related issue: https://github.com/golang/go/issues/27546

**Comment by jdef** [comment]
Looks like we need to bump a dependency, this appears to have patched a while ago: https://github.com/miekg/dns/commit/00b8eaaab9411e1ff61e5030ef7e58bed412ad2a

**Comment by 2easy** [comment]
Yup, that's it.
