### ISSUE TITLE
marthon 1.7 mesos-dns default json

### ISSUE THREAD

**Issue by f1-outsourcing** [mesosphere/mesos-dns#533]
Sorry for asking maybe the obvious I am having a test setup and just upgraded to mesos 1.7 and marathon 1.7. Marathon is now running as uid marathon. And I have probably problems launching the mesos-dns because of the low port 53 in the mesos-dns.json. (If I change it to 2053 it deploys)

How should I resolve this issue? I guess I need to have the 53 port.

**Comment by j3k0** [comment]
@f1-outsourcing did you found a solution?

**Comment by f1-outsourcing** [comment]
yes run as root, all ports below 1024 require it, otherwise you need to do something with port forwarding etc etc.


```
{
  "id": "mesos-dns",
  "user": "root",
  "cmd": "/usr/local/sbin/mesos-dns -config=/etc/mesos-dns/config.json",
  "cpus": 0.2,
  "mem": 256,
  "instances": 1,
  "constraints": [["hostname","CLUSTER","m01.local"]],
  "acceptedResourceRoles": ["*"],
  "healthChecks": [
    {
      "protocol": "MESOS_TCP",
      "port": 8123,
      "gracePeriodSeconds": 120,
      "intervalSeconds": 10,
      "timeoutSeconds": 10,
      "maxConsecutiveFailures": 3
    }
  ]
}
```
