### ISSUE TITLE
mesos 1.8+ unsupported

### ISSUE THREAD

**Issue by vixns** [mesosphere/mesos-dns#538]
Mesos 1.8+ no longer supports `/master/state.json` endpoint (404 response), we must use `/master/state` instead.

**Comment by MyckeTap** [comment]
Hello, I have upgraded mesos to 1.8.0 and now mesos-dns outputs an error related to state.json. 
How could I overcome it? I don't know where to change state.json to state?
-----------------------------------------------------
ERROR: 2019/05/27 10:19:18 generator.go:267: invalid character 'N' after top-level value
ERROR: 2019/05/27 10:19:18 generator.go:210: Failed to fetch state.json from leader. Error:  invalid character 'N' after top-level value
ERROR: 2019/05/27 10:19:18 generator.go:173: Failed to fetch state.json. Error:  No more masters to try
ERROR: 2019/05/27 10:19:18 resolver.go:162: Warning: Error generating records: No more masters to try; keeping old DNS state
-----------------------------------------------------

**Comment by vixns** [comment]
fixed by https://github.com/mesosphere/mesos-dns/commit/a274e0d17df5abb86d931c21875207849302dd9f

**Comment by MyckeTap** [comment]
thanks, I got it and already even tested it - works as a charm! Thanks, again!
