### ISSUE TITLE
make docs better indicate minimally successful configuration

### ISSUE THREAD

**Issue by gpolyn** [mesosphere/mesos-dns#64]
On a four-node GCE mesos cluster (generated from resources at google.mesosphere.com), with a service^ launched with marathon:

   TIME   STATE    RSS     CPU   %MEM          COMMAND          USER                      ID                    
 0:00:01    R    30.91 MB  0.2  61.82  sh -c 'python -m Si...'  root  http.7eebddff-a2fd-11e4-9415-56847afe9799 

...and with the following emulation of the "Getting Started" docs:

* mesos-dns installed on cluster master ("development-3694-553")
* config.json, as follows, where resolvers match nameserver values in master's resolv.conf:
   {
     "masters": ["development-3694-553:5050"],
     "refreshSeconds": 60,
     "ttl": 60,
     "domain": "mesos",
     "port": 53,
     "resolvers": ["169.254.169.254", "10.0.0.1"],
     "timeout": 5
   }
* three slave resolv.conf files begin with eth0 address of master: "nameserver 10.186.82.217"

...and from any slave dig http.marathon.mesos reports "ANSWER: 0."

Can more guidance be offered on succeeding with steps like these? To start, suggest how to confirm that slaves recognize mesos-dns?

^ github.com/mesosphere/marathon/blob/master/examples/PythonSimpleHTTPServer.json

**Comment by kozyraki** [comment]
Thanks for the suggestion Gallagher. We'll provide more documentation soon. 

To verify that Mesos-DNS is accessible and works:
- dig www.google.com
this should provide you with the expected answers and towards the end the server signature should be 
;; SERVER: 10.186.82.217#53(10.186.82.217)
- dig nametask.frameworkname.mesos 
should return an answer assuming you did actually launch a task named "task name" with framework named "frameworkname". 

Given your setup, two suggestions:
- The current version of Marathon launched by elastic mesos registers as "marathon-0.7.6". So, the task name will be taskname.marathon-0.7.6.mesos. I know this is annoying; the upcoming RCs of Marathon fix it. You can also see what records Mesos-DNS generates if you launch it with "-v". 
- Define the "masters" by its internal IP address on GCE.  This should not matter much but it may lead to confusion. 

Hope this helps

**Comment by gpolyn** [comment]
Thanks for your prompt attention, Christos.

Your guidance was immediately useful: none of the slaves as configured find the master nameserver.

I'm not looking for immediate resolution, rather, hoping that something more "hello world-y" will arrive soon, from which I can start fresh.

In any case, here follows what I might expect is the crucial configuration for my setup:

Mesos master (10.186.82.217:5050) has this config.json:

{
  "masters": ["10.186.82.217:5050"],
  "refreshSeconds": 60,
  "ttl": 60,
  "domain": "mesos",
  "port": 53,
  "resolvers": ["169.254.169.254", "10.0.0.1"],
  "timeout": 5
}

...and mesos-dns _may_ be running on the master node:
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp6       0      0 :::53                   :::*                                15529/mesos-dns 

...and the slave resolv.conf files are:

nameserver 10.186.82.217
 nameserver 10.252.212.182
 domain c.sound-bee-823.internal.
search c.sound-bee-823.internal. 733099285469.google.internal. google.internal.
nameserver 169.254.169.254
nameserver 10.0.0.1

...but dig www.google.com results in 

;; Query time: 2 msec
;; SERVER: 169.254.169.254#53(169.254.169.254)
;; WHEN: Fri Jan 23 23:19:56 2015
;; MSG SIZE  rcvd: 12

**Comment by kozyraki** [comment]
Gallagher, I forgot the MOST important thing. If you are running on GCE then you need to unblock port 53. Google blocks it by default. From your gce console, go to (your project) -> instances -> (select a node) -> network (select the image) -> and then add a firewall rule that opens port 53. Should be similar to the one for opening port 22, although you don't have to open it to the whole world.

**Comment by gpolyn** [comment]
Yay,  dig http.marathon-0.7.6.mesos now gives me a reasonable answer.

Here was the (sloppy?) GCE rule:

![screen shot 2015-01-23 at 7 02 15 pm](https://cloud.githubusercontent.com/assets/744660/5884935/75957df2-a332-11e4-9ef6-5a1c7f14d147.png)

**Comment by kozyraki** [comment]
Unless you want to serve DNS traffic for the whole internet, get rid of the
0.0.0.0/0 part

**Comment by gpolyn** [comment]
curbing my ambitions accordingly

![screen shot 2015-01-23 at 7 10 59 pm](https://cloud.githubusercontent.com/assets/744660/5885021/a527a72e-a333-11e4-9523-f8b25eea9428.png)
