### ISSUE TITLE
Support Reverse Lookup

### ISSUE THREAD

**Issue by kensipe** [mesosphere/mesos-dns#67]
mesos-dns does not support reverse lookup.   The following command should return the service name that is registered at that node:

$ dig @$servicehost -x 10.240.214.151

** where $servicehost is the IP of the mesos-dns service.

**Comment by tarnfeld** [comment]
Presumably you would need to return multiple records to describe the many services that might be running on this node? I'm not sure if it's valid for a reverse lookup to return multiple `PTR` record types.

I believe the RFC doesn't explicitly prohibit the use of multiple PTR records for reverse lookups, but there's plenty of [material](https://supernoc.rogerstelecom.net/pdfs/multiple-ptrs.pdf) on the net about why you shouldn't do it.

**Comment by kozyraki** [comment]
I don't particularly like the idea of supporting reverse lookup (through PTR records). In addition to the issues Tom lists above, it is a security concern and an anti-pattern as allows one to query about all tasks running on a specific machine. Other than the Mesos master, that already has this info, I am not sure who else needs it.

**Comment by tarnfeld** [comment]
IMO if you want to embed this information into the DNS system it's worth reading more into the utilities the DNS-SD RFC (6763) spec provides.

**Comment by mindscratch** [comment]
With mesos-dns in place, I'm not able to use cURL and I suspect http libraries would also have issues if I tried to access "http://chronos.marathon.mesos". 

Programmatically, if want to perform a GET request to chronos.marathon.mesos, would I first need to do a DNS query to get the IP address, and then perform the GET?

**Comment by mindscratch** [comment]
@kozyraki my use case is mostly having services that use static configuration files. It would be nice to put in the configuration file "<service>.marathon.mesos". If marathon moves that service to a different node, no configuration changes are required. However, many client applications are not "home grown" so I can't alter how they look up that host. Most likely, those applications expect DNS to resolve properly versus doing a DNS query and then interacting with the service. Does that help?

**Comment by mindscratch** [comment]
@kozyraki with the opening of [this ticket on marathon](https://github.com/mesosphere/marathon/issues/1112), does that mean reverse lookup support will be added to mesos-dns eventually?

**Comment by kozyraki** [comment]
@mindscratch 
The problem with curl is either is a misconfiguration or a bug from our side. You don't need inverse DNS to translate chronos.marathon.mesos to an IP address. Here are some suggestions of things to check:
- have you setup /etc/resolv.conf to point to Mesos-DNS (nameserver <its-ip-address) in all machines involved and in particular the machine that curl executes on? 
- launch Mesos-DNS in verbose mode (-v) and see if Mesos-DNS is actually generating records for the tasks as expected. Does chronos.marathon.mesos actually exist? 
- There can be a 60sec delay between launching a task and getting a DNS record. 
- Once you launch mesos-dns, check if it is actually up and using port 53 (netstat -tulpn | grep 53). 
- In some platforms, eg Google Compute Engine, port 53 is blocked by default. You need to enter a firewall rule that opens it. 
- Curl does not work but does "dig", "nslookup" or "host" commands work? 
If nothing else works, we can get on a screenshare and dig into this together. 

Separately of this, let's talk about PTR records. What is the use case for them in your case? Remember that Mesos-DNS will allow you to translate the IP address back to a hostname. It will just not give you a translation from IP address to the "hostnames" generated for tasks.

**Comment by mindscratch** [comment]
@kozyraki Essentially, everything seems ok (I did not start mesos-dns in verbose mode, will have to try that). I setup `/etc/resolv.conf`, I verified the port 53 (udp/tcp) were open (on private network), dig/nslookup/host all worked.

With regards to PTR records, I may have misunderstood. I thought they would be required to support a client program that simply takes a hostname and passes it along to a library to do communications (HTTP, JMS (java), etc). I was imagining, since curl didn't work, that other sorts of clients would not work as well.

**Comment by kozyraki** [comment]
@mindscratch If you are still having problems with curl, there is another bug in there somewhere. We should hunt it down. The last thing I can imagine is the following a port issue. If you can "dig chronos.marathon.mesos" and get the correct answer, it may be that curl is not connecting to the right port. For example you may have to try  "curl http://chronos.marathon.mesos:8080" or whatever port chronos has been configured to listen too. On elastic mesos on GCE it is 4400. Have you checked for a port issue? Alternatively, you know it is a DNS problem if "curl http://chronos.marathon.mesos" does not work but ""curl http://<chronos-IP-address>" works.  

Let me know

**Comment by mindscratch** [comment]
@kozyraki so i've enabled verbose mode. On a single host, I have mesos-dns running. On that same host, I modified /etc/resolve.conf to add the IP address of the host as the first entry. I can successfully:

* dig chronos.marathon.mesos
* nslookup chronos.marathon.mesos

But, curl http://chronos.marathon.mesos:31890 (the random port chronos is listening on) returns:

```
curl: (6) Couldn't resolve host 'chronos.marathon.mesos'
```

**Comment by mindscratch** [comment]
@kozyraki looks like it was a `resolv.conf` configuration that was causing the problem with cURL.

The `/etc/resolv.conf` file looked like:

```
nameserver 192.168.1.5
nameserver 192.168.1.6
search mydomain.com
options ndots:1 timeout:2 attempts:2 rotate
```

The 192.168.1.5 IP is mesos-dns, the other IP is a named DNS server. Removing the `rotate` option resolved the curl issues. I'm going to try updating the "main" DNS server (192.168.1.6) so it knows about the mesos-dns server, which I hope will allow the "rotate" option to still be something I can set.

**Comment by kozyraki** [comment]
@mindscratch this is great information. Thank you for discovering the problem. 
I will update the troubleshooting guide to have a record of issue.

**Comment by tsenart** [comment]
The consensus here was the reverse lookups aren't something we want to support as of now.
