### ISSUE TITLE
Translation of framework names into hostnames

### ISSUE THREAD

**Issue by pcj** [mesosphere/mesos-dns#70]
mesos-dns will join `task-name`, `framework-name`, and `mesos` into a dot-separated identifier for DNS lookup purposes.  Currently, if `task-name` or `framework-name` contain characters that are are not legal URI characters, the identifier won't be a legal identifier in DNS, and won't be discoverable.

For example, the `cassandra-mesos` framework (not production ready) hardcodes the framework names as the token `Cassanda` +  `SPACE` + `${clusterName}`.  So unless you patch the source, you can't use `cassandra-mesos` with `mesos-dns`:  

```
task12345.Cassandra my-cluster-name.mesos
```

Consider providing an option to escape or normalize illegal URI characters in tasknames or framework names, such as converting spaces to underscore characters.

See http://golang.org/src/net/url/url.go?s=3942:3975#L65

**Comment by kozyraki** [comment]
Thanks @pcj . 
Can you also file an issue with the cassandra-mesos repo? :)

**Comment by eyberg** [comment]
c78034e55b987b62213f98923552fedebe3e0a82

**Comment by pcj** [comment]
@kozyraki  Will do but I'm not sure who is monitoring issues with `cassandra-mesos`.  Not very active.
