### ISSUE TITLE
Provide the ability to pass the configuration via STDIN

### ISSUE THREAD

**Issue by mindscratch** [mesosphere/mesos-dns#72]
Provide the ability to pass the configuration via STDIN.

**Comment by tsenart** [comment]
I've never seen this pattern for UNIX daemons or utilities. STDIN is usually for data, not configuration.
Currently we have a mix of configuration via flags and files. I'd like to consolidate it into one single approach but that wouldn't `stdin`.

If you feel strongly about this proposal, would you please elaborate on its rationale? Thanks.

**Comment by mindscratch** [comment]
It's been so long and I didn't provide any detail in the issue regarding why this might be useful, configuration via file and flags seems good enough.
