### ISSUE TITLE
Ability to make mesos-dns behave like a nameserver

### ISSUE THREAD

**Issue by tarnfeld** [mesosphere/mesos-dns#73]
It would be awesome if it were possible to configure mesos-dns to behave like a true nameserver (as that's really what it is). Perhaps a configuration option to disable the following?

- Refuse to make outbound recursive queries, e.g only respond to things inside the mesos domain
- Don't sent the RA bit in responses (Recursion Available)
  - More importantly, this shouldn't be set for the mesos responses anyway because as far as I can tell, mesos-dns doesn't recurse internal domains nor would it return a CNAM or NS records for an internal domain.
- A little more configuration around the values inserted into the SOA records

Regarding the first point, we should send the `REFUSED` status code back;

```
dig apple.com. @ns1.google.com

; <<>> DiG 9.9.5 <<>> apple.com. @ns1.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 54582
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;apple.com.			IN	A

;; Query time: 32 msec
;; SERVER: 216.239.32.10#53(216.239.32.10)
;; WHEN: Wed Jan 28 08:36:16 GMT 2015
;; MSG SIZE  rcvd: 27
```

Any thoughts? Happy to contribute the patches.

**Comment by benley** [comment]
It would be helpful if mesos-dns served up NS records for the domain it's hosting, too.  Without that I don't think it's possible to globally delegate a subdomain to mesos-dns, which I would like to do instead of using mesos-dns as the primary recursive/caching dns server for all my machines.

**Comment by benley** [comment]
(I might be incorrect about the necessity of authoritative NS records in delegated zones, but it would still be nice to support those)

**Comment by kozyraki** [comment]
@tarnfeld @benley Sorry for not looking into this earlier. Great suggestions. We'll start scoping it and get it done soon.

**Comment by tarnfeld** [comment]
@benley Yeah NS records aren't _strictly_ required but it's good to do it. The only thing that's really important is a correct SOA touting the right authority details.

**Comment by kozyraki** [comment]
@tarnfeld I thought we handle SOA correctly now. Can you let me know if there is still an issue with that one?

**Comment by tarnfeld** [comment]
It looks like it's handled OK but not very configurable. For example, it is often desirable to set the negative cache TTL very low but _not_ do the exact same for records. Currently both positive and negative TTLs are the same. Also, the serial is set to the current time which isn't very accurate... Correct me if I'm wrong but the timestamp is supposed to reflect the time the zone was last updated, so maybe the value of this should be updated when data is collected from the mesos master endpoint?

**Comment by kozyraki** [comment]
@tarnfeld the http branch introduces a flag to refuse outbound requests. It will be merged with the master after some further testing.

**Comment by cmaloney** [comment]
For a lot of setups the recursion is needed (Ex: I'm in a datacenter, sending all DNS to mesos-dns so I can rely on the .mesos names being reliable since I don't know what TLD is above mesos-dns), but definitely could make it possible to toggle the recursive behavior on/off, or make the behavior only available if querying mesos-dns from inside a network / on certain interfaces.

**Comment by kozyraki** [comment]
If some knowledgeable people make a list of all the things they want configurable (specific feature, specific range), these should be easy changes. I just need some help with making the list @tarnfeld @cmaloney

**Comment by cmaloney** [comment]
The major things I can see (although haven't read the specs lately, so not certain)

1. Ability to set what the domain is mesos-dns is authoritative for
1. Ability to enable / disable recursive behavior (Esp. for listening on "public" vs. "private" interfaces)
1. Be able to contain all the necessary "glue" records to have a domain delegated to it. 

The glue records can be fairly well tested by running two instances of mesos-dns, and having one delegate a subdomain to the other (Preferrably finding the other via discovery info). Once that is fully functional being able to tell an actual nameserver to delegate to mesos-dns should work fairly simply. I suspect the glue records will take quite a bit of work though (How does mesos-dns know what the ips of all running mesos-dns instances are to use as Nameservers? Ideally they should match what the delegator says they are, ...)

**Comment by kozyraki** [comment]
Ok gentlemen, I think I am finally done with this one. Here is what the http branch http branch includes:
- the ability to turn off serving of non Mesos requests (returns refused)
- full customization of all fields in the SOA record
- turn off the RA field for Mesos replies (since we do not recurse anyway)
So I think I am done. If not, please reopen and let me know what I missed or file new issues. 
The http branch will be tested for a while and then merged with the master soon. 
Thanks for the help.
