### ISSUE TITLE
Make master configuration optional

### ISSUE THREAD

**Issue by ssk2** [mesosphere/mesos-dns#75]
It's possible to make master configuration in the config file optional under the assumption that mesos-dns is running on a Mesos cluster (and also that the Mesos cluster it is running on is the one it will be serving DNS for).

By querying http://localhost:5051/slave(1)/state.json on startup, it's possible to pull out the configured master URI for the slave it is running on it. 

This will make it a little easier to deploy mesos-dns since the config then becomes considerably more "static".

**Comment by kozyraki** [comment]
We can probably provide a flag that instructs mesos-dns to do this. 
We will also replace the "masters" field with a "zk" field soon.

**Comment by kozyraki** [comment]
Implemented zookeeper detector (see master)
