### ISSUE TITLE
Support for roles

### ISSUE THREAD

**Issue by moderation** [mesosphere/mesos-dns#76]
I've been doing some testing with running multiple Marathon's in different roles attaching to a Mesos cluster. For example if I start up a Marathon in a "production" role and another Marathon in a "development" role. Tobi mentioned this at https://groups.google.com/d/msg/marathon-framework/yigM72K9Lec/YRNflQvC8lkJ

I doesn't appear that mesos-dns looks at the role so when I run the same application syncl in Marathon "production" and Marathon "development" they appear under a single mesos-dns entry ie.

```
VERBOSE: 2015/02/04 17:06:26 generator.go:329: [SRV]	_syncl._tcp.marathon.mesos.: localhost:31186
VERBOSE: 2015/02/04 17:06:26 generator.go:329: [SRV]	_syncl._udp.marathon.mesos.: localhost:31186
VERBOSE: 2015/02/04 17:06:26 generator.go:329: [A]	syncl.marathon.mesos.: localhost:31186
VERBOSE: 2015/02/04 17:06:26 generator.go:329: [SRV]	_syncl._tcp.marathon.mesos.: localhost:31542
VERBOSE: 2015/02/04 17:06:26 generator.go:329: [SRV]	_syncl._udp.marathon.mesos.: localhost:31542
VERBOSE: 2015/02/04 17:06:26 generator.go:329: [A]	syncl.marathon.mesos.: localhost:31542
VERBOSE: 2015/02/04 17:06:26 generator.go:329: [SRV]	_syncl._tcp.marathon.mesos.: localhost:31963
VERBOSE: 2015/02/04 17:06:26 generator.go:329: [SRV]	_syncl._udp.marathon.mesos.: localhost:31963
VERBOSE: 2015/02/04 17:06:26 generator.go:329: [A]	syncl.marathon.mesos.: localhost:31963
VERBOSE: 2015/02/04 17:06:26 generator.go:329: [SRV]	_syncl._tcp.marathon.mesos.: localhost:31054
VERBOSE: 2015/02/04 17:06:26 generator.go:329: [SRV]	_syncl._udp.marathon.mesos.: localhost:31054
VERBOSE: 2015/02/04 17:06:26 generator.go:329: [A]	syncl.marathon.mesos.: localhost:31054
```

It may be desirable to only want to route to the production or development instances of the application / task.  One way to get around this is to use different names ie. syncl_production and syncl_development or /production/syncl and /development/syncl. Does it make sense to incorporate Mesos roles into mesos-dns?

**Comment by kozyraki** [comment]
Yes, we definitely want richer and more flexible naming schemes. There are two issues here:
a) how to pass more interesting info about names to Mesos-DNS. 
For that, we have a good solution. Look at https://issues.apache.org/jira/browse/MESOS-2150. It will allow Marathon or any other task to pass all sorts of interesting names and info to Mesos about the tasks. For example, we can label a task X as being production, v 2.1, east-coast etc. 
b) What names should Mesos-DNS generate based on this info
For that we can use your feedback. One idea is to concatenate labels into names: so X becomes X.prod.v21.eastcoast.mesos. But others may prefer different schemes. 

Until this functionality is implemented, I suggest you use `--framework_name=marathon.prod` and `--framework_name=marathon-dev` when you launch each framework. This will allow Mesos-DNS to create names X.marathon.prod.mesos and X.marathon.dev.mesos.

**Comment by moderation** [comment]
Thanks for the --framework_name suggestion - working well.
