### ISSUE TITLE
Serve mesos-master and current leader as DNS entries

### ISSUE THREAD

**Issue by cmaloney** [mesosphere/mesos-dns#82]
When a new machine is coming up for the first time it is a lot nicer to be able to query for these rather than having to tell every machine them in advance. Just something like `master.mesos` and `leading.master.mesos` would be really useful for my use case. master.mesos could return either an A record for each master or SRV records if those queried for. leading.master.mesos would do the same, but always contain at most 1 record (At any given point in time there might not be a leading maser).

**Comment by kozyraki** [comment]
See #81 
Will be merged soon.
