### ISSUE TITLE
Setup builds on travis

### ISSUE THREAD

**Issue by guenter** [mesosphere/mesos-dns#91]
It would be nice to build all commits and PRs with Travis.

**Comment by lingmann** [comment]
@guenter let's use Teamcity instead. We have an unlimited license for open source projects and it's much more capable (already using it for CI builds of Marathon, Chronos, etc.) Community members can log in as guest and have full visibility to the open source builds.

**Comment by kozyraki** [comment]
@lingmann @guenter In retrospect, the simplest starting point is to push a docker with mesos-dns at dockerhub (currently we only push it to the private hub).

**Comment by tsenart** [comment]
We now have CI in place: https://circleci.com/gh/mesosphere/mesos-dns
