### ISSUE TITLE
Correct handling of AAAA (ipv6) DNS requests

### ISSUE THREAD

**Issue by ondrej-smola** [mesosphere/mesos-dns#94]
When requested for AAAA record

mesos-dns should return NODATA instead of NXDOMAIN when there are A or SRV records for requested entry

**Comment by kozyraki** [comment]
@ondrej-smola  how does #95 look to you? 
Let me know.

**Comment by ondrej-smola** [comment]
Hi,
it should work - i will test it on out dev env after lunch and give
feedback in case of any problems.

Thanks

2015-03-06 2:58 GMT+01:00 Christos Kozyrakis <notifications@github.com>:

**Comment by ondrej-smola** [comment]
Tested few use cases and it works.

**Comment by kozyraki** [comment]
Great. Looking forward to any further feedback from you.

**Comment by imrangit** [comment]
Is this issue resolved in mesos-dns 0.1.2 version? I am still seeing the issues when trying to "host" command. It works with "dig" command. I am using CentOS 6.5.

[ishaikh@mesosdev4 ~]$ host esdemo-1325-s4.elasticsearch.mesos
esdemo-1325-s4.elasticsearch.mesos has address 10.1.160.30
Host esdemo-1325-s4.elasticsearch.mesos not found: 3(NXDOMAIN)

[ishaikh@mesosdev4 ~]$ dig +short esdemo-1325-s4.elasticsearch.mesos
10.1.160.30
