### ISSUE TITLE
Config based on environment Vars

### ISSUE THREAD

**Issue by jrossi** [mesosphere/mesos-dns#97]
I have found environment variables to be some of the simplest ways to configure apps inside of docker.  With this would mesos-dns entertain a pull request that moves to arguments and environment variable or config file?

**Comment by ConnorDoyle** [comment]
@jrossi Yes, we'd be very interested in alternate ways of providing config values.  Requiring a config file can be awkward depdending on how mesos-dns is deployed.

**Comment by kozyraki** [comment]
@jrossi I've seen a couple of docker users using environment variables to generate the config file as part of the docker cmd :)

**Comment by kozyraki** [comment]
Hi @jrossi take a look at the http branch. This is finally converging to the point that is worth considering alternative configuration options, through command line flags or env variables (MESOS-DNS-XXX).

**Comment by tsenart** [comment]
I want to consolidate the configuration of mesos-dns to a *single* method. Right now it's split across flags and file which is not ideal. I'd rather have everything configured via flags. Would that work for you @jrossi ?

**Comment by jayzes** [comment]
FWIW, I put together a small Dockerfile and automated build to autogenerate a config file on launch based on environment variables. You can check it out at https://hub.docker.com/r/ello/mesos-dns-env/

**Comment by karlkfi** [comment]
+1 mesos-dns is a PITA to configure in docker as-is

Also, I don't thing consolidating is optimal. Optimize for UX, not dev laziness. In fact, I wrote a go lib to make it easy to accept a few different common methods: https://github.com/pivotal-cf-experimental/service-config

**Comment by tsenart** [comment]
Replaced by #257
